#!/usr/bin/env python3
"""
Patch 1: UI & Giao diện cốt lõi Translator for ONI
Đã tinh chỉnh theo phản hồi chuyên sâu:
- Nhãn menu ngắn gọn, chống tràn UI tối đa.
- Đúng bản chất tính năng game (Retire = Tổng kết thuộc địa, Consumables = Khẩu phần, v.v.).
- Không dùng dấu '/' trong nhãn cảnh báo.
- Bảo toàn thương hiệu, link tags, placeholders.
"""

import sys, re
sys.path.insert(0, '/Users/nam088/code/nam088/mod-game/Oxygen-Not-Included/strings')
import polib

def translate_ui_text(ctxt, text):
    if not text or not text.strip():
        return ""

    input_keys = {
        "Alt": "Alt", "Ctrl": "Ctrl", "Enter": "Enter", "Escape": "Esc", "Shift": "Shift",
        "Backspace": "Backspace", "Space": "Dấu cách", "Tab": "Tab",
        "Mouse Scroll Down": "Cuộn chuột xuống", "Mouse Scroll Up": "Cuộn chuột lên",
        "Left Mouse Button": "Chuột trái", "Right Mouse Button": "Chuột phải", "Middle Mouse Button": "Chuột giữa",
        "Left Click": "Nhấp chuột trái", "Right Click": "Nhấp chuột phải"
    }
    if text in input_keys:
        return input_keys[text]

    # Các nhãn UI cố định tinh chỉnh chuẩn xác
    ui_exact = {
        "RESUME": "TIẾP TỤC",
        "Resume Game": "Tiếp tục trò chơi",
        "NEW GAME": "TRÒ CHƠI MỚI",
        "New Game": "Trò chơi mới",
        "LOAD GAME": "TẢI MÀN CHƠI",
        "Load Game": "Tải màn chơi",
        "OPTIONS": "CÀI ĐẶT",
        "Options": "Cài đặt",
        "RETIRE": "TỔNG KẾT",
        "Retire": "Tổng kết thuộc địa",
        "SAVE": "LƯU GAME",
        "Save": "Lưu game",
        "SAVE AS": "LƯU THÀNH",
        "Save As": "Lưu thành",
        "QUIT": "THOÁT",
        "Quit": "Thoát",
        "QUIT TO MAIN MENU": "VỀ MENU CHÍNH",
        "Quit to Main Menu": "Về menu chính",
        "QUIT TO DESKTOP": "THOÁT RA MÀN HÌNH",
        "Quit to Desktop": "Thoát ra màn hình",
        "CANCEL": "HỦY",
        "Cancel": "Hủy",
        "CONFIRM": "XÁC NHẬN",
        "Confirm": "Xác nhận",
        "OK": "OK",
        "APPLY": "ÁP DỤNG",
        "Apply": "Áp dụng",
        "CLOSE": "ĐÓNG",
        "Close": "Đóng",
        "BACK": "QUAY LẠI",
        "Back": "Quay lại",
        "NEXT": "TIẾP THEO",
        "Next": "Tiếp theo",
        "PREVIOUS": "TRƯỚC ĐÓ",
        "Previous": "Trước đó",
        "DELETE": "XÓA",
        "Delete": "Xóa",
        "RENAME": "ĐỔI TÊN",
        "Rename": "Đổi tên",
        "DEFAULT": "MẶC ĐỊNH",
        "Default": "Mặc định",
        "PAUSE": "TẠM DỪNG",
        "Pause": "Tạm dừng",
        "PLAY": "CHẠY",
        "Play": "Chạy",
        "SLOW": "CHẬM",
        "Slow": "Chậm",
        "FAST": "NHANH",
        "Fast": "Nhanh",
        "VERY FAST": "RẤT NHANH",
        "Very Fast": "Rất nhanh",
        "ULTRA": "CỰC NHANH",
        "Ultra": "Cực nhanh",
        "AUTOMATION": "TỰ ĐỘNG HÓA",
        "Automation": "Tự động hóa",
        "OXYGEN": "OXY",
        "Oxygen": "Oxy",
        "POWER": "ĐIỆN",
        "Power": "Điện",
        "TEMPERATURE": "NHIỆT ĐỘ",
        "Temperature": "Nhiệt độ",
        "MATERIALS": "VẬT LIỆU",
        "Materials": "Vật liệu",
        "LIGHT": "ÁNH SÁNG",
        "Light": "Ánh sáng",
        "PLUMBING": "ỐNG NƯỚC",
        "Plumbing": "Chất lỏng",
        "VENTILATION": "THÔNG GIÓ",
        "Ventilation": "Thông gió",
        "DECOR": "TRANG TRÍ",
        "Decor": "Trang trí",
        "GERMS": "MẦM BỆNH",
        "Germs": "Mầm bệnh",
        "FARMING": "TRỒNG TRỌT",
        "Farming": "Trồng trọt",
        "RANCHING": "CHĂN NUÔI",
        "Ranching": "Chăn nuôi",
        "ROOMS": "PHÒNG ỐC",
        "Rooms": "Phòng ốc",
        "SUITS": "ĐỒ BẢO HỘ",
        "Suits": "Đồ bảo hộ",
        "RADIATION": "BỨC XẠ",
        "Radiation": "Bức xạ",
        "PRIORITIES": "ƯU TIÊN",
        "Priorities": "Độ ưu tiên",
        "SCHEDULE": "LỊCH TRÌNH",
        "Schedule": "Lịch trình",
        "CONSUMABLES": "KHẨU PHẦN",
        "Consumables": "Khẩu phần",
        "VITALS": "CHỈ SỐ SINH TỒN",
        "Vitals": "Chỉ số sinh tồn",
        "RESEARCH": "NGHIÊN CỨU",
        "Research": "Nghiên cứu",
        "SKILLS": "KỸ NĂNG",
        "Skills": "Kỹ năng",
        "STARMAP": "BẢN ĐỒ SAO",
        "Starmap": "Bản đồ sao",
        "COLONY SUMMARY": "TỔNG KẾT THUỘC ĐỊA",
        "Colony Summary": "Tổng kết thuộc địa",
        "PRINTING POD": "KÉN IN ẤN",
        "Printing Pod": "Kén in ấn",
        "IMMIGRANTS AVAILABLE": "CÓ ĐỆ MỚI SẴN SÀNG IN",
        "Immigrants Available": "Có Đệ mới sẵn sàng in",
        "NEW PRINTING AVAILABLE": "CÓ ĐỢT IN MỚI TRONG KÉN",
        "New Printing Available": "Có đợt in mới trong kén",
        "SELECT A BLUEPRINT": "CHỌN MỘT BẢN THIẾT KẾ",
        "Select a Blueprint": "Chọn một bản thiết kế",
        "PRINT": "IN RA",
        "Print": "In ra",
        "REJECT ALL": "TỪ CHỐI TẤT CẢ",
        "Reject All": "Từ chối tất cả",
        "CYCLE": "CHU KỲ",
        "Cycle": "Chu kỳ",
        "CALORIES": "CALO",
        "Calories": "Calo",
        "STRESS": "CĂNG THẲNG",
        "Stress": "Căng thẳng",
        "MORALE": "TINH THẦN",
        "Morale": "Tinh thần",
        "IDLE": "RẢNH RỖI",
        "Idle": "Rảnh rỗi",
        "IDLE DUPLICANTS": "ĐỆ ĐANG RẢNH RỖI",
        "Idle Duplicants": "Đệ đang rảnh rỗi",
        "SUFFOCATING": "ĐANG NGẠT THỞ!",
        "Suffocating": "Đang ngạt thở!",
        "STARVING": "ĐANG ĐÓI LẢ!",
        "Starving": "Đang đói lả!",
        "UNREACHABLE FOOD": "KHÔNG CÓ ĐƯỜNG TỚI ĐỒ ĂN",
        "Unreachable Food": "Không có đường tới đồ ăn",
        "Unreachable food": "Không có đường tới đồ ăn",
        "UNREACHABLE BED": "KHÔNG CÓ ĐƯỜNG VỀ GIƯỜNG",
        "Unreachable Bed": "Không có đường về giường",
        "Unreachable bed": "Không có đường về giường",
        "CIRCUIT OVERLOADED": "MẠCH ĐIỆN QUÁ TẢI",
        "Circuit Overloaded": "Mạch điện quá tải",
        "PIPE BLOCKED": "ỐNG DẪN BỊ TẮC",
        "Pipe Blocked": "Ống dẫn bị tắc",
        "PIPE BROKEN": "ỐNG DẪN BỊ VỠ",
        "Pipe Broken": "Ống dẫn bị vỡ",
        "GAS BLOCKED": "LỖ XẢ KHÍ BỊ NGHẼN",
        "Gas Blocked": "Lỗ xả khí bị nghẽn",
        "LIQUID BLOCKED": "LỖ XẢ NƯỚC BỊ NGẬP",
        "Liquid Blocked": "Lỗ xả nước bị ngập",
        "NO POWER": "MẤT ĐIỆN",
        "No Power": "Mất điện",
        "NOT CONNECTED": "CHƯA KẾT NỐI",
        "Not Connected": "Chưa kết nối",
        "STEAM WORKSHOP": "STEAM WORKSHOP",
        "Steam Workshop": "Steam Workshop",
        "KLEI INVENTORY": "KLEI INVENTORY",
        "DISCORD": "DISCORD",
        "Discord": "Discord"
    }

    if text in ui_exact:
        return ui_exact[text]

    return None
