#!/usr/bin/env python3
import json

# Batch 061 translation dictionary
b061 = {
  "STRINGS.UI.OUTFITS.ATMOSUIT_SPARKLE_BLUE.NAME": "Bộ Đồ Atmo Lấp Lánh Xanh Dương",
  "STRINGS.UI.OUTFITS.ATMOSUIT_SPARKLE_GREEN.NAME": "Bộ Đồ Atmo Lấp Lánh Xanh Lá",
  "STRINGS.UI.OUTFITS.ATMOSUIT_SPARKLE_LAVENDER.NAME": "Bộ Đồ Atmo Lấp Lánh Tím",
  "STRINGS.UI.OUTFITS.ATMOSUIT_SPARKLE_RED.NAME": "Bộ Đồ Atmo Lấp Lánh Đỏ",
  "STRINGS.UI.OUTFITS.ATMOSUIT_SPIFFY.NAME": "Bộ Đồ Atmo Bảnh Bao",
  "STRINGS.UI.OUTFITS.BALLET.NAME": "Trang Phục Ba Lê",
  "STRINGS.UI.OUTFITS.BASIC_AQUA.NAME": "Trang Phục Xanh Nước Biển Cơ Bản",
  "STRINGS.UI.OUTFITS.BASIC_BLACK.NAME": "Trang Phục Đen Cơ Bản",
  "STRINGS.UI.OUTFITS.BASIC_BLUE_COBALT.NAME": "Trang Phục Xanh Lam Thuần",
  "STRINGS.UI.OUTFITS.BASIC_DEEPRED.NAME": "Trang Phục Đội Trưởng",
  "STRINGS.UI.OUTFITS.BASIC_GREEN.NAME": "Trang Phục Xanh Lá Cơ Bản",
  "STRINGS.UI.OUTFITS.BASIC_GREEN_KELLY.NAME": "Trang Phục Cố Lên Cả Đội!",
  "STRINGS.UI.OUTFITS.BASIC_GREY_CHARCOAL.NAME": "Trang Phục Kẻ Yếu Thế",
  "STRINGS.UI.OUTFITS.BASIC_LEMON.NAME": "Trang Phục Hoạt Náo Viên",
  "STRINGS.UI.OUTFITS.BASIC_ORANGE.NAME": "Trang Phục Cam Cơ Bản",
  "STRINGS.UI.OUTFITS.BASIC_PINK_FLAMINGO.NAME": "Trang Phục Cổ Vũ",
  "STRINGS.UI.OUTFITS.BASIC_PINK_ORCHID.NAME": "Trang Phục Kẹo Cao Su Cơ Bản",
  "STRINGS.UI.OUTFITS.BASIC_PURPLE.NAME": "Trang Phục Tím Cơ Bản",
  "STRINGS.UI.OUTFITS.BASIC_RED.NAME": "Trang Phục Đỏ Cơ Bản",
  "STRINGS.UI.OUTFITS.BASIC_SATSUMA.NAME": "Trang Phục Fan Cuồng",
  "STRINGS.UI.OUTFITS.BASIC_WHITE.NAME": "Trang Phục Trắng Cơ Bản",
  "STRINGS.UI.OUTFITS.BASIC_YELLOW.NAME": "Trang Phục Vàng Cơ Bản",
  "STRINGS.UI.OUTFITS.CANUXTUX.NAME": "Bộ Tuxedo Canada",
  "STRINGS.UI.OUTFITS.CIRCUIT.NAME": "Trang Phục Tiệc Tùng LED",
  "STRINGS.UI.OUTFITS.DONOR.NAME": "Trang Phục Người Hiến Tặng",
  "STRINGS.UI.OUTFITS.DOWNTIME.NAME": "Trang Phục Giờ Nghỉ",
  "STRINGS.UI.OUTFITS.FLANNEL_BLACK.NAME": "Trang Phục Vải Nỉ Đơn Sắc",
  "STRINGS.UI.OUTFITS.FLANNEL_BLUE_MIDDLE.NAME": "Trang Phục Vải Nỉ Y Tế",
  "STRINGS.UI.OUTFITS.FLANNEL_GREEN.NAME": "Trang Phục Vải Nỉ Đầm Lầy",
  "STRINGS.UI.OUTFITS.FLANNEL_ORANGE.NAME": "Trang Phục Vải Nỉ Cadmium",
  "STRINGS.UI.OUTFITS.FLANNEL_PINK_ORCHID.NAME": "Trang Phục Vải Nỉ Rực Rỡ",
  "STRINGS.UI.OUTFITS.FLANNEL_PURPLE.NAME": "Trang Phục Vải Nỉ Hợp Nhất",
  "STRINGS.UI.OUTFITS.FLANNEL_RED.NAME": "Trang Phục Vải Nỉ Cổ Điển",
  "STRINGS.UI.OUTFITS.FLANNEL_WHITE.NAME": "Trang Phục Vải Nỉ Trắng",
  "STRINGS.UI.OUTFITS.FLANNEL_YELLOW.NAME": "Trang Phục Vải Nỉ Sợi Lanh",
  "STRINGS.UI.OUTFITS.GINCH_BILE.NAME": "Đồ Lót Bánh Vàng",
  "STRINGS.UI.OUTFITS.GINCH_CORTEX.NAME": "Đồ Lót Hoàng Hôn",
  "STRINGS.UI.OUTFITS.GINCH_FROSTY.NAME": "Đồ Lót Hồ Băng",
  "STRINGS.UI.OUTFITS.GINCH_GLUON.NAME": "Trang Phục Đá Muối Xếp Nếp",
  "STRINGS.UI.OUTFITS.GINCH_GOOP.NAME": "Đồ Lót Nhầy Nhụa",
  "STRINGS.UI.OUTFITS.GINCH_IRONBOW.NAME": "Đồ Lót Mắc-ma",
  "STRINGS.UI.OUTFITS.GINCH_LOCUS.NAME": "Đồ Lót Ấm Áp",
  "STRINGS.UI.OUTFITS.GINCH_NYBBLE.NAME": "Đồ Lót Nguyên Tử",
  "STRINGS.UI.OUTFITS.GINCH_OBELUS.NAME": "Đồ Lót Than Củi",
  "STRINGS.UI.OUTFITS.GINCH_PHLEGM.NAME": "Đồ Lót Đá Phiến",
  "STRINGS.UI.OUTFITS.GONCHIES_BLUEBERRY.NAME": "Đồ Lót Quản Trị Viên",
  "STRINGS.UI.OUTFITS.GONCHIES_GRAPE.NAME": "Đồ Lót Thuật Ngữ Thời Thượng",
  "STRINGS.UI.OUTFITS.GONCHIES_LEMON.NAME": "Đồ Lót Tư Duy Nhóm",
  "STRINGS.UI.OUTFITS.GONCHIES_LIME.NAME": "Đồ Lót Bên Liên Quan",
  "STRINGS.UI.OUTFITS.GONCHIES_SATSUMA.NAME": "Đồ Lót Cấp Dưới",
  "STRINGS.UI.OUTFITS.GONCHIES_STRAWBERRY.NAME": "Đồ Lót Giám Đốc",
  "STRINGS.UI.OUTFITS.GONCHIES_WATERMELON.NAME": "Đồ Lót Sức Mạnh Tổng Hợp",
  "STRINGS.UI.OUTFITS.HIVIS.NAME": "Trang Phục Phản Quang",
  "STRINGS.UI.OUTFITS.JELLYPUFF_BLUEBERRY.NAME": "Trang Phục Thạch Việt Quất",
  "STRINGS.UI.OUTFITS.JELLYPUFF_GRAPE.NAME": "Trang Phục Thạch Nho",
  "STRINGS.UI.OUTFITS.JELLYPUFF_LEMON.NAME": "Trang Phục Thạch Chanh Vàng",
  "STRINGS.UI.OUTFITS.JELLYPUFF_LIME.NAME": "Trang Phục Thạch Chanh Xanh",
  "STRINGS.UI.OUTFITS.JELLYPUFF_SATSUMA.NAME": "Trang Phục Thạch Quýt",
  "STRINGS.UI.OUTFITS.JELLYPUFF_STRAWBERRY.NAME": "Trang Phục Thạch Dâu",
  "STRINGS.UI.OUTFITS.JELLYPUFF_WATERMELON.NAME": "Trang Phục Thạch Dưa Hấu",
  "STRINGS.UI.OUTFITS.LUCKY.NAME": "Đồ Ngủ May Mắn",
  "STRINGS.UI.OUTFITS.MECHANIC.NAME": "Quần Áo Liền Quần Kỹ Sư",
  "STRINGS.UI.OUTFITS.NERD.NAME": "Trang Phục Nghiên Cứu",
  "STRINGS.UI.OUTFITS.PAJAMAS_SNOW.NAME": "Đồ Ngủ Pha Lê Băng",
  "STRINGS.UI.OUTFITS.POLKADOT_TRACKSUIT.NAME": "Đồ Thể Thao Chấm Bi",
  "STRINGS.UI.OUTFITS.POMPOM_SHINEBUGS_PINK_PEPPERNUT.NAME": "Trang Phục Bọ Bông Len",
  "STRINGS.UI.OUTFITS.REBELGI.NAME": "Võ Phục Nổi Loạn",
  "STRINGS.UI.OUTFITS.SLEEVELESS_BOW_BW.NAME": "Váy Tiến Sĩ",
  "STRINGS.UI.OUTFITS.SNOWFLAKE_BLUE.NAME": "Trang Phục Pha Lê Băng",
  "STRINGS.UI.OUTFITS.STANDARD_BLUE.NAME": "Đồng Phục Xanh Dương Chuẩn",
  "STRINGS.UI.OUTFITS.STANDARD_GREEN.NAME": "Đồng Phục Xanh Lá Chuẩn",
  "STRINGS.UI.OUTFITS.STANDARD_RED.NAME": "Đồng Phục Đỏ Chuẩn",
  "STRINGS.UI.OUTFITS.STANDARD_YELLOW.NAME": "Đồng Phục Vàng Chuẩn",
  "STRINGS.UI.OUTFITS.SUPERSTAR.NAME": "Trang Phục Siêu Sao",
  "STRINGS.UI.OUTFITS.SWEETHEART.NAME": "Đồ Ngủ Người Yêu",
  "STRINGS.UI.OUTFITS.TWEED_PINK_ORCHID.NAME": "Trang Phục Tiệc Trưa Doanh Nhân",
  "STRINGS.UI.OUTFITS.VELOUR_BLACK.NAME": "Trang Phục Nhung Tiến Sĩ",
  "STRINGS.UI.OUTFITS.VELOUR_BLUE.NAME": "Trang Phục Nhung Sóng Ngắn",
  "STRINGS.UI.OUTFITS.VELOUR_PINK.NAME": "Trang Phục Nhung Tia Gamma",
  "STRINGS.UI.OUTFITS.WAISTCOAT_PINSTRIPE_SLATE.NAME": "Trang Phục Kẻ Sọc Nobel",
  "STRINGS.UI.OUTFITS.WATER.NAME": "Quần Áo Liền Quần Thông Gió",
  "STRINGS.UI.OUTFITS.X_SPORCHID.NAME": "Trang Phục Lễ Hội Bào Tử",
  "STRINGS.UI.OUTFITS.X1_PINCHAPEPPERNUTBELLS.NAME": "Trang Phục Chuông Hạt Tiêu",
  "STRINGS.UI.OVERLAYS.CONVEYOR.BUTTON": "Lớp Phủ Băng Chuyền",
  "STRINGS.UI.OVERLAYS.CONVEYOR.INPUT": "Điểm Nhận",
  "STRINGS.UI.OVERLAYS.CONVEYOR.NAME": "LỚP PHỦ BĂNG CHUYỀN",
  "STRINGS.UI.OVERLAYS.CONVEYOR.OUTPUT": "Điểm Nạp",
  "STRINGS.UI.OVERLAYS.CONVEYOR.TOOLTIPS.INPUT": "<b>Điểm Nhận</b>\nNhận vật liệu từ <style=\"KKeyword\">Ray Băng Chuyền</style> và lưu trữ để Đệ sử dụng",
  "STRINGS.UI.OVERLAYS.CONVEYOR.TOOLTIPS.OUTPUT": "<b>Điểm Nạp</b>\nNạp vật liệu lên <style=\"KKeyword\">Ray Băng Chuyền</style> để vận chuyển đến các Điểm Nhận",
  "STRINGS.UI.OVERLAYS.CROP.BUTTON": "Lớp Phủ Trồng Trọt",
  "STRINGS.UI.OVERLAYS.CROP.FULLY_GROWN": "Đã Trưởng Thành Hoàn Toàn",
  "STRINGS.UI.OVERLAYS.CROP.GROWING": "Đang Lớn",
  "STRINGS.UI.OVERLAYS.CROP.GROWTH_HALTED": "Dừng Tăng Trưởng",
  "STRINGS.UI.OVERLAYS.CROP.NAME": "LỚP PHỦ TRỒNG TRỌT",
  "STRINGS.UI.OVERLAYS.CROP.TOOLTIPS.FULLY_GROWN": "<b>Đã Trưởng Thành Hoàn Toàn</b>\nNhững cây này đã phát triển hoàn chỉnh\n\nChọn <b>Công Cụ Thu Hoạch</b> {Hotkey/Harvest} để thu hoạch hàng loạt",
  "STRINGS.UI.OVERLAYS.CROP.TOOLTIPS.GROWING": "<b>Đang Lớn</b>\nNhững cây này đang phát triển tốt trong điều kiện hiện tại",
  "STRINGS.UI.OVERLAYS.CROP.TOOLTIPS.GROWTH_HALTED": "<b>Dừng Tăng Trưởng</b>\nĐiều kiện dưới mức tiêu chuẩn khiến những cây này không thể phát triển",
  "STRINGS.UI.OVERLAYS.CROPS.BUTTON": "Lớp Phủ Trồng Trọt",
  "STRINGS.UI.OVERLAYS.CROPS.NAME": "LỚP PHỦ TRỒNG TRỌT",
  "STRINGS.UI.OVERLAYS.DECOR.BUTTON": "Lớp Phủ Trang Trí",
  "STRINGS.UI.OVERLAYS.DECOR.CLOTHING": "Trang Phục Của {0}",
  "STRINGS.UI.OVERLAYS.DECOR.CLOTHING_TRAIT_DECORDOWN": "Trang Phục Của {0} (Ăn Mặc Luộm Thuộm)",
  "STRINGS.UI.OVERLAYS.DECOR.CLOTHING_TRAIT_DECORUP": "Trang Phục Của {0} (Phong Cách Bẩm Sinh)",
  "STRINGS.UI.OVERLAYS.DECOR.CLUTTER": "Mảnh Vụn",
  "STRINGS.UI.OVERLAYS.DECOR.COUNT": "({0})",
  "STRINGS.UI.OVERLAYS.DECOR.ENTRY": "{0} {1} {2}",
  "STRINGS.UI.OVERLAYS.DECOR.HEADER_NEGATIVE": "Giá Trị Tiêu Cực:",
  "STRINGS.UI.OVERLAYS.DECOR.HEADER_POSITIVE": "Giá Trị Tích Cực:",
  "STRINGS.UI.OVERLAYS.DECOR.HIGHDECOR": "Trang Trí Tích Cực",
  "STRINGS.UI.OVERLAYS.DECOR.HOVERTITLE": "TRANG TRÍ",
  "STRINGS.UI.OVERLAYS.DECOR.LIGHTING": "Ánh Sáng",
  "STRINGS.UI.OVERLAYS.DECOR.LOWDECOR": "Trang Trí Tiêu Cực",
  "STRINGS.UI.OVERLAYS.DECOR.MAXIMUM_DECOR": "{0}{1} (Trang Trí Tối Đa)",
  "STRINGS.UI.OVERLAYS.DECOR.NAME": "LỚP PHỦ TRANG TRÍ",
  "STRINGS.UI.OVERLAYS.DECOR.TOOLTIPS.HIGHDECOR": "<b>Trang Trí Tích Cực</b>\nKhu vực có giá trị <style=\"KKeyword\">Trang Trí</style> đầy đủ\n* Ánh sáng và các công trình đẹp mắt giúp tăng trang trí",
  "STRINGS.UI.OVERLAYS.DECOR.TOOLTIPS.LOWDECOR": "<b>Trang Trí Tiêu Cực</b>\nKhu vực có giá trị <style=\"KKeyword\">Trang Trí</style> không đạt\n* Tài nguyên rơi vãi trên sàn được coi là \"mảnh vụn\" và sẽ làm giảm trang trí",
  "STRINGS.UI.OVERLAYS.DECOR.TOTAL": "Tổng Điểm Trang Trí: ",
  "STRINGS.UI.OVERLAYS.DECOR.VALUE": "{0}{1}",
  "STRINGS.UI.OVERLAYS.DECOR.VALUE_ZERO": "{0}{1}",
  "STRINGS.UI.OVERLAYS.DISEASE.BUTTON": "Lớp Phủ Mầm Bệnh",
  "STRINGS.UI.OVERLAYS.DISEASE.CONTAINER_FORMAT": "\n    {0}: {1}",
  "STRINGS.UI.OVERLAYS.DISEASE.DISEASE_FORMAT": "{1} [{0}]<color=#{2}></color>",
  "STRINGS.UI.OVERLAYS.DISEASE.DISEASE_FORMAT_NO_COLOR": "{1} [{0}]",
  "STRINGS.UI.OVERLAYS.DISEASE.DISEASE_NAME_FORMAT": "{0}<color=#{1}></color>",
  "STRINGS.UI.OVERLAYS.DISEASE.DISEASE_NAME_FORMAT_NO_COLOR": "{0}",
  "STRINGS.UI.OVERLAYS.DISEASE.DISINFECT_THRESHOLD_DIAGRAM.MAX_LABEL": "1tr",
  "STRINGS.UI.OVERLAYS.DISEASE.DISINFECT_THRESHOLD_DIAGRAM.MIN_LABEL": "0",
  "STRINGS.UI.OVERLAYS.DISEASE.DISINFECT_THRESHOLD_DIAGRAM.THRESHOLD_PREFIX": "Khử Trùng Tại:",
  "STRINGS.UI.OVERLAYS.DISEASE.DISINFECT_THRESHOLD_DIAGRAM.TOOLTIP": "Tự động khử trùng bất kỳ công trình nào có hơn {NumberOfGerms} mầm bệnh.",
  "STRINGS.UI.OVERLAYS.DISEASE.DISINFECT_THRESHOLD_DIAGRAM.TOOLTIP_DISABLED": "Đã tắt tự động khử trùng công trình.",
  "STRINGS.UI.OVERLAYS.DISEASE.DISINFECT_THRESHOLD_DIAGRAM.UNITS": "Mầm Bệnh",
  "STRINGS.UI.OVERLAYS.DISEASE.HOVERTITLE": "Mầm Bệnh",
  "STRINGS.UI.OVERLAYS.DISEASE.INFECTION_SOURCE": "Nguồn Mầm Bệnh",
  "STRINGS.UI.OVERLAYS.DISEASE.INFECTION_SOURCE_TOOLTIP": "<b>Nguồn Mầm Bệnh</b>\nKhu vực sản sinh ra mầm bệnh\n• Đặt Chậu Rửa Tay hoặc Máy Khử Trùng Tay gần các khu vực này có thể ngăn ngừa dịch bệnh lây lan",
  "STRINGS.UI.OVERLAYS.DISEASE.NAME": "LỚP PHỦ MẦM BỆNH",
  "STRINGS.UI.OVERLAYS.DISEASE.NO_DISEASE": "Không có mầm bệnh trên bề mặt",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.BUTTON": "Lớp Phủ Điện Lực",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.DIAGRAM_HEADER": "Năng lượng từ <b>Ổ Cắm Trái</b> được sử dụng bởi <b>Ổ Cắm Phải</b>",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.LEGEND_SWITCH": "Công Tắc",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.LEGEND1": "<b>NGUỒN ĐIỆN CÔNG TRÌNH</b>",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.LEGEND2": "Tiêu Thụ",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.LEGEND3": "Sản Xuất",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.LEGEND4": "<b>TÌNH TRẠNG MẠCH ĐIỆN</b>",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.LEGEND5": "Không Hoạt Động",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.LEGEND6": "An Toàn",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.LEGEND7": "Căng Thẳng",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.LEGEND8": "Quá Tải",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.NAME": "LỚP PHỦ ĐIỆN LỰC",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.TOOLTIPS.LEGEND_SWITCH": "<b>Công Tắc</b>\nBật hoặc tắt các mạch điện được kết nối",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.TOOLTIPS.LEGEND1": "Hiển thị công trình đang tiêu thụ hay sản xuất <link=\"POWER\">Năng Lượng Điện</link>",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.TOOLTIPS.LEGEND2": "<b>Tiêu Thụ</b>\nCác công trình này rút điện từ mạch",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.TOOLTIPS.LEGEND3": "<b>Sản Xuất</b>\nCác công trình này phát điện cho mạch",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.TOOLTIPS.LEGEND4": "Hiển thị tình trạng của hệ thống dây điện",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.TOOLTIPS.LEGEND5": "<b>Không Hoạt Động</b>\nKhông có hoạt động điện nào trên các mạch này",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.TOOLTIPS.LEGEND6": "<b>An Toàn</b>\nCác mạch này không có nguy cơ bị quá tải",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.TOOLTIPS.LEGEND7": "<b>Căng Thẳng</b>\nCác mạch này sắp tiêu thụ nhiều điện hơn mức dây chịu tải",
  "STRINGS.UI.OVERLAYS.ELECTRICAL.TOOLTIPS.LEGEND8": "<b>Quá Tải</b>\nCác mạch này đang tiêu thụ nhiều điện hơn mức dây chịu tải",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.BUTTON": "Lớp Phủ Thông Khí",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.CONNECTED": "Đã Kết Nối",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.CONSUMER": "Ống Đầu Ra",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.DIAGRAM_AFTER_ARROW": "<b>Đầu Nạp Công Trình</b>",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.DIAGRAM_BEFORE_ARROW": "Khí chảy từ <b>Ống Đầu Ra</b>",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.DISCONNECTED": "Ngắt Kết Nối",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.FILTERED": "Ống Đầu Ra Đã Lọc",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.NAME": "LỚP PHỦ THÔNG KHÍ",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.NETWORK": "Mạng Lưới Khí {0}",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.PRODUCER": "Đầu Nạp Công Trình",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.TOOLTIPS.CONNECTED": "Đã kết nối với một <link=\"GASPIPING\">Ống Khí</link>",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.TOOLTIPS.CONSUMER": "<b>Ống Đầu Ra</b>\nĐầu ra dẫn <style=\"KKeyword\">Khí</style> vào <style=\"KKeyword\">Đường Ống</style>\n\nPhải nằm trên cùng mạng lưới với ít nhất một <link=\"GASPIPING\">Đầu Nạp</link>",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.TOOLTIPS.DISCONNECTED": "Chưa kết nối với <link=\"GASPIPING\">Ống Khí</link>",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.TOOLTIPS.FILTERED": "<b>Ống Đầu Ra Đã Lọc</b>\nĐầu ra đã lọc dẫn <style=\"KKeyword\">Khí</style> đã lọc vào <style=\"KKeyword\">Đường Ống</style>\n\nPhải nằm trên cùng mạng lưới với ít nhất một <link=\"GASPIPING\">Đầu Nạp</link>",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.TOOLTIPS.NETWORK": "Mạng lưới khí {0}",
  "STRINGS.UI.OVERLAYS.GASPLUMBING.TOOLTIPS.PRODUCER": "<b>Đầu Nạp Công Trình</b>\nĐầu nạp đưa khí vào trong công trình\n\nPhải nằm trên cùng mạng lưới với ít nhất một <link=\"GASPIPING\">Đầu Ra</link>",
  "STRINGS.UI.OVERLAYS.HEATFLOW.BUTTON": "Lớp Phủ Chịu Nhiệt",
  "STRINGS.UI.OVERLAYS.HEATFLOW.COOLING": "Mất Nhiệt Thân Thể",
  "STRINGS.UI.OVERLAYS.HEATFLOW.COOLING_DUPE": "Mất Nhiệt Thân Thể {0}\n\nMôi trường xung quanh lạnh khó chịu",
  "STRINGS.UI.OVERLAYS.HEATFLOW.HEATING": "Tích Nhiệt Thân Thể",
  "STRINGS.UI.OVERLAYS.HEATFLOW.HEATING_DUPE": "Mất Nhiệt Thân Thể {0}\n\nMôi trường xung quanh nóng bức khó chịu",
  "STRINGS.UI.OVERLAYS.HEATFLOW.HOVERTITLE": "CHỊU NHIỆT",
  "STRINGS.UI.OVERLAYS.HEATFLOW.NAME": "LỚP PHỦ CHỊU NHIỆT",
  "STRINGS.UI.OVERLAYS.HEATFLOW.NEUTRAL": "Vùng Thoải Mái",
  "STRINGS.UI.OVERLAYS.HEATFLOW.NEUTRAL_DUPE": "Vùng Thoải Mái {0}",
  "STRINGS.UI.OVERLAYS.HEATFLOW.TOOLTIPS.COOLING": "<b>Mất Nhiệt Thân Thể</b>\nLạnh khó chịu\n\nĐệ mất nhiều nhiệt vào môi trường lạnh hơn mức có thể hấp thụ\n    • Áo Ấm giúp Đệ giữ nhiệt thân thể",
  "STRINGS.UI.OVERLAYS.HEATFLOW.TOOLTIPS.HEATING": "<b>Tích Nhiệt Thân Thể</b>\nNóng khó chịu\n\nĐệ hấp thụ nhiều nhiệt từ môi trường nóng hơn mức có thể tỏa ra",
  "STRINGS.UI.OVERLAYS.HEATFLOW.TOOLTIPS.NEUTRAL": "<b>Vùng Thoải Mái</b>\nKhu vực dễ chịu\n\nĐệ có thể tự điều hòa thân nhiệt tại các khu vực này",
  "STRINGS.UI.OVERLAYS.JOULES.BUTTON": "Lớp Phủ Joules",
  "STRINGS.UI.OVERLAYS.JOULES.HOVERTITLE": "JOULES",
  "STRINGS.UI.OVERLAYS.JOULES.NAME": "JOULES",
  "STRINGS.UI.OVERLAYS.LIGHTING.BUTTON": "Lớp Phủ Ánh Sáng",
  "STRINGS.UI.OVERLAYS.LIGHTING.DARK": "Khu Vực Tối",
  "STRINGS.UI.OVERLAYS.LIGHTING.DESC": "{0} Lux",
  "STRINGS.UI.OVERLAYS.LIGHTING.HOVERTITLE": "ÁNH SÁNG",
  "STRINGS.UI.OVERLAYS.LIGHTING.LITAREA": "Khu Vực Sáng",
  "STRINGS.UI.OVERLAYS.LIGHTING.NAME": "LỚP PHỦ ÁNH SÁNG",
  "STRINGS.UI.OVERLAYS.LIGHTING.RANGES.HIGH_LIGHT": "Sáng",
  "STRINGS.UI.OVERLAYS.LIGHTING.RANGES.LOW_LIGHT": "Mờ",
  "STRINGS.UI.OVERLAYS.LIGHTING.RANGES.MAX_LIGHT": "Chói Mắt",
  "STRINGS.UI.OVERLAYS.LIGHTING.RANGES.MEDIUM_LIGHT": "Chiếu Sáng Tốt",
  "STRINGS.UI.OVERLAYS.LIGHTING.RANGES.NO_LIGHT": "Tối Đen Như Mực",
  "STRINGS.UI.OVERLAYS.LIGHTING.RANGES.VERY_HIGH_LIGHT": "Rực Rỡ",
  "STRINGS.UI.OVERLAYS.LIGHTING.RANGES.VERY_LOW_LIGHT": "Rất Mờ",
  "STRINGS.UI.OVERLAYS.LIGHTING.TOOLTIPS.DARK": "<b>Khu Vực Tối</b>\nLàm việc trong bóng tối không ảnh hưởng đến Đệ",
  "STRINGS.UI.OVERLAYS.LIGHTING.TOOLTIPS.LITAREA": "<b>Khu Vực Sáng</b>\nLàm việc trong khu vực chiếu sáng tốt giúp cải thiện <style=\"KKeyword\">Đạo Đức</style> của Đệ",
  "STRINGS.UI.OVERLAYS.LIGHTING.TOOLTIPS.NAME": "LỚP PHỦ ÁNH SÁNG",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.BUTTON": "Lớp Phủ Dẫn Nước",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.CONNECTED": "Đã Kết Nối",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.CONSUMER": "Ống Đầu Ra",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.DIAGRAM_AFTER_ARROW": "<b>Đầu Nạp Công Trình</b>",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.DIAGRAM_BEFORE_ARROW": "Chất lỏng chảy từ <b>Ống Đầu Ra</b>",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.DISCONNECTED": "Ngắt Kết Nối",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.FILTERED": "Ống Đầu Ra Đã Lọc",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.NAME": "LỚP PHỦ DẪN NƯỚC",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.NETWORK": "Mạng Lưới Chất Lỏng {0}",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.PRODUCER": "Đầu Nạp Công Trình",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.TOOLTIPS.CONNECTED": "Đã kết nối với một <link=\"LIQUIDCONDUIT\">Ống Chất Lỏng</link>",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.TOOLTIPS.CONSUMER": "<b>Ống Đầu Ra</b>\nĐầu ra dẫn chất lỏng vào đường ống\n\nPhải nằm trên cùng mạng lưới với ít nhất một <link=\"LIQUIDPIPING\">Đầu Nạp</link>",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.TOOLTIPS.DISCONNECTED": "Chưa kết nối với <link=\"LIQUIDCONDUIT\">Ống Chất Lỏng</link>",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.TOOLTIPS.FILTERED": "<b>Ống Đầu Ra Đã Lọc</b>\nĐầu ra đã lọc dẫn chất lỏng đã lọc vào đường ống\n\nPhải nằm trên cùng mạng lưới với ít nhất một <link=\"LIQUIDPIPING\">Đầu Nạp</link>",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.TOOLTIPS.NETWORK": "Mạng lưới chất lỏng {0}",
  "STRINGS.UI.OVERLAYS.LIQUIDPLUMBING.TOOLTIPS.PRODUCER": "<b>Đầu Nạp Công Trình</b>\nĐầu nạp đưa chất lỏng vào trong công trình\n\nPhải nằm trên cùng mạng lưới với ít nhất một <link=\"LIQUIDPIPING\">Đầu Ra</link>",
  "STRINGS.UI.OVERLAYS.LOGIC.BUTTON": "Lớp Phủ Tự Động Hóa",
  "STRINGS.UI.OVERLAYS.LOGIC.CIRCUIT_STATUS_HEADER": "TRẠNG THÁI LƯỚI",
  "STRINGS.UI.OVERLAYS.LOGIC.CONTROL_INPUT": "Cổng Điều Khiển",
  "STRINGS.UI.OVERLAYS.LOGIC.DISCONNECTED": "NGẮT KẾT NỐI",
  "STRINGS.UI.OVERLAYS.LOGIC.INPUT": "Cổng Đầu Vào",
  "STRINGS.UI.OVERLAYS.LOGIC.NAME": "LỚP PHỦ TỰ ĐỘNG HÓA",
  "STRINGS.UI.OVERLAYS.LOGIC.ONE": "Xanh Lá",
  "STRINGS.UI.OVERLAYS.LOGIC.OUTPUT": "Cổng Đầu Ra",
  "STRINGS.UI.OVERLAYS.LOGIC.RESET_UPDATE": "Cổng Đặt Lại",
  "STRINGS.UI.OVERLAYS.LOGIC.RIBBON_INPUT": "Cổng Dây Băng Đầu Vào",
  "STRINGS.UI.OVERLAYS.LOGIC.RIBBON_OUTPUT": "Cổng Dây Băng Đầu Ra",
  "STRINGS.UI.OVERLAYS.LOGIC.TOOLTIPS.CONTROL_INPUT": "<b>Cổng Điều Khiển</b>\nĐiều khiển việc chọn tín hiệu của một <link=\"LOGICGATEMULTIPLEXER\">Bộ Chọn Tín Hiệu</link> hoặc <link=\"LOGICGATEDEMULTIPLEXER\">Bộ Phân Phối Tín Hiệu</link>",
  "STRINGS.UI.OVERLAYS.LOGIC.TOOLTIPS.DISCONNECTED": "<b>Ngắt Kết Nối</b>\nCổng này chưa kết nối với lưới tự động hóa",
  "STRINGS.UI.OVERLAYS.LOGIC.TOOLTIPS.INPUT": "<b>Cổng Đầu Vào</b>\nNhận tín hiệu từ lưới tự động hóa",
  "STRINGS.UI.OVERLAYS.LOGIC.TOOLTIPS.ONE": "<b>Xanh Lá</b>\nCổng này hiện đang <b><style=\"logic_on\">Xanh Lá</style></b>",
  "STRINGS.UI.OVERLAYS.LOGIC.TOOLTIPS.OUTPUT": "<b>Cổng Đầu Ra</b>\nGửi tín hiệu ra lưới tự động hóa",
  "STRINGS.UI.OVERLAYS.LOGIC.TOOLTIPS.RESET_UPDATE": "<b>Cổng Đặt Lại</b>\nĐặt lại Bộ Nhớ trong của <link=\"LOGICMEMORY\">Công Tắc Nhớ</link> về <b><style=\"logic_off\">Đỏ</style></b>",
  "STRINGS.UI.OVERLAYS.LOGIC.TOOLTIPS.RIBBON_INPUT": "<b>Cổng Dây Băng Đầu Vào</b>\nNhận tín hiệu 4-bit từ lưới tự động hóa",
  "STRINGS.UI.OVERLAYS.LOGIC.TOOLTIPS.RIBBON_OUTPUT": "<b>Cổng Dây Băng Đầu Ra</b>\nGửi tín hiệu 4-bit ra lưới tự động hóa",
  "STRINGS.UI.OVERLAYS.LOGIC.TOOLTIPS.ZERO": "<b>Đỏ</b>\nCổng này hiện đang <b><style=\"logic_off\">Đỏ</style></b>",
  "STRINGS.UI.OVERLAYS.LOGIC.ZERO": "Đỏ",
  "STRINGS.UI.OVERLAYS.OXYGEN.BUTTON": "Lớp Phủ Oxy",
  "STRINGS.UI.OVERLAYS.OXYGEN.LEGEND1": "Rất Dễ Thở",
  "STRINGS.UI.OVERLAYS.OXYGEN.LEGEND2": "Thở Được",
  "STRINGS.UI.OVERLAYS.OXYGEN.LEGEND3": "Hơi Khó Thở",
  "STRINGS.UI.OVERLAYS.OXYGEN.LEGEND4": "Không Thể Thở",
  "STRINGS.UI.OVERLAYS.OXYGEN.LEGEND5": "Hơi Độc",
  "STRINGS.UI.OVERLAYS.OXYGEN.LEGEND6": "Rất Độc",
  "STRINGS.UI.OVERLAYS.OXYGEN.NAME": "LỚP PHỦ OXY",
  "STRINGS.UI.OVERLAYS.OXYGEN.TOOLTIPS.LEGEND1": "<b>Rất Dễ Thở</b>\nNồng độ <style=\"KKeyword\">Oxy</style> cao",
  "STRINGS.UI.OVERLAYS.OXYGEN.TOOLTIPS.LEGEND2": "<b>Thở Được</b>\nNồng độ <style=\"KKeyword\">Oxy</style> đầy đủ",
  "STRINGS.UI.OVERLAYS.OXYGEN.TOOLTIPS.LEGEND3": "<b>Hơi Khó Thở</b>\nNồng độ <style=\"KKeyword\">Oxy</style> thấp",
  "STRINGS.UI.OVERLAYS.OXYGEN.TOOLTIPS.LEGEND4": "<b>Không Thể Thở</b>\nNồng độ <style=\"KKeyword\">Oxy</style> cực thấp hoặc không có\n\nĐệ sẽ bị ngạt thở nếu kẹt trong các khu vực này",
  "STRINGS.UI.OVERLAYS.OXYGEN.TOOLTIPS.LEGEND5": "<b>Hơi Độc</b>\nNồng độ khí có hại",
  "STRINGS.UI.OVERLAYS.OXYGEN.TOOLTIPS.LEGEND6": "<b>Rất Độc</b>\nNồng độ khí gây chết người",
  "STRINGS.UI.OVERLAYS.POWER.WATTS_CONSUMED": "Watt Tiêu Thụ",
  "STRINGS.UI.OVERLAYS.POWER.WATTS_GENERATED": "Watt Sản Xuất",
  "STRINGS.UI.OVERLAYS.PRIORITIES.BUTTON": "Lớp Phủ Độ Ưu Tiên",
  "STRINGS.UI.OVERLAYS.PRIORITIES.EIGHT": "8",
  "STRINGS.UI.OVERLAYS.PRIORITIES.EIGHT_TOOLTIP": "Ưu Tiên 8",
  "STRINGS.UI.OVERLAYS.PRIORITIES.FIVE": "5",
  "STRINGS.UI.OVERLAYS.PRIORITIES.FIVE_TOOLTIP": "Ưu Tiên 5",
  "STRINGS.UI.OVERLAYS.PRIORITIES.FOUR": "4",
  "STRINGS.UI.OVERLAYS.PRIORITIES.FOUR_TOOLTIP": "Ưu Tiên 4",
  "STRINGS.UI.OVERLAYS.PRIORITIES.NAME": "LỚP PHỦ ĐỘ ƯU TIÊN",
  "STRINGS.UI.OVERLAYS.PRIORITIES.NINE": "9 (Khẩn Cấp Cao)",
  "STRINGS.UI.OVERLAYS.PRIORITIES.NINE_TOOLTIP": "Ưu Tiên 9",
  "STRINGS.UI.OVERLAYS.PRIORITIES.ONE": "1 (Khẩn Cấp Thấp)",
  "STRINGS.UI.OVERLAYS.PRIORITIES.ONE_TOOLTIP": "Ưu Tiên 1",
  "STRINGS.UI.OVERLAYS.PRIORITIES.SEVEN": "7",
  "STRINGS.UI.OVERLAYS.PRIORITIES.SEVEN_TOOLTIP": "Ưu Tiên 7",
  "STRINGS.UI.OVERLAYS.PRIORITIES.SIX": "6",
  "STRINGS.UI.OVERLAYS.PRIORITIES.SIX_TOOLTIP": "Ưu Tiên 6",
  "STRINGS.UI.OVERLAYS.PRIORITIES.THREE": "3",
  "STRINGS.UI.OVERLAYS.PRIORITIES.THREE_TOOLTIP": "Ưu Tiên 3",
  "STRINGS.UI.OVERLAYS.PRIORITIES.TWO": "2",
  "STRINGS.UI.OVERLAYS.PRIORITIES.TWO_TOOLTIP": "Ưu Tiên 2",
  "STRINGS.UI.OVERLAYS.RADIATION.BUTTON": "Lớp Phủ Phóng Xạ",
  "STRINGS.UI.OVERLAYS.RADIATION.DESC": "{rads} mỗi chu kỳ ({description})",
  "STRINGS.UI.OVERLAYS.RADIATION.HOVERTITLE": "PHÓNG XẠ",
  "STRINGS.UI.OVERLAYS.RADIATION.NAME": "PHÓNG XẠ",
  "STRINGS.UI.OVERLAYS.RADIATION.RANGES.HIGH": "Mối Nguy Đáng Kể",
  "STRINGS.UI.OVERLAYS.RADIATION.RANGES.INPUTPORT": "Cổng Đầu Vào Tia Bức Xạ",
  "STRINGS.UI.OVERLAYS.RADIATION.RANGES.LOW": "Vừa Đủ An Toàn",
  "STRINGS.UI.OVERLAYS.RADIATION.RANGES.MAX": "Mối Nguy Tối Đa",
  "STRINGS.UI.OVERLAYS.RADIATION.RANGES.MEDIUM": "Mối Nguy Nhẹ",
  "STRINGS.UI.OVERLAYS.RADIATION.RANGES.NONE": "Hoàn Toàn An Toàn",
  "STRINGS.UI.OVERLAYS.RADIATION.RANGES.OUTPUTPORT": "Cổng Đầu Ra Tia Bức Xạ",
  "STRINGS.UI.OVERLAYS.RADIATION.RANGES.VERY_HIGH": "Mối Nguy Cực Độ",
  "STRINGS.UI.OVERLAYS.RADIATION.RANGES.VERY_LOW": "Hầu Như An Toàn",
  "STRINGS.UI.OVERLAYS.RADIATION.SHIELDING_DESC": "Chắn Phóng Xạ: {radiationAbsorptionFactor}",
  "STRINGS.UI.OVERLAYS.RADIATION.TOOLTIPS.HIGH": "Mối Nguy Đáng Kể",
  "STRINGS.UI.OVERLAYS.RADIATION.TOOLTIPS.INPUTPORT": "Cổng Đầu Vào Tia Bức Xạ",
  "STRINGS.UI.OVERLAYS.RADIATION.TOOLTIPS.LOW": "Vừa Đủ An Toàn",
  "STRINGS.UI.OVERLAYS.RADIATION.TOOLTIPS.MAX": "Mối Nguy Tối Đa",
  "STRINGS.UI.OVERLAYS.RADIATION.TOOLTIPS.MEDIUM": "Mối Nguy Nhẹ",
  "STRINGS.UI.OVERLAYS.RADIATION.TOOLTIPS.NONE": "Hoàn Toàn An Toàn",
  "STRINGS.UI.OVERLAYS.RADIATION.TOOLTIPS.OUTPUTPORT": "Cổng Đầu Ra Tia Bức Xạ",
  "STRINGS.UI.OVERLAYS.RADIATION.TOOLTIPS.VERY_HIGH": "Mối Nguy Cực Độ",
  "STRINGS.UI.OVERLAYS.RADIATION.TOOLTIPS.VERY_LOW": "Hầu Như An Toàn"
}

with open("Oxygen-Not-Included/strings/ai_batches_compact/batch_061.json", "w", encoding="utf-8") as f:
    json.dump(b061, f, ensure_ascii=False, indent=2)

print("Saved batch_061.json successfully")
