import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(PROJECT_ROOT, "translations", "03_Resources_Items_Tech.json")

T = {
  # 1. Crops
  "crop.spices": "Cây Gia Vị",
  "crop.mushrooms": "Nấm Ăn",

  # 2. Policies & Decrees (50 items)
  "policy.title.increasedCarryCapacity": "Còng Lưng Khuân Vác",
  "policy.desc.increasedCarryCapacity": "Bà con chuột có thể mang vác thêm +2 tài nguyên.",
  "policy.title.improvedscience": "Khoảnh Khắc Eureka",
  "policy.desc.improvedScience": "Phòng nghiên cứu thỉnh thoảng tạo ra thêm +1 điểm tri thức miễn phí.",
  "policy.desc.betterlogistics": "Thợ kho tăng thêm +4 sức khuân vác. Băng chuyền vận hành nhanh hơn 20%.",
  "policy.title.betterlogistics": "Bôi Trơn Xe Kéo",
  "policy.title.stripmine": "Khai Thác Lộ Thiên",
  "policy.desc.negotiations": "Hợp đồng xuất khẩu thưởng thêm 20% điểm phát triển nhưng giảm 20% các phần thưởng khác.",
  "policy.title.lushGardens": "Vườn Tược Tốt Tươi",
  "policy.desc.lushGardens": "Người làm vườn dùng lượng nước gấp đôi, giúp vườn tược sau khi tưới đạt hiệu quả gấp đôi.",
  "policy.desc.stripmine": "Tốc độ khai mỏ tăng gấp đôi.\n\nNhưng có 20% tỉ lệ làm hỏng mất tài nguyên khai thác.",
  "policy.title.negotiations": "Đàm Phán Hợp Đồng",
  "policy.title.coldresist": "Tôi Luyện Băng Giá",
  "policy.desc.coldresist": "Bà con chuột miễn nhiễm với mọi bất lợi do giá rét gây ra.",
  "policy.title.rapidConstruction": "Thi Công Thần Tốc",
  "policy.desc.rapidConstruction": "Thợ xây tăng mạnh tốc độ thi công và tốc độ di chuyển.",
  "policy.title.stretchfood": "Gia Vị Mạt Cưa",
  "policy.desc.stretchfood": "25% cơ hội các xưởng chế biến thực phẩm tạo ra sản lượng gấp đôi.",
  "policy.title.foodrationing": "Thắt Lưng Buộc Bụng",
  "policy.desc.foodrationing": "Bà con chuột tự hạn chế chỉ ăn một bữa mỗi ngày.\n(Bỏ bữa trưa).",
  "policy.title.extrarations": "Tăng Khẩu Phần",
  "policy.desc.extrarations": "Bà con chuột được phép ăn thêm 1 phần ăn mỗi bữa.",
  "policy.title.dirtyfuel": "Đốt Rác Sưởi Ấm",
  "policy.desc.dirtyfuel": "Nhiên liệu cháy lâu hơn trong lò sưởi, nhưng xả ra lượng ô nhiễm gấp đôi.",
  "policy.title.movespeed": "Bước Chân Thoăn Thoắt",
  "policy.desc.movespeed": "Toàn bộ dân chuột di chuyển nhanh hơn 20%.",
  "policy.title.extrawood": "Đào Bới Gốc Cây",
  "policy.desc.extrawood": "Đào bật gốc cây khi đốn gỗ có cơ hội thu thêm gỗ khúc.",
  "policy.title.directtax": "Thu Thuế Trực Tiếp",
  "policy.desc.directtax": "Đi quanh làng đòi thu thuế mỗi ngày từ từng chú chuột để bù vào nợ thuế cống nạp.",
  "policy.title.intimidatingstatues": "Đôi Mắt Đá",
  "policy.desc.intimidatingstatues": "Hiệu ứng tăng tốc khi đi ngang qua các tượng đài thị uy được gia tăng và kéo dài gấp đôi.",
  "policy.costUnit.perIntimidation": "Mỗi Lần Thị Uy",
  "policy.costUnit.perBonusOutput": "Mỗi Sản Lượng Thưởng Thêm",
  "policy.costUnit.perCollection": "Mỗi Lần Thu Gom",
  "policy.costUnit.perMinedResource": "Mỗi Tài Nguyên Khai Thác",
  "policy.costUnit.perCut": "Mỗi Lần Đốn Hạ",
  "policy.costUnit.perSkippedFood": "Mỗi Bữa Ăn Cắt Giảm",
  "policy.costUnit.perConstructionTask": "Mỗi Dự Án Thi Công",
  "policy.costUnit.perHeavyPickup": "Mỗi Chuyến Vác Nặng",
  "policy.spentToday": "Đã Chi Hôm Nay",
  "policy.noUpkeep": "Không Tốn Chi Phí Duy Trì",
  "policy.title.lateconstruction": "Thi Công Ban Đêm",
  "policy.desc.lateconstruction": "Thợ thuyền tiếp tục thi công công trình dưới ánh nến đêm.",
  "policy.title.trinkets": "Gia Công Đồ Mỹ Nghệ",
  "policy.desc.trinkets": "Chuột tận dụng thời gian rảnh rỗi sau giờ làm để chế tác đồ mỹ nghệ đem bán.",
  "policy.costUnit.perTrinket": "Mỗi Món Đồ Mỹ Nghệ",
  "policy.title.fastshuttles": "Hải Trình Bạt Mạng",
  "policy.desc.fastshuttles": "Bè mảng và thuyền chở khách cỡ nhỏ nhận lệnh phải di chuyển nhanh hơn.",
  "policy.costUnit.perShipDeparted": "Mỗi Chuyến Tàu Rời Bến",

  # 3. Tech Unlocks & Schematics (78 items)
  "unlock.farming.title": "Nông Nghiệp Cơ Bản",
  "unlock.farming.desc": "Bản vẽ Nông Trại và Công Cụ Trồng Trọt.\n\nCó thể gán giống cây trồng cho các thửa ruộng, cây sẽ phát triển tùy theo độ màu mỡ của đất.",
  "unlock.elevator.tile": "Thang Máy",
  "unlock.elevator.desc": "Vận chuyển thẳng đứng tốc độ cao.\n\nCó thể xếp chồng Trục và Cửa Vào để tạo thành Thang Máy.",
  "unlock.waterPumping.title": "Máy Bơm Nước",
  "unlock.waterPumping.desc": "Máy bơm nước biển có thể cấp nước cho các dịch vụ và ngành chế biến qua mạng lưới đường ống.",
  "unlock.steam.title": "Năng Lượng Hơi Nước",
  "unlock.steam.desc": "Nồi hơi dẫn hơi nước vào mạng lưới ống chuyên dụng. Hơi nước nén áp suất cao có thể sưởi ấm và trợ lực cho máy móc hạng nặng.\n\nNồi hơi cần Trại Chăm Lửa để tiếp tế nhiên liệu.",
  "unlock.aimBasic.title": "Băng Chuyền Cơ Bản",
  "unlock.aimBasic.desc": "Vận chuyển tài nguyên trên băng chuyền từ Phễu Nạp đến các kho chứa.\n\nCác nhà xưởng có thể chọn Phễu Nạp làm điểm trả hàng.",
  "unlock.housingTier1.title": "Nhà Ván Gỗ",
  "unlock.housingTier1.desc": "Chất lượng nhà ở mức trung bình, có nhiều kích cỡ mặt bằng khác nhau.",
  "unlock.housingTier2.title": "Nhà Đá",
  "unlock.housingTier2.desc": "Chất lượng nhà ở cao, có nhiều kích cỡ mặt bằng khác nhau.",
  "unlock.housingTier3.title": "Nhà Sang Trọng",
  "unlock.housingTier3.desc": "Chất lượng nhà ở rất cao nhờ có hệ thống cấp thoát nước, nhưng cần kết nối với đường ống nước sạch.",
  "unlock.recipe.advancedResearch.title": "Nghiên Cứu Chuyên Sâu",
  "unlock.recipe.advancedResearch.desc": "Nghiên cứu nâng cao mở khóa các công nghệ thời kỳ hơi nước phức tạp.",
  "unlock.luxuries.title": "Phân Phối Hàng Xa Xỉ",
  "unlock.luxuries.desc": "Cho phép xây Tiệm Cung Ứng Hàng Xa Xỉ để phân phát đồ dùng như bàn ghế đến các hộ gia đình chuột.\n\nCho phép Xưởng Mộc đóng bàn ghế làm hàng xa xỉ.",
  "unlock.wheat.title": "Canh Tác Lúa Mì",
  "unlock.wheat.desc": "Cho phép thợ nông gieo trồng lúa mì trên ruộng.\n\nLúa mì cho sản lượng dồi dào nhưng cần xay xát trước khi ăn và nhạy cảm với độ phì nhiêu của đất hơn cây bản địa.",
  "unlock.potashProcessing.title": "Phân Bón Kali",
  "unlock.potashProcessing.desc": "Khả năng tinh chế khoáng kali thành phân bón hữu dụng tại Tháp Sàng Khoáng Sản.",
  "unlock.mushroom.title": "Canh Tác Nấm Ăn",
  "unlock.mushroom.desc": "Cho phép thợ nông nuôi trồng nấm trên ruộng.\n\nNấm phát triển tốt ở những nơi ẩm tối dưới lòng đất.",
  "unlock.advancedCooking.title": "Nghệ Thuật Ẩm Thực",
  "unlock.advancedCooking.desc": "Kỹ năng nấu ăn chuyên nghiệp giúp chế biến món ăn chất lượng cao tại Nhà Hun Khói, Bếp Nấu Súp và Lò Bánh Mì. Một bước tiến lớn so với nấu nướng nghiệp dư.",
  "unlock.spice.title": "Gieo Trồng Gia Vị",
  "unlock.spice.desc": "Cho phép gieo trồng ớt cay trên đồng ruộng.\n\nLoài cây ngoại lai này không thể lớn nếu thiếu phân bón, nhưng đem lại những trải nghiệm ẩm thực thượng hạng nhất.",
  "unlock.tea.title": "Canh Tác Cây Trà",
  "unlock.tea.desc": "Cho phép nông dân trồng trà trên đồng ruộng.\n\nNguồn trà tự cung tự cấp giúp làng tự chủ, nhưng đòi hỏi bón phân đầy đủ để phát triển.",
  "unlock.valves.title": "Điều Tiết Dẫn Dòng",
  "unlock.valves.desc": "Các loại van giúp điều khiển mạng lưới dẫn chất lỏng chuyên sâu hơn.\n\nCó thể điều khiển thủ công hoặc cài đặt ngưỡng kích hoạt tự động.",
  "unlock.railTech.title": "Đường Sắt Chở Khách",
  "unlock.railTech.desc": "Hệ thống vận tải tốc độ cao đưa chuột đi xa nhanh chóng.\n\nChuột lên hoặc xuống toa tại các sân ga đón trả khách.",
  "unlock.recipe.ironsmelting.title": "Luyện Sắt Thỏi",
  "unlock.recipe.ironsmelting.desc": "Bản vẽ luyện quặng sắt thành các thỏi sắt kiên cố.",
  "unlock.recipe.goldsmelter.title": "Luyện Vàng Thỏi",
  "unlock.recipe.goldsmelter.desc": "Công thức luyện kim cho phép nấu quặng vàng thành các thỏi vàng quý giá tại Lò Nấu Quặng.",
  "unlock.bedding.desc": "Bản vẽ may chăn đệm tại Tiệm May Mặc.\n\nChăn đệm được Tiệm Cung Ứng Hàng Xa Xỉ phân phát đến từng nhà chuột.",
  "unlock.bedding.title": "Chăn Đệm Ấm Áp",
  "unlock.tablesalt.title": "Muối Ăn Tinh Luyện",
  "unlock.tablesalt.desc": "Khả năng chế biến muối mỏ thành muối ăn tinh khiết tại Tháp Sàng Khoáng Sản.",
  "unlock.recipe.steelsmelting.title": "Luyện Thép Cao Cấp",
  "unlock.recipe.steelsmelting.desc": "Bản vẽ luyện thỏi thép từ thỏi sắt và than đá tại Lò Cao Luyện Kim.",
  "unlock.recipe.bronzesmelter.title": "Luyện Đồng Thanh",
  "unlock.recipe.bronzesmelter.desc": "Bản vẽ đúc thỏi đồng thanh từ đồng đỏ và thiếc tại Lò Nấu Quặng.",
  "unlock.steelcannons.title": "Đại Bác Thép",
  "unlock.steelcannons.desc": "Bản vẽ sản xuất pháo thép tại Xưởng Đúc Đại Bác.",
  "unlock.finetea.title": "Trà Thượng Hạng",
  "unlock.finetea.desc": "Bí quyết phối trộn lá trà tươi hảo hạng với gia vị để tạo ra món trà quý tộc.",
  "unlock.soap.title": "Xà Phòng Tắm",
  "unlock.soap.desc": "Bản vẽ sản xuất xà phòng tại Phòng Hóa Phẩm.\n\nXà phòng được Tiệm Cung Ứng Hàng Xa Xỉ phân phát đến từng nhà chuột.",
  "unlock.stonePathing.title": "Đường Lát Đá",
  "unlock.stonePathing.desc": "Lối đi bằng phẳng giúp di chuyển nhanh hơn.\n\nBản vẽ Đường Lát Đá và Cầu Thang Đá.",
  "unlock.organizedHeating.title": "Mạng Lưới Sưởi Ấm",
  "unlock.organizedHeating.desc": "Các nguồn nhiệt công suất lớn và cố định kiên cố.\n\nCần có Trại Chăm Lửa để duy trì tiếp tế nhiên liệu.",
  "unlock.seafaring.title": "Kỹ Nghệ Đóng Tàu",
  "unlock.seafaring.desc": "Đóng tàu vượt biển kiên cố và giong buồm ra khơi khám phá đại dương.\n\nTàu đóng xong phải gán vào Bến Tàu Thợ để tuyển mộ thủy thủ.",
  "unlock.housingTier4.desc": "Nhà ở xa hoa bậc nhất tích hợp lò sưởi trung tâm, nhưng đòi hỏi kết nối với cả đường ống nước sạch lẫn hơi nước nóng.",
  "unlock.housingTier4.title": "Nhà Xa Hoa",
  "unlock.textiles.desc": "Bản vẽ cho Tiệm May Mặc để may áo choàng cao cấp hơn.\n\nCho phép Xưởng Kéo Sợi Lanh se sợi chỉ, và Xưởng Dệt Vải dệt thành vải vóc.",
  "unlock.textiles.title": "Kỹ Nghệ Dệt May",
  "unlock.precisionscales.title": "Bản vẽ chế tạo kẹp gắp lửa tại Xưởng Rèn Đồng.",
  "unlock.precisionscales.desc": "Bản vẽ chế tạo cân chính xác tại Lò Rèn Sắt Thép.",
  "unlock.steelplates.desc": "Bản vẽ cán các tấm thép kiên cố tại Lò Rèn Sắt Thép.",
  "unlock.nails.desc": "Bản vẽ rèn đinh đồng tại Xưởng Rèn Đồng.",
  "unlock.newCrop": "Giống Cây Mới",
  "unlock.luxury": "Hàng xa xỉ để phân phát.",
  "unlock.medicine": "Dùng để chữa trị bệnh tật.",
  "unlock.aimAdvanced": "Băng Chuyền Nâng Cao",
  "unlock.aimAdvanced.desc": "Các cỗ máy bổ trợ để rút hàng, leo tầng, chia luồng và lọc hàng trên băng chuyền.\n\nTài nguyên có thể rút trực tiếp từ kho rồi chia và lọc để cấp thẳng vào xưởng qua các kho đón hàng địa phương.",
  "unlock.plannedFlooding": "Làm Ngập Có Kiểm Soát",
  "unlock.guanocollection.title": "Thu Gom Phân Chim Biển",
  "unlock.guanocollection.desc": "Trang bị tàu thuyền vượt biển đi gom phân chim trên các đảo xa.\nNguồn phân bón vô cùng giàu dinh dưỡng.",
  "unlock.cannonDefenses.title": "Chế Tạo Đại Bác",
  "unlock.cannonDefenses.desc": "Trước hiểm họa hải tặc ngày càng gia tăng, thần dân chuột được truyền dạy bí kíp chế tạo đại bác thuốc súng.",

  # 4. Resources, Foods, Crafting Materials & Commodities (220 items)
  "resource.wood": "Gỗ Khúc",
  "resource.planks": "Ván Gỗ",
  "resource.stone": "Đá Tảng",
  "resource.bricks": "Đá Đẽo Gọt",
  "resource.wheat": "Lúa Mì",
  "resource.flour": "Bột Mì",
  "resource.spice": "Gia Vị",
  "resource.rawfish": "Cá Tươi",
  "resource.mushroom": "Nấm Ăn",
  "resource.berries": "Quả Mọng",
  "resource.bread": "Bánh Mì",
  "resource.smokedfish": "Cá Hun Khói",
  "resource.berrysoup": "Súp Quả Mọng",
  "resource.jampastry": "Bánh Nhân Mứt",
  "resource.stew": "Súp Nấm Hầm",
  "resource.fishskewers": "Cá Xiên Nướng",
  "resource.simplemeal": "Bữa Ăn Đậm Đà",
  "resource.heartymeal": "Bữa Ăn Thịnh Soạn",
  "resource.platter": "Bữa Ăn Sang Trọng",
  "resource.cannedfood": "Đồ Hộp",
  "resource.basicRations": "Bánh Lương Khô",
  "resource.tea": "Trà Đen",
  "resource.finetea": "Trà Thượng Hạng",
  "resource.tealeaves": "Búp Trà Tươi",
  "resource.flax": "Cây Lanh",
  "resource.cotton": "Xơ Bông",
  "resource.rope": "Dây Thừng",
  "resource.fabric": "Vải Vóc",
  "resource.fishingnet": "Lưới Đánh Cá",
  "resource.sail": "Cánh Buồm",
  "resource.clothes": "Áo Choàng May Đo",
  "resource.bedding": "Chăn Đệm",
  "resource.copperore": "Quặng Đồng",
  "resource.tinore": "Quặng Thiếc",
  "resource.ironore": "Quặng Sắt",
  "resource.goldore": "Quặng Vàng",
  "resource.coal": "Than Đá",
  "resource.rocksalt": "Muối Mỏ",
  "resource.potash": "Khoáng Kali",
  "resource.cobaltore": "Quặng Coban",
  "resource.copperbar": "Thỏi Đồng Đỏ",
  "resource.bronze": "Thỏi Đồng Thanh",
  "resource.ironbar": "Thỏi Sắt",
  "resource.steel": "Thỏi Thép",
  "resource.goldbar": "Vàng Thỏi",
  "resource.ruby": "Hồng Ngọc",
  "resource.sapphire": "Lam Ngọc",
  "resource.emerald": "Ngọc Lục Bảo",
  "resource.amethyst": "Thạch Anh Tím",
  "resource.amber": "Hổ Phách",
  "resource.obsidian": "Hắc Diệu Thạch",
  "resource.fuel": "Nhiên Liệu",
  "resource.fertilizer": "Phân Bón",
  "resource.tablesalt": "Muối Ăn",
  "resource.salinesolution": "Dung Dịch Nước Muối",
  "resource.oil": "Dầu Bôi Trơn",
  "resource.medicine": "Dược Phẩm",
  "resource.soap": "Xà Phòng",
  "resource.candles": "Nến Thắp Sáng",
  "resource.nails": "Đinh Đồng",
  "resource.teaset": "Bộ Ấm Chén",
  "resource.furniture": "Bàn Ghế Gỗ",
  "resource.cannonframes": "Khung Bệ Pháo",
  "resource.bronzecannons": "Đại Bác Đồng Thanh",
  "resource.handTool": "Công Cụ Kim Loại",
  "resource.steelplates": "Tấm Thép Cán",
  "resource.steelcannons": "Đại Bác Thép",
  "resource.tools": "Máy Móc Cơ Khí",
  "resource.trinkets": "Đồ Mỹ Nghệ",
  "resource.influence": "Lòng Dân",
  "resource.goldCoin": "Đồng Tiền Vàng",
  "resource.research": "Điểm Tri Thức",
  "resource.xp": "Kinh Nghiệm Hợp Đồng",
  "resource.smallship": "Thuyền Buồm Cỡ Nhỏ",
  "resource.frigate": "Tàu Hộ Vệ Frigate",
  "resource.fluid_water": "Nước Ống Dẫn",
  "resource.fluid_steam": "Hơi Nước Ống Dẫn",
  "resource.agent": "Dân Chuột",
  "resource.mineTool.unknown": "Chưa Rõ",
  "resource.mineTool.bedrock": "Đá Nền",
  "resource.mineTool.ocean": "Đáy Biển",
  "resource.farmTool.nutrients": "Dinh Dưỡng",
  "resource.farmTool.rocks": "Độ Lẫn Đá",
  "resource.farmTool.light": "Ánh Nắng",
  "resource.farmTool.pollution": "Ô Nhiễm",
  "resource.noitem": "Không Có",
  "resource.waste": "Phế Thải",
  "resource.peppers": "Ớt Cay",
  "resource.trees": "Cây Rừng",
  "resource.desc.wood": "Gỗ khúc thô sơ chưa qua sơ chế.",
  "resource.farmTool.soilProps": "Môi Trường",
  "resource.farmTool.cropFertilty": "Độ Phì Nhiêu Cây Trồng",
  "resource.farmTool.clear": "Tắt Lớp Phủ",
  "resource.mousetrap": "Bẫy Sâu Bọ",
  "resource.allores": "Mọi Loại Quặng",
  "resource.desc.planks": "Ván gỗ đã qua xẻ gọt nhẵn bóng.",
  "resource.desc.stone": "Đá tảng thô chưa đẽo gọt.",
  "resource.desc.bricks": "Khối đá được đẽo gọt chuẩn xác cho việc xây dựng.",
  "resource.desc.wheat": "Cây lương thực cho sản lượng cao nhưng cần xay xát.",
  "resource.desc.flour": "Nguồn calo dồi dào và hiệu quả khi được nấu chín.",
  "resource.desc.peppers": "Vị cay nồng thơm ngon.",
  "resource.desc.spice": "Gia vị xay nhuyễn dùng cho các bữa ăn thượng hạng.",
  "resource.desc.rawfish": "Cá tươi mới đánh bắt từ biển.",
  "resource.desc.mushroom": "Một loài nấm ăn được.",
  "resource.desc.berries": "Đơn sơ nhưng giàu dinh dưỡng.",
  "resource.desc.bread": "Ổ bánh mì mới ra lò thơm phức.",
  "resource.desc.smokedfish": "Ướp muối và hun khói thơm ngon.",
  "resource.desc.berrysoup": "Món súp ngọt thanh tao.",
  "resource.desc.jampastry": "Bánh mì cao cấp kẹp nhân mứt.",
  "resource.desc.stew": "Món hầm nấu chín nóng hổi, ấm bụng.",
  "resource.desc.fishskewers": "Cá xiên nướng được chế biến khéo léo.",
  "resource.desc.simplemeal": "Một bữa ăn đậm đà hương vị.",
  "resource.desc.heartymeal": "Một bữa ăn thịnh soạn no nê.",
  "resource.desc.platter": "Một bữa ăn tươi ngon sảng khoái.",
  "resource.desc.cannedfood": "Lương khô đóng hộp phục vụ những chuyến hải trình dài ngày.",
  "resource.desc.basicRations": "Lương khô mặn chát, ăn chắc bụng để làm lụng.",
  "resource.desc.tea": "Trà đen mộc mạc thưởng thức vào buổi tối.",
  "resource.desc.finetea": "Trà thượng hạng được giới quý tộc ưa chuộng.",
  "resource.desc.tealeaves": "Búp trà tươi đang chờ được sao chế.",
  "resource.desc.flax": "Cây giàu chất xơ dùng để xe sợi dệt vải lanh.",
  "resource.desc.cotton": "Cây lấy xơ dùng để dệt vải bông mềm mại.",
  "resource.desc.rope": "Dây thừng bện chắc nịch dùng trong công nghiệp.",
  "resource.desc.fabric": "Tấm vải dệt có độ bền cao.",
  "resource.desc.fishingnet": "Các loại lưới bện để giăng bắt cá biển.",
  "resource.desc.sail": "Vật liệu thiết yếu để đóng tàu vượt biển.",
  "resource.desc.clothes": "Trang phục ấm áp giúp tăng khả năng chống rét.",
  "resource.desc.bedding": "Chăn nệm chần bông cho giấc ngủ say nồng.",
  "resource.desc.copperore": "Quặng đồng thô chưa qua chế biến.",
  "resource.desc.tinore": "Quặng thiếc thô chưa qua chế biến.",
  "resource.desc.ironore": "Quặng sắt thô chưa qua chế biến.",
  "resource.desc.goldore": "Quặng vàng thô chưa qua chế biến.",
  "resource.desc.coal": "Than đá. Có thể tinh chế thành nhiên liệu tại Tháp Sàng Khoáng Sản.",
  "resource.desc.rocksalt": "Khoáng muối mặn mòi chưa qua tinh chế.",
  "resource.desc.potash": "Khoáng sản có thể chế biến thành phân bón kali.",
  "resource.desc.cobaltore": "Quặng coban thô chưa qua chế biến.",
  "resource.desc.copperbar": "Thỏi đồng đỏ đã qua nấu chảy đúc khuôn.",
  "resource.desc.bronze": "Hợp kim cao cấp pha trộn giữa thiếc và đồng đỏ.",
  "resource.desc.ironbar": "Thỏi sắt đã qua luyện kim đúc khuôn.",
  "resource.desc.steel": "Kim loại cứng cáp và bền vững nhất.",
  "resource.desc.goldbar": "Vàng ròng được đúc thành những thỏi quý giá.",
  "resource.desc.fuel": "Thiết yếu cho sưởi ấm, nấu ăn và công nghiệp.",
  "resource.desc.fertilizer": "Phục hồi hoặc tăng cường độ phì nhiêu cho đồng ruộng.",
  "resource.desc.tablesalt": "Tăng thêm vị đậm đà cho món ăn.",
  "resource.desc.salinesolution": "Bù đắp lượng dịch cơ thể mất đi do chấn thương hoặc ốm đau.",
  "resource.desc.oil": "Chất bôi trơn và phụ gia giá trị cao.",
  "resource.desc.medicine": "Chữa trị viêm nhiễm và đẩy lùi các triệu chứng bệnh tật.",
  "resource.desc.soap": "Bánh xà phòng sạch sẽ thơm tho.",
  "resource.desc.candles": "Nến sáp thắp sáng trong nhà.",
  "resource.desc.nails": "Đinh tán chống gỉ sét kiên cố.",
  "resource.desc.teaset": "Bộ dụng cụ chuẩn mực để thưởng trà.",
  "resource.desc.furniture": "Đồ gỗ cao cấp mang lại cuộc sống tiện nghi.",
  "resource.desc.cannonframes": "Khung bệ vững chắc để gắn nòng đại bác lên.",
  "resource.desc.bronzecannons": "Hỏa lực đồng thanh cơ bản nhưng dùng được.",
  "resource.desc.handTool": "Dụng cụ chuyên dụng giúp nâng cao hiệu suất làm việc.",
  "resource.desc.steelplates": "Những tấm kim loại cán dày dặn và kiên cố.",
  "resource.desc.steelcannons": "Chuẩn mực hỏa lực của chiến tranh hiện đại.",
  "resource.desc.tools": "Máy móc phụ tùng quý giá giúp duy trì công xưởng vận hành trơn tru.",
  "resource.desc.trinkets": "Những món đồ mỹ nghệ vụn vặt nhưng lại khiến Quý Tộc Móng Vuốt rất vừa lòng.",
  "resource.desc.influence": "Lòng Dân nhận được mỗi đêm từ bà con chuột.\n\nDùng cho các chính sách xã hội và hành động cộng đồng.",
  "resource.desc.goldCoin": "Tiền tệ thông dụng trong giao thương.",
  "resource.desc.research": "Tri thức khoa học kỹ thuật.",
  "resource.desc.smallship": "Tàu thủy cỡ nhỏ phục vụ các mục đích dân sự.",
  "resource.desc.frigate": "Chiến hạm cỡ trung có năng lực tác chiến hải quân.",
  "resource.desc.fluid_water": "Nước dẫn qua đường ống phục vụ nhiều mục đích công nghiệp.",
  "resource.desc.fluid_steam": "Hơi nước áp suất cao tạo ra từ nồi hơi. Môi chất hiệu quả để truyền nhiệt và cơ năng.",
  "resource.desc.agent": "Chú chuột",
  "resource.desc.mineTool.unknown": "Thăm dò khu vực này để biết thêm thông tin.",
  "resource.desc.mineTool.bedrock": "Khối đá nền này không thể đào bới.",
  "resource.desc.mineTool.ocean": "Tầng đáy biển này không thể khai thác mỏ.",
  "resource.desc.farmTool.nutrients": "Hàm lượng dinh dưỡng có trong đất.",
  "resource.desc.farmTool.rocks": "Mức độ lẫn sỏi đá trong tầng đất.",
  "resource.desc.farmTool.light": "Lượng ánh sáng mặt trời chiếu tới vị trí này.",
  "resource.desc.farmTool.pollution": "Mức độ ô nhiễm môi trường tác động lên đất đai.",
  "resource.desc.farmtool.noitem": "Chưa chọn gì.",
  "resource.desc.waste": "Phế phẩm công nghiệp cần được đem đi thiêu hủy.",
  "resource.desc.trees": "Nguồn cung cấp gỗ tự nhiên có thể tái sinh.",
  "resource.desc.mousetrap": "Bẫy tiêu diệt sâu bọ phá hoại mùa màng.",
  "resource.diplomacySeals": "Ấn Triện Sáp Hoàng Gia",
  "resource.desc.diplomacySeals": "Minh chứng thiện chí từ Quý Tộc Móng Vuốt.\n\nCó thể dùng để đệ trình các thỉnh cầu đặc biệt.",
  "resource.pollution": "Ô Nhiễm",
  "resource.desc.pollution": "Chất ô nhiễm độc hại bay lơ lửng trong không khí.",
  "resource.fallow": "Cho Đất Nghỉ",
  "resource.desc.fallow": "Không gieo trồng gì để đất phục hồi dưỡng chất.",
  "resource.desc.thread": "Những sợi chỉ dài mảnh.",
  "resource.thread": "Sợi Chỉ",
  "resource.simpleclothes": "Áo Choàng Thô",
  "resource.desc.simpleclothes": "Thô cứng và hơi cộm ráp, nhưng giữ ấm tốt và mang lại chút tươm tất cho người mặc.",
  "resource.advancedRations": "Khẩu Phần Ăn Đầy Đủ",
  "resource.desc.advancedRations": "Một bữa ăn trọn vẹn đầy đủ dinh dưỡng.",
  "resource.vises": "Ê-tô Gỗ",
  "resource.scissors": "Kéo Cắt Vải",
  "resource.firetongs": "Kẹp Gắp Lửa",
  "resource.ironpots": "Nồi Gang",
  "resource.precisionscales": "Cân Chính Xác",
  "resource.desc.vises": "Dụng cụ để kẹp chặt đồ vật cố định khi gia công.",
  "resource.desc.scissors": "Dụng cụ sắc bén rất hiệu quả để cắt may vải vóc.",
  "resource.desc.firetongs": "Dụng cụ để thao tác gắp than củi trong ngọn lửa.",
  "resource.desc.ironpots": "Nồi nấu cỡ lớn, dày dặn và bền bỉ.",
  "resource.desc.precisionscales": "Dụng cụ đo lường đáng tin cậy để cân đong chuẩn xác.",
  "resource.desc.firstrate": "Kỳ hạm đại dương hùng mạnh được chế tạo chuyên dụng cho các trận hải chiến nảy lửa.",
  "resource.firstrate": "Kỳ Hạm Hạng Nhất",
  "resource.ironpots2": "Nồi Đồng",
  "resource.nails2": "Đinh Sắt",
  "resource.farmTool.salinity": "Độ Mặn Của Đất",
  "resource.bathed": "Tắm Nước Nóng",
  "resource.desc.bathed": "Bé chuột sạch sẽ tinh tươm sau khi tắm gội.",
  "resource.corpse": "Thi Thể Chuột",
  "resource.desc.corpse": "Một thi thể không rõ danh tính cần được an táng tươm tất.",
  "resource.guano": "Phân Chim Biển",
  "resource.guano.desc": "Phế thải giàu dinh dưỡng tích tụ trên các mỏm đá có chim biển cư ngụ.\nCó thể tinh chế thành phân bón hảo hạng.",
  "resource.stone_cannonball": "Đạn Pháo Đá",
  "resource.desc.stone_cannonball": "Đạn pháo rẻ tiền nhưng uy lực yếu. Gây 3 sát thương.",
  "resource.iron_cannonball": "Đạn Pháo Sắt",
  "resource.desc.iron_cannonball": "Loại đạn pháo hiệu quả tiêu chuẩn. Gây 8 sát thương.",
  "resource.bronze_cannonball": "Đạn Pháo Đồng",
  "resource.desc.bronze_cannonball": "Đạn đại bác bằng đồng cơ bản. Gây 5 sát thương.",
  "resource.chainshot_cannonball": "Đạn Xích Đôi",
  "resource.desc.chainshot_cannonball": "Đạn sắt gồm hai nửa nối với nhau bằng dây xích, gây sát thương diện rộng tối đa lên buồm tàu. Gây 13 sát thương.",
  "resource.pirate_protection": "Ấn Ước Bảo Hộ Hải Tặc",
  "resource.desc.pirate_protection": "Hiệp ước đình chiến ngăn chặn các cuộc cướp phá của hải tặc trong một ngày."
}

def apply():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        entries = json.load(f)

    applied = 0
    missing = []

    for entry in entries:
        key = entry["key"]
        if key in T:
            entry["target_vi"] = T[key]
            applied += 1
        else:
            missing.append((key, entry["source_en"]))

    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(entries, f, ensure_ascii=False, indent=2)

    print(f"Applied translation to {applied} / {len(entries)} items in Phase 3!")
    if missing:
        print(f"Missing {len(missing)} keys:")
        for k, s in missing[:10]:
            print(f"  - {k}: {s}")
    else:
        print("All 350 Phase 3 items translated 100%!")

if __name__ == "__main__":
    apply()
