import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(PROJECT_ROOT, "translations", "01_Core_UI_Menus.json")

# Dictionary of high-quality, gamer-friendly Vietnamese translations for Phase 1 (391 items)
T = {
  # Toolbar categories
  "toolbar.paths": "Đường Đi",
  "toolbar.utilities": "Sưởi Ấm & Tiện Ích",
  "toolbar.housing": "Nhà Ở",
  "toolbar.services": "Dịch Vụ",
  "toolbar.research": "Nghiên Cứu",
  "toolbar.bulldoze": "Phá Dỡ",
  "toolbar.aim": "Băng Tải",
  "toolbar.minetool": "Khai Mỏ",
  "toolbar.logistics": "Kho Bãi & Băng Tải",
  "toolbar.industry": "Khai Khoáng & Chế Biến",
  "toolbar.harvesttool": "Ưu Tiên Hái Lượm",
  "toolbar.farmTool": "Trồng Trọt",
  "toolbar.menu": "Menu",
  "toolbar.foodProcessing": "Chế Biến Thức Ăn",
  "toolbar.navigation": "Đường Đi Bộ",
  "toolbar.resourceExtractors": "Khai Thác Tài Nguyên",
  "toolbar.production": "Nhà Xưởng",
  "toolbar.domestic": "Nhà Ở & Dịch Vụ",
  "toolbar.markingTools": "Đánh Dấu Tài Nguyên",
  "toolbar.glossary": "Bách Khoa",
  "toolbar.pathdecoratives": "Trang Trí Đường Xá",
  "toolbar.priorityTool": "Ưu Tiên Đốn Gỗ",
  "toolbar.priorityTool.harvest": "Ưu Tiên Hái Lượm",
  "toolbar.civic": "Hành Chính",
  "toolbar.decor": "Trang Trí",
  "toolbar.water": "Công Trình Nước",
  "toolbar.steam": "Công Trình Hơi Nước",
  "toolbar.construction": "Xây Dựng",
  "toolbar.whiskerview": "Văn Phòng Làng Chuột",
  "toolbar.clawsview": "Sổ Cống Nạp",
  "toolbar.policies": "Bảng Chính Sách",
  "toolbar.researchBuildings": "Nghiên Cứu",
  "toolbar.storedResources": "Tổng Tài Nguyên",
  "toolbar.trains": "Đường Ray",
  "toolbar.nautical": "Hàng Hải & Tàu Thuyền",
  "toolbar.questlog": "Nhật Ký Nhiệm Vụ",
  "toolbar.masonry": "Công Trình Đá",
  "toolbar.terraformTool": "Công Cụ San Nền",
  "toolbar.workoverview": "Tổng Quan Công Việc",

  # Pause Menu
  "pause.resume": "Tiếp Tục",
  "pause.save": "Lưu Game",
  "pause.load": "Tải Game",
  "pause.saveAs": "Lưu Thành Bản Mới",
  "pause.quitmainmenu": "Menu Chính",
  "pause.quitdesktop": "Thoát Game",
  "pause.editmapeditor": "Mở Trình Tạo Bản Đồ",
  "pause.music": "Âm Nhạc",

  # Settings
  "settings.title": "Cài Đặt",
  "settings.resetdefault": "Đặt Lại Mặc Định",
  "settings.resetdefaultkeybind": "Đặt Lại Phím Tắt",
  "settings.graphics": "Đồ Họa",
  "settings.gameplay": "Lối Chơi",
  "settings.audio": "Âm Thanh",
  "settings.language": "Ngôn Ngữ",
  "settings.keybinds": "Phím Điều Khiển",
  "settings.mods": "Bản Mod",
  "settings.a.master": "Âm Lượng Tổng",
  "settings.a.ambient": "Môi Trường",
  "settings.a.music": "Nhạc Nền",
  "settings.a.sfx": "Hiệu Ứng",
  "settings.a.ui": "Âm Giao Diện",
  "settings.a.voice": "Giọng Nói",
  "settings.g.vsync": "Đồng Bộ Dọc (VSync)",
  "settings.g.resolution": "Độ Phân Giải",
  "settings.g.dynres": "Độ Phân Giải Động",
  "settings.g.vfxq": "Chất Lượng Hiệu Ứng & Thời Tiết",
  "settings.g.textureq": "Chất Lượng Vân Bề Mặt",
  "settings.g.shadowq": "Chất Lượng Đổ Bóng",
  "settings.g.ppq": "Chất Lượng Hậu Kỳ",
  "settings.g.effectsq": "Chất Lượng Hiệu Ứng",
  "settings.g.fullscreen": "Chế Độ Màn Hình",
  "settings.g.terrainres": "Chi Tiết Địa Hình",
  "settings.fullscreen": "Toàn Màn Hình",
  "settings.windowedfullscreen": "Toàn Màn Hình Không Viền",
  "settings.windowed": "Cửa Sổ",
  "settings.confirmupgrade": "Hỏi Khi Nâng Cấp Nhà Xưởng",
  "settings.confirmsell": "Hỏi Khi Tháo Dỡ Toa Tàu",
  "settings.controller": "Gợi Ý Nút Tay Cầm",
  "settings.g.fpsmax": "Giới Hạn FPS",
  "settings.g.unlimited": "Không Giới Hạn",
  "settings.g.showfps": "Hiện FPS",
  "settings.dpiscale": "Tỉ Lệ Giao Diện",
  "settings.g.sharpness": "Độ Sắc Nét",
  "settings.g.aa": "Khử Răng Cưa",
  "settings.g.mode.dlss": "Chế Độ DLSS",
  "settings.g.mode.fsr": "Chế Độ FSR",
  "settings.g.mode.xess": "Chế Độ XeSS",
  "settings.g.discreteRotation": "Xoay Camera Từng Nấc",
  "settings.g.holdToBulldoze": "Nhấn Giữ Để Phá Dỡ",
  "settings.g.autosave": "Tần Suất Tự Động Lưu",
  "settings.terraindrawdistance": "Tầm Hiển Thị Địa Hình",
  "settings.terraingrassdensity": "Mật Độ Cỏ",
  "settings.temperature": "Thang Đo Nhiệt Độ",
  "settings.celsius": "Độ C (°C)",
  "settings.fahrenheit": "Độ F (°F)",
  "settings.enableDockCamera": "Bật Camera Bến Cảng",
  "settings.toggleEdgeScrolling": "Cuộn Chuột Viền Màn Hình",
  "settings.toggleMouseLocking": "Khóa Chuột Trong Cửa Sổ",
  "settings.mousecameracontrols": "Thao Tác Camera Bằng Chuột",
  "settings.mbbpan": "Chuột Giữa: Trượt / Chuột Phải: Xoay",
  "settings.mbborbit": "Chuột Giữa: Xoay / Chuột Phải: Trượt",
  "settings.action.resetSettings": "Đặt Lại Mặc Định",
  "settings.action.resetKeybinds": "Đặt Lại Phím Tắt",
  "settings.action.resetToDefault": "Khôi Phục Đồ Họa Mặc Định",
  "settings.action.applyGraphics": "Áp Dụng Đồ Họa Mới",
  "settings.header.camera": "Camera",
  "settings.header.basic": "Cơ Bản",
  "settings.header.other": "Khác",
  "settings.showblips": "Biểu Tượng Thông Báo",
  "settings.showblips.desc": "Tùy chỉnh biểu tượng trạng thái, sự cố hoặc sự kiện hiển thị trên đầu công trình và các chú chuột.",
  "settings.showblips.all": "Tất Cả",
  "settings.showblips.statusonly": "Chỉ Sự Cố & Trạng Thái",
  "settings.terraindrawdistance.desc": "Mức chi tiết địa hình theo khoảng cách thu phóng.\nChi tiết càng cao càng ngốn phần cứng.\nẢnh hưởng lớn đến hiệu năng.",
  "settings.terraingrassdensity.desc": "Khoảng cách ngừng kết xuất cỏ và chi tiết phụ.\nẢnh hưởng lớn đến hiệu năng.",

  # Anti-Aliasing options
  "aa.noaa": "Tắt Khử Răng Cưa",
  "aa.quality.auto": "Tự Động",
  "aa.quality.ultraperformance": "Siêu Hiệu Năng",
  "aa.quality.performance": "Hiệu Năng",
  "aa.quality.balanced": "Cân Bằng",
  "aa.quality.quality": "Chất Lượng",
  "aa.quality.ultraquality": "Siêu Chất Lượng",
  "aa.quality.ultraqualityplus": "Chất Lượng Tối Đa",
  "aa.quality.antialiasing": "Khử Răng Cưa",
  "aa.quality.nativeaa": "Khử Răng Cưa Gốc",

  # Main Menu & General Menu
  "menu.settings": "Cài Đặt",
  "menu.newcolony": "Trò Chơi Mới",
  "menu.loadcolony": "Tải Game",
  "menu.leveleditor": "Trình Tạo Bản Đồ",
  "menu.credits": "Đội Ngũ Phát Triển",
  "menu.quit": "Thoát",
  "menu.back": "Quay Lại",
  "menu.map": "Bản Đồ",
  "menu.delete": "Xóa",
  "menu.load": "Tải",
  "menu.loadfiles": "Danh Sách Bản Lưu",
  "menu.nosaves": "Chưa có bản lưu nào",
  "menu.compilingshaders": "Đang Tải Trước Shader",
  "menu.discord": "Discord",
  "menu.support": "Hỗ Trợ",
  "menu.autosave": "Tự Động Lưu",
  "menu.population": "Dân Số",
  "menu.playtime": "Thời Gian Chơi",
  "menu.date": "Ngày",
  "menu.confirmDelete": "Bạn có chắc chắn muốn xóa bản lưu này?",
  "menu.resourcesRequired": "Tài Nguyên Cần Thiết",
  "menu.inbound": "Đang Vận Chuyển Đến",
  "menu.nomaterials": "Không tìm thấy nguyên vật liệu cần thiết.",
  "menu.highprinight": "Ưu Tiên Cao + Làm Đêm",
  "menu.sethightpri": "Đặt Ưu Tiên Cao",
  "menu.markrebuild": "Đánh Dấu Xây Lại",
  "menu.choose": "Lựa Chọn",
  "menu.taxpayment": "Thuế Cống Nạp",
  "menu.letstalk": "Bàn về thành quả thuộc địa gần đây nào...",
  "menu.giftsupplies": "Tiếp Tế Ban Ơn",
  "menu.gain": "Nhận Được",
  "menu.saving": "Đang lưu...",
  "menu.quitwarning": "Tiến trình chơi sẽ được lưu lại vào ổ đĩa.",
  "menu.quitdesktopheader": "Thoát Ra Desktop",
  "menu.quitmainmenuheader": "Quay Lại Menu Chính",
  "menu.wiki": "Cẩm Nang Wiki",
  "menu.rebellionsentiment": "Khí Thế Khởi Nghĩa",
  "menu.rebellionsentiment.desc": "Khí thế khởi nghĩa trong làng dấy lên những lời bàn tán về tương lai thoát khỏi ách Móng Vuốt.\n\nNghe điều này, đa số thợ thuyền sẽ hăng hái làm việc hơn. Những kẻ trung thành với Hoàng gia sẽ phàn nàn về sự phản nghịch.",

  # Keybindings
  "settings.defaultBinding": "Phím Mặc Định",
  "settings.pressKeyToRebind": "Nhấn phím bất kỳ để gán",
  "settings.invalidKey": "Phím Không Hỗ Trợ",
  "settings.keybind.LeftClick": "Chọn",
  "settings.keybind.RightClick": "Quay Lại / Hủy",
  "settings.keybind.pausemenu": "Menu Tạm Dừng",
  "settings.keybind.Up": "Nâng Độ Cao",
  "settings.keybind.Down": "Hạ Độ Cao",
  "settings.keybind.tabLeft": "Chuyển Tab Trái",
  "settings.keybind.tabRight": "Chuyển Tab Phải",
  "settings.keybind.pause": "Tạm Dừng / Chạy Tiếp",
  "settings.keybind.speed_1x": "Tốc Độ 1x",
  "settings.keybind.speed_2x": "Tốc Độ 2x",
  "settings.keybind.speed_4x": "Tốc Độ 3x",
  "settings.keybind.PanUp_Keyboard.0": "Lùi Lại",
  "settings.keybind.PanUp_Keyboard.1": "Tiến Lên",
  "settings.keybind.PanRight_Keyboard.0": "Sang Trái",
  "settings.keybind.PanRight_Keyboard.1": "Sang Phải",
  "settings.keybind.Pan": "Trượt Nhanh",
  "settings.keybind.slice": "Bật/Tắt Cắt Tầng",
  "settings.keybind.toggleHeatOverlay": "Xem Bản Đồ Nhiệt",
  "settings.keybind.rotateCursor": "Xoay Con Trỏ",
  "settings.keybind.clone": "Sao Chép Công Trình",
  "settings.keybind.OpenEventQueue": "Xem Bảng Tin Sự Kiện",
  "settings.keybind.moveBuilding": "Dời Công Trình",
  "settings.keybind.resetZ": "Khóa / Mở Độ Cao Con Trỏ",
  "settings.keybind.fastHeightChange": "Cuộn Nhanh Độ Cao",
  "settings.keybind.rotCW": "Xoay Camera Thuận KĐH",
  "settings.keybind.rotCCW": "Xoay Camera Ngược KĐH",
  "settings.keybind.rotCamera": "Xoay Camera",
  "settings.keybind.minetool": "Khai Mỏ",
  "settings.keybind.farmtool": "Trồng Trọt",
  "settings.keybind.togglePollutionOverlay": "Xem Bản Đồ Ô Nhiễm",
  "settings.keybind.quicksave": "Lưu Nhanh",
  "settings.keybind.BulldozeTool": "Phá Dỡ",
  "settings.keybind.cycleVariant": "Biến Thể Tiếp Theo",
  "settings.keybind.zoomIn": "Phóng To",
  "settings.keybind.zoomOut": "Thu Nhỏ",
  "settings.keybind.fishView": "Xem Bãi Cá",
  "settings.keybind.terraformTool": "San Nền",
  "settings.keybind.copySettings": "Sao Chép Cài Đặt",
  "settings.keybind.pasteSettings": "Dán Cài Đặt",

  # Actions
  "action.pauseconstruction": "Tạm Dừng Thi Công",
  "action.resumeConstruction": "Tiếp Tục Thi Công",
  "action.setHighPriority": "Đặt Ưu Tiên Cao",
  "action.setLowPriority": "Đặt Ưu Tiên Thấp",
  "action.assignJumpPadDestination": "Chọn Điểm Bắn Đến",
  "action.closeValve": "Đóng Van",
  "action.openValve": "Mở Van",
  "action.moveCamp": "Di Dời",
  "action.upgrade": "Nâng Cấp",
  "action.changeRecipe": "Đổi Công Thức",
  "action.assignInputSources": "Chọn Nguồn Cấp",
  "action.assignOutputDestinations": "Chọn Nơi Nhận",
  "action.enact": "Ban Hành",
  "action.abolish": "Bãi Bỏ",
  "action.unlock": "Mở Khóa",
  "action.requestWhiskers": "Xin Thêm Dân Chuột",
  "action.assignFreeShip": "Điều Tàu Mới",
  "action.gotoship": "Đến Vị Trí Tàu",
  "action.delivernow": "Giao Hàng Ngay",
  "action.deliverPending": "Đang Chờ Giao",
  "action.deliverNow.desc": "Ưu tiên chuyển tài nguyên hiện có về kho ngay lập tức",
  "action.startnewday": "Bắt Đầu Ngày Mới",
  "action.acceptDefeat": "Vớt Vát Thiệt Hại & Rời Đi",
  "action.unloadSupplies": "Bốc Dỡ Hàng Tiếp Tế",
  "action.unloadCrew": "Đưa Bà Con Chuột Lên Đảo",
  "action.signCharter": "Ký Hiệp Ước Thuộc Địa",
  "action.manageWhiskers": "Phân Công Dân Chuột",
  "action.turninquest": "Hoàn Thành Nhiệm Vụ",
  "action.EndDay": "Nhấn để kết thúc ngày.",
  "action.pauseWork": "Tạm Dừng Công Việc",
  "action.replaceWorker": "Đổi Thợ Khác",
  "action.doubletime": "Tăng Ca Làm Đêm",
  "action.doubletime.desc": "Tăng tốc độ thợ làm việc đến sáng mai.\n\nBà con chuột sẽ cày cuốc thâu đêm suốt sáng.",
  "action.refuseSupplies": "Từ Chối Tiếp Tế",
  "action.unassignCurrentWhisker": "Bỏ Phân Công Chuột Này",
  "action.requestDifferentWhiskers": "Yêu Cầu Nhóm Chuột Khác",
  "action.assign.home": "Chỉ Định Chỗ Ở",
  "action.assign.home.desc": "Chỉ định một ngôi nhà cụ thể cho chú chuột cư ngụ",
  "action.assign.work": "Chỉ Định Nơi Làm",
  "action.assign.work.desc": "Chỉ định nơi làm việc cho chú chuột",
  "action.pickupWhisker": "Nhấc Chú Chuột Lên",
  "action.pickupWhisker.desc": "Nhấc và chuyển chú chuột đi nơi khác. Hơi chóng mặt đấy nhé!",
  "action.heater.autopause": "Tự Động Tắt Lò",
  "action.heater.autopause.desc": "Tự động tắt lò sưởi khi nhiệt độ xung quanh đã đủ ấm.",
  "action.heater.overdrive": "Đốt Tối Đa Công Suất",
  "action.heater.overdrive.desc": "Tiêu hao gấp đôi nhiên liệu để tăng thêm nhiệt lượng.",
  "action.enable": "Bật",
  "action.disable": "Tắt",
  "action.markForRebuild": "Đánh Dấu Xây Lại",
  "action.quickRebuild": "Xây Lại Nhanh",
  "action.neverShowAgain": "Không hiện lại nữa",
  "action.toggleResource": "Bật/Tắt Tài Nguyên",
  "action.toggleResource.desc": "Thợ chỉ thu thập các loại tài nguyên được tích chọn.",
  "action.fillBlock": "Bồi Đất San Nền",
  "action.pirates.refuseCooperation": "Từ Chối Thỏa Hiệp",
  "action.pirates.sendPartial": "Gửi Một Phần Tiền Chuộc",
  "action.pirates.sendFull": "Gửi Đủ Tiền Chuộc",
  "action.reroll": "Đổi Lại Lựa Chọn",
  "action.sendToSea": "Cho Ra Khơi",
  "action.selectEducation": "Chọn Ngành Đào Tạo",
  "action.selectEducation.desc": "Chọn kỹ năng để học viên theo học. Cần có một thợ giảng dạy đã đạt cấp bậc đó.",
  "action.ship.dismiss": "Cho Tàu Rời Bến",
  "action.ship.tradeConfirm": "Chấp Thuận Giao Thương",
  "action.addWood": "Thêm Củi Đốt",
  "action.disableAllInputs": "Ngừng Nhận Hàng Vào",
  "action.disableAllInputs.desc": "Công trình sau khi xây xong sẽ chặn mọi tài nguyên cho đến khi được cấu hình",
  "action.disableAllInputs_global": "Mặc Định Toàn Cầu: Ngắt Nhận Hàng",
  "action.disableAllInputs_global.desc": "Mọi kho hàng mới xây xong sẽ tự động ngắt nhận hàng vào",
  "action.forbidWarehouseDining": "Cấm Ăn Vụng Trong Kho",
  "action.forbidWarehouseDining.desc": "Nếu bật, bà con chuột sẽ không bao giờ ăn vụng trực tiếp trong kho. Hãy đảm bảo xây đủ nơi ăn uống cho cả làng!",
  "action.recallShip": "Gọi Tàu Quay Về",
  "action.copyToAllTowers": "Đồng Bộ Yêu Cầu Đạn Dược",
  "action.copyToAllTowers.tooltip": "Tất cả các tháp canh sẽ yêu cầu lượng đạn dược giống nhau",
  "action.changeTradePartner": "Chọn Đối Tác Giao Thương",
  "action.clearIncompatibleRequests": "Hủy Yêu Cầu Không Phù Hợp",
  "action.quickRepair": "Sửa Chữa Nhanh",
  "action.scuttleShip": "Đánh Đắm Tàu",
  "action.scuttleShip.desc": "Phá hủy vĩnh viễn con tàu",

  # Notifications & Hover notifications
  "notif.newWhiskers": "Đón Nhận Thêm Dân Chuột Mới",
  "notif.assigned": "Đã Phân Công!",
  "notif.whiskerShipScheduled": "Tàu Nhà Chuột Đã Xuất Bến",
  "notif.piratesDeparting": "Hải tặc đang rời đi",
  "notif.suppliesAccepted": "Đã tiếp nhận hàng tiếp tế",
  "notif.suppliesRejected": "Đã từ chối hàng tiếp tế!",
  "notif.taxesPaid": "Đã nộp đủ thuế; tàu thuế đang rời bến",
  "notif.whiskerRefuses": "Chú chuột này không chịu hợp tác!",
  "notif.toolsReplaced": "Đã Thay Mới Máy Móc",
  "notif.emergencyRepairs": "Sửa Chữa Khẩn Cấp",
  "notif.productionFailed": "Sản Xuất Thất Bại!",
  "notif.refusedOvertime": "Thợ từ chối tăng ca làm đêm",
  "notif.sleepinghere": "Này, chúng tôi đang ngủ ở đây cơ mà!",
  "notif.noAvailableWhiskers": "Hết Dân Chuột Rảnh Rỗi!",
  "notif.newSchematic": "Bản Thiết Kế Mới!",
  "notif.extraProduction": "Sản Lượng Tăng Thêm",
  "notif.noShipSchematics": "Tàu của Stormie đã sửa xong. Bến cảng tạm này giờ có thể tháo dỡ",
  "notif.noShipSchematics.hint": "Bọn hải tặc có thể cung cấp bản thiết kế xưởng đóng tàu thật nếu có chút vàng lót tay",
  "notif.schematicObtained": "Đã Nhận Bản Thiết Kế",
  "notif.stolenShip": "Stormie đã chuồn mất cùng con tàu mới đóng của bạn rồi!",
  "notif.newResearchUnlocked": "Có Bản Thiết Kế Mới Để Nghiên Cứu",
  "notif.newResearchUnlocked.desc": "Với bản thiết kế của hải tặc trong tay, bà con nhà chuột tràn đầy cảm hứng sáng tạo",
  "notif.newResearchUnlocked.descGeneric": "Bà con nhà chuột tràn ngập cảm hứng sáng chế mới",

  "hoverNotif.occupied": "Đã Kín Chỗ",
  "hoverNotif.blockedEdge": "Không Thể Tiếp Cận",
  "hoverNotif.noValidStorage": "Không Có Kho Chứa Hàng",
  "hoverNotif.noValidHarvestable": "Hết Tài Nguyên Trong Tầm",
  "hoverNotif.repairNeeded": "Máy móc cần thay thế!",
  "hoverNotif.noWorkers": "Chưa Phân Công Thợ",
  "hoverNotif.constructionMissingResources": "Thiếu Vật Liệu Xây Dựng",
  "hoverNotif.nofuel": "Hết Nhiên Liệu",
  "hoverNotif.disabled": "Đã Tắt",
  "hoverNotif.noSteam": "Không Có Hơi Nước",
  "hoverNotif.noWater": "Không Có Nước",
  "hoverNotif.constructionPaused": "Tạm Dừng Thi Công",
  "hoverNotif.highPriority": "Ưu Tiên Cao",
  "hoverNotif.cantReachHome": "Không Tìm Thấy Đường Về Nhà",
  "hoverNotif.cantReachWork": "Không Tìm Thấy Đường Đi Làm",
  "hoverNotif.noResourcesEnabled": "Đã tắt nhận mọi tài nguyên",
  "hoverNotif.overtime": "Đang Tăng Ca Đêm",
  "hoverNotif.noConstructionWorkers": "Không Có Thợ Xây Rảnh",
  "hoverNotif.longPath": "Quãng Đường Quá Xa",
  "hoverNotif.noMinesNearby": "Không có mỏ nào được đánh dấu gần đây",
  "hoverNotif.noRecipe": "Chưa Đặt Công Thức",
  "hoverNotif.SafetyOverride": "Đã Vượt Rào An Toàn",
  "hoverNotif.shipBlocking": "Bị Tàu Thuyền Chặn Lối",
  "hoverNotif.noTaskInRange": "Không có việc gì trong tầm",

  # Errors
  "error.blocked": "Vị trí bị chặn.",
  "error.notOverWater": "Cần tiếp giáp mặt nước.",
  "error.needMoreSpace": "Cần khoảng nước thông thoáng hơn quanh bến.",
  "error.notSeaLevel": "Phải xây ở ngang mực nước biển.",
  "error.underwater": "Đang ngập dưới nước!",
  "error.notShore": "Phải đặt ở bờ biển.",
  "error.notgrounded": "Cần nền đất bằng phẳng vững chắc.",
  "error.blockedEntrances": "Lối vào đang bị chặn!",
  "error.notaffordable": "Không đủ tài nguyên.",
  "error.toodeep": "Quá sâu, không đào được!",
  "error.alreadyLivesHere": "Đã sống ở đây rồi!",
  "error.alreadyWorksHere": "Đã làm việc ở đây rồi!",
  "error.railRequired": "Phải đặt trên đường ray.",
  "error.onetrain": "Mỗi đoạn ray chỉ được một toa xe!",
  "error.alreadySentWhiskers": "Đoàn chuột đang trên đường đến",
  "error.mustbeempty": "Phải dọn sạch đồ bên trong.",
  "error.noAvailableWhiskers": "Không còn chú chuột nào rảnh rỗi.",
  "error.blockedterrain": "Vị trí nằm sâu dưới lòng đất.",
  "error.badlandingpos": "Vị trí cập bến không hợp lệ.",
  "error.noMatchingWhiskers": "Không có chú chuột nào phù hợp.",
  "error.invalidLocation": "Vị trí không hợp lệ.",
  "error.savefailed": "Lỗi khi lưu game!",
  "error.tryagain": "Vui lòng thử lại.",
  "error.needsAdmin": "Chỉ định một chú chuột có học thức để mở khóa giới hạn sản xuất",
  "error.cantFindPathForRoute": "Không tìm thấy đường đi hợp lệ giữa hai bến cảng",
  "error.routeAlreadyAssigned": "Tuyến đường này đã có tàu phụ trách",
  "error.notOceanNavigable": "Không thể thông ra biển lớn",
  "error.shipassign.shipneedsRepair": "Cần sửa chữa tàu trước khi phân công lại",
  "error.shipassign.shipneedsUnloading": "Tàu cần dỡ sạch hàng hóa trước",
  "error.cantBulldozeWhileShipAssigned": "Không thể dỡ bến cảng khi vẫn còn tàu neo đậu",
  "error.overlapsdockingspace": "Bị trùng với vùng neo đậu khác",
  "error.insufficientdockingspace": "Không đủ khoảng trống để tàu cập bến",

  # Tooltips
  "tooltip.desc.requestWhiskers": "Yêu cầu chi viện thêm một đợt dân chuột ngoài kế hoạch.",
  "tooltip.title.gifts": "Quà Tặng Từ Đức Vua",
  "tooltip.desc.gifts": "Phe Móng Vuốt sẽ gửi thêm hàng tiếp tế miễn phí khi bạn nộp dư cống thuế.",
  "tooltip.freebuilders": "Thợ Xây Dựng",
  "tooltip.freebuilders.desc": "Các chú chuột không vướng bận việc khác sẽ tham gia thi công công trình.",
  "tooltip.totalPopulation": "Tổng Nhân Khẩu Chuột",
  "tooltip.totalFood": "Tổng Lương Thực Ăn Được",
  "tooltip.locked": "Đang Khóa",
  "tooltip.requiresTechnology": "Cần Bản Thiết Kế",
  "tooltip.requiresOther": "Cần Bản Thiết Kế",
  "tooltip.trust": "Lòng Tin Của Phe Móng Vuốt",
  "tooltip.trust.desc": "Mức độ hài lòng của lũ Mèo đối với cống nạp của bạn.",
  "tooltip.guildspecialty.title": "Chuyên Môn Phường Hội",
  "tooltip.guildspecialty.desc": "Thợ thuộc phường hội này được tăng tốc độ làm việc.",
  "tooltip.needFiretender": "Xây Trại Chăm Lửa để vận chuyển than củi sưởi ấm",
  "tooltip.slice.desc": "Ẩn mọi địa hình và công trình nằm phía trên độ cao con trỏ.",
  "tooltip.moveCamp": "Di dời công trình đến vị trí mới",
  "tooltip.lockhousing": "Khóa Nơi Ở",
  "tooltip.lockhousing.desc": "Ngăn không cho chú chuột tự ý đổi chỗ ở lung tung.",
  "tooltip.maxlimit": "Giới Hạn Tối Đa",
  "tooltip.loseUnsavedChanges": "Mất các thay đổi chưa lưu",
  "tooltip.variants": "Kiểu Biến Thể",
  "tooltip.heat.desc": "Bật/tắt chế độ xem nhiệt độ. Vùng màu xanh dương là nơi lạnh buốt nguy hiểm.",
  "tooltip.pollution.desc": "Bật/tắt xem mức ô nhiễm. Trên 10% bà con chuột sẽ bắt đầu phàn nàn. Ô nhiễm cao hơn sẽ làm giảm hiệu suất làm việc.",
  "tooltip.bulldoze.desc": "Bật/tắt chế độ phá dỡ. Nhấn giữ để dỡ bỏ công trình. Hàng trong kho sẽ mất, vật liệu xây dựng được hoàn lại một phần.",
  "tooltip.fish.desc": "Hiển thị trữ lượng cá ngoài biển quanh đảo.",
  "tooltip.shipStorage": "Khoang Hàng Của Tàu",
  "tooltip.shipStorage.desc": "Hàng hóa hiện đang nằm trong khoang tàu",
  "tooltip.dockStorage": "Hàng Tại Bến Cảng",
  "tooltip.dockStorage.desc": "Hàng hóa tại bến cảng đang chờ chuyển về kho tổng"
}

def apply_translation():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        entries = json.load(f)

    translated_count = 0
    missing_keys = []

    for entry in entries:
        key = entry["key"]
        if key in T:
            entry["target_vi"] = T[key]
            translated_count += 1
        else:
            missing_keys.append((key, entry["source_en"]))

    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(entries, f, ensure_ascii=False, indent=2)

    print(f"Applied translation: {translated_count} / {len(entries)} strings in Phase 1!")
    if missing_keys:
        print(f"Missing {len(missing_keys)} keys:")
        for k, src in missing_keys[:10]:
            print(f"  - {k}: {src}")
    else:
        print("All 391 strings translated 100%!")

if __name__ == "__main__":
    apply_translation()
