import json

# Phase 6B Translations: 336 items (Indices 335 to 670, IDs 1339 to 2166)
PHASE6B_TRANSLATIONS = {
    1339: "Lạnh Lẽo",
    1340: "Cái lạnh khó chịu làm giảm năng suất của chuột thợ.",
    1341: "Ấm Áp",
    1342: "Điều kiện nhiệt độ dễ chịu.",
    1353: "Tàu cập bến sau:",
    1354: "Không còn tàu nào cập bến hôm nay.",
    1355: "THÙ ĐỊCH",
    1356: "Nghi Ngờ",
    1357: "Mất Kiên Nhẫn",
    1358: "Tạm Hài Lòng",
    1359: "Hài Lòng",
    1360: "Tin Tưởng",
    1361: "Quá Đỗi Tin Tưởng",
    1362: "Chính Sách Đang Áp Dụng",
    1363: "Xây thêm văn phòng",
    1364: "Phe Chồn",
    1365: "Sản Xuất & Vận Tải",
    1366: "Bầy Chuột",
    1367: "Phe Móng Vuốt",
    1368: "Thuế Khóa & Răn Đe",
    1384: "Hiệu Ứng Bổ Trợ",
    1385: "Không Có Hiệu Ứng Nào",
    1386: "Không Có Hiệu Ứng Liên Quan",
    1387: "Rất Ấm Áp",
    1388: "Ấm Áp",
    1389: "Lạnh Lẽo",
    1390: "Giá Lạnh",
    1391: "Băng Giá",
    1392: "Nhà Cửa & Đời Sống",
    1394: "Chọn tài nguyên để theo dõi trên giao diện",
    1395: "Thân Nhiệt",
    1396: "Chuột làm việc hiệu quả nhất trong điều kiện ấm áp.",
    1433: "Bận Rộn",
    1440: "Sử Dụng Lòng Dân",
    1441: "Mỗi đêm, bạn nhận được điểm Lòng Dân dựa trên tâm trạng của bầy chuột.",
    1442: "Dùng điểm này để thu nhận thêm chuột, yêu cầu Làm Thêm Giờ, ban hành Chính Sách và còn nhiều điều khác nữa!",
    1443: "Xây dựng Tòa Thị Chính để mở khóa Bảng Chính Sách với nhiều tính năng nâng cao hơn.",
    1446: "Chất Lượng Nhà Ở",
    1447: "Cảnh Quan",
    1448: "Mức Độ Răn Đe",
    1449: "Xa Xỉ Phẩm",
    1450: "Được chuột tiếp ứng xa xỉ phẩm vận chuyển tới",
    1451: "Chưa Có Chuột Thợ",
    1452: "Chỉ Định Chuột Thợ",
    1453: "Điều Chuyển Chuột Thợ",
    1462: "Chuột Thợ Vận Tải",
    1463: "Chuột thợ sẽ giữ kho hàng này luôn đầy dựa theo hạn mức đã thiết lập.",
    1464: "Đang Tạm Dừng",
    1465: "Tạm Dừng - Thời Tiết Ấm Áp",
    1466: "Đang Cung Cấp Nhiệt",
    1467: "Bán Kính Tỏa Nhiệt",
    1468: "Thời Lượng Nhiên Liệu",
    1483: "Bắt Đầu Kéo",
    1484: "Kết Thúc Kéo",
    1485: "Hủy Kéo",
    1486: "Nâng Lên",
    1487: "Hạ Xuống",
    1488: "Xoay",
    1489: "Khóa Độ Cao",
    1490: "Bám Mặt Đất",
    1491: "Bật/Tắt Phá Dỡ",
    1492: "Chế Độ Dỡ Bỏ",
    1493: "Xóa Đánh Dấu",
    1494: "Nâng Lớp Cắt",
    1495: "Hạ Lớp Cắt",
    1496: "Góc Nhìn Lớp Cắt",
    1497: "Thoát Góc Nhìn Lớp Cắt",
    1498: "Thoát Góc Nhìn Nhiệt Độ",
    1499: "Đã Mở Khóa",
    1532: "Nghỉ - Thiếu nguyên liệu",
    1533: "Nghỉ - Kho thành phẩm đầy",
    1534: "Nghỉ - Chưa có chuột thợ",
    1535: "Đang làm việc",
    1536: "Nghỉ - Đang tạm dừng",
    1537: "Nghỉ - Chưa chọn công thức",
    1544: "Chuột Bị Khiếp Sợ",
    1545: "Đường Nối",
    1546: "Nghỉ",
    1547: "Đang Hoạt Động",
    1548: "Hết Hơi Nước",
    1549: "Thời gian cháy còn lại",
    1550: "Hủy",
    1551: "Quay Lại",
    1552: "Chỉ định nơi chuyển thành phẩm đến",
    1553: "Chỉ định nơi lấy nguyên liệu đầu vào",
    1554: "Phân bổ nhà ở cho chuột",
    1555: "Chỉ định nơi làm việc cho chuột",
    1556: "Đánh dấu tài nguyên ưu tiên cao",
    1557: "Các trại thu gom sẽ ưu tiên thu hoạch tài nguyên được đánh dấu",
    1558: "Đánh dấu địa hình để khai khoáng",
    1559: "Đánh dấu lần nữa để hủy hoặc dỡ bỏ giàn giáo đã dùng",
    1560: "Đánh dấu đất để canh tác",
    1561: "Cung ứng đủ số lượng yêu cầu",
    1562: "Nhiệm Vụ Đang Làm",
    1563: "Không có nhiệm vụ nào",
    1564: "Chi phí mỗi lượt tắm",
    1565: "Chuột đang có mặt",
    1566: "Chuột thợ sẽ tích trữ nhiên liệu và đem giao cho các lò sưởi gần đó.",
    1567: "Chuột thợ sẽ tích trữ xa xỉ phẩm và phân phát tới các ngôi nhà gần đó",
    1568: "Chuột sẽ đến đây để hồi phục khi bị thương hoặc ốm bệnh.",
    1569: "Chuột thợ được phân công sẽ dùng dược phẩm để giúp đồng loại bình phục nhanh hơn.",
    1570: "Kho Chứa",
    1571: "Vận Tải",
    1572: "Sản Xuất",
    1573: "Thống Kê",
    1574: "Thuộc địa của",
    1575: "Tài nguyên được chấp nhận để nộp cống",
    1576: "Các Khoản Nợ Phải Trả",
    1577: "Tình Trạng Tốt",
    1578: "Tình Trạng Hao Mòn",
    1579: "Hỏng Hóc Cơ Khí!",
    1580: "Bảo dưỡng thay thế tại mốc <0>",
    1581: "Vận Hành Bất Chấp",
    1582: "Đã Gạt Bỏ Cảnh Báo An Toàn",
    1583: "Máy móc sẽ hao mòn theo thời gian và cần được chuột thợ bảo dưỡng thay thế phụ tùng.",
    1584: "Bỏ qua rủi ro an toàn và ép máy móc tiếp tục vận hành",
    1585: "Không có phụ tùng thay thế!",
    1586: "Nghỉ - Máy móc hỏng hóc",
    1587: "Bảo Trì",
    1610: "Chất Xúc Tác",
    1611: "Đã Vô Hiệu",
    1612: "Thiếu",
    1613: "Đang Hoạt Động",
    1614: "Thiếu Điều Kiện Tiên Quyết",
    1616: "Chất xúc tác sẽ tiêu hao dần theo thời gian, giúp tăng sản lượng công thức khi được cấp phát.",
    1617: "<0> chuột vừa qua đời",
    1618: "Nhiệm Vụ Hết Hạn",
    1619: "Nhiệm vụ không được hoàn thành đúng hạn định.",
    1620: "Có Thể Hoàn Thành Nhiệm Vụ",
    1621: "Nhiệm vụ hiện đã có thể nộp và nhận thưởng.",
    1622: "Nhiệt Độ Hạ Thấp",
    1623: "Nhiệt độ ngoài trời đang trở nên lạnh lẽo.\n\nMức nhiệt này chưa tới mức nguy hiểm, nhưng việc sưởi ấm đầy đủ sẽ cải thiện tâm trạng và năng suất làm việc của bầy chuột.",
    1624: "Giá Lạnh Nguy Hiểm",
    1625: "Nhiệt độ ngoài trời đang trở nên lạnh buốt nguy hiểm!\n\nHãy bảo đảm bạn có đủ lò sưởi ấm áp, đặc biệt là quanh khu nhà ở. Nếu không, bầy chuột sẽ đối mặt với dịch bệnh và cái chết!",
    1626: "Bị Thương Hoặc Ốm Bệnh",
    1627: "Một chú chuột đang bị chấn thương nặng hoặc nhiễm bạo bệnh!\n\nChuột bị thương không thể làm việc và phải được điều trị tại Trạm Y Tế.\n\nQuá trình chữa trị khá chậm chạp, nhưng nếu bỏ mặc không điều trị, chú chuột có thể sẽ bỏ mạng!",
    1628: "Chuột Đang Chết Đói!",
    1629: "Một chú chuột đang chết đói!\n\nChú chuột có nguy cơ tử vong rất cao nếu không tìm được thức ăn trong vài ngày tới.",
    1630: "Lòng Dân Dâng Cao",
    1631: "Bạn đã gây dựng được điểm Lòng Dân rất cao từ bầy chuột.\n\nXây dựng Tòa Thị Chính sẽ cho phép bạn sử dụng điểm Lòng Dân dư dả này để ban hành các Chính Sách đắc lực.",
    1632: "Máy Móc Trục Trặc!",
    1633: "Một xưởng sản xuất đã hao mòn hết Máy Móc và không tìm thấy phụ tùng thay thế nào!\n\nBạn cần nhập khẩu thêm Máy Móc để duy trì các dây chuyền hoạt động, nếu không sẽ phải ép bầy chuột tiếp tục làm việc với thiết bị hỏng hóc.",
    1634: "Phe Móng Vuốt Mất Kiên Nhẫn",
    1635: "Phe Móng Vuốt đang dần mất niềm tin vào khả năng trả nợ của bạn.\n\nNếu tiếp tục trễ hạn các đợt cống nộp, loài mèo có thể sẽ áp dụng các biện pháp trừng phạt tàn khốc lên thuộc địa!",
    1636: "Phe Móng Vuốt Phẫn Nộ!",
    1637: "Việc liên tục thất hứa nộp thuế đang đe dọa trực tiếp sự tồn vong của thuộc địa!\n\nNếu bạn không gom đủ thuế ở chuyến tàu tiếp theo, bạn và toàn bộ bầy chuột sẽ phải chịu hình phạt thích đáng!",
    1638: "Thuế Khóa Kỳ Tới",
    1639: "Ngươi đã nộp đủ khoản thuế đầu tiên. Khá khen cho ngươi.\n\nChúng ta kỳ vọng sẽ thấy sản lượng của thuộc địa các ngươi tăng trưởng vượt bậc hơn nữa trong thời gian tới.",
    1640: "Thuế Khóa Kỳ Tới",
    1641: "Ngươi đã không nộp đủ khoản thuế cống nạp đầu tiên.\n\nChẳng sao cả — chúng ta sẽ dồn nợ sang chuyến tàu kế tiếp (dĩ nhiên là có tính lãi suất đi kèm).",
    1642: "Cáo Phó Thuộc Địa",
    1643: "Bầy chuột đang tiếc thương những đồng loại vừa qua đời.",
    1656: "Tốc Độ Sản Xuất",
    1657: "Hệ số tốc độ sản xuất hiện tại từ chuột thợ và các hiệu ứng bổ trợ khác.",
    1658: "Độ Thích Ứng Cây Trồng",
    1659: "Được quyết định bởi độ màu mỡ, ánh nắng và độ thích nghi tự nhiên của cây trồng trên mảnh ruộng này.",
    1660: "Dinh dưỡng còn lại trong đất. Có thể bón thêm phân để phục hồi.",
    1661: "Tài Nguyên Được Hỗ Trợ",
    1662: "Chọn",
    1663: "Thu Phóng",
    1664: "Nghỉ - Máy bơm cạn nước",
    1668: "Khu vực đổ hàng bị nghẽn",
    1671: "Giây",
    1672: "giây",
    1673: "Phút",
    1674: "Tạo Địa Hình",
    1675: "Độ C",
    1676: "Độ F",
    1677: "°C",
    1678: "°F",
    1680: "Từ chối yêu sách của Hải Tặc",
    1681: "Hải Tặc đã hài lòng",
    1682: "Chưa đáp ứng yêu sách",
    1727: "1 Phút",
    1728: "5 Phút",
    1729: "10 Phút",
    1730: "30 Phút",
    1731: "60 Phút",
    1732: "Không Tự Động Lưu",
    1745: "Chọn",
    1746: "Đã Từ Chối",
    1748: "Hoàn Thành Nhiệm Vụ",
    1749: "Hải Tặc sẽ trả đũa",
    1750: "Chiến tranh... chiến tranh không bao giờ thay đổi.\n\n...Ngoại trừ trong giai đoạn Truy Cập Sớm (Early Access) của chúng tôi. Cơ chế chiến tranh vẫn chưa hoàn thiện và trong quá trình phát triển, chúng tôi sẽ tiếp tục tinh chỉnh lại cách thức vận hành. Chúng tôi sẽ cố gắng duy trì khả năng tương thích của tệp lưu game, nhưng có thể không bảo đảm toàn diện cho mọi yếu tố chiến trận. Nếu bạn khơi mào chiến tranh, thuộc địa có thể sẽ bị san phẳng nếu bạn chưa sẵn sàng đối đầu với đợt tổng tấn công. Xin hãy bảo đảm rằng thuộc địa đã có một nền kinh tế vững vàng cùng lực lượng hải quân hùng hậu trước khi tuyên chiến.",
    1751: "Cảm ơn bạn đã trải nghiệm bản chơi thử Whiskerwood. Đây là dự án ấp ủ của chúng tôi, và chúng tôi quyết tâm tiếp tục phát triển cho đến khi trò chơi hoàn thiện trọn vẹn.\n\nTrong bản demo này, bạn có thể mở khóa một số bản vẽ thiết kế đầu game, bao gồm Đường Ray và Băng Tải. Nhiều bản vẽ công trình hơn sẽ cập bến trong phiên bản chính thức của Whiskerwood.\n\nMột số cơ chế chơi vẫn đang trong quá trình hoàn thiện, nên bạn có thể sẽ gặp lỗi hoặc những chỗ chưa tối ưu. Chúng tôi rất mong nhận được phản hồi nếu bạn gặp lỗi hay có bất kỳ đề xuất nào. Bạn có thể gửi email cho tôi tại devdaniel@minakatadynamics.co.jp, hoặc trò chuyện trực tiếp cùng tôi và cả đội ngũ phát triển trên Discord.\n\nCảm ơn bạn đã trải nghiệm trò chơi :)",
    1755: "Ngày <0>",
    1757: "Chưa Phân Công Tàu",
    1762: "Làm Thêm Giờ",
    1763: "Chuột thợ được tăng tốc độ sản xuất và sẽ làm việc xuyên màn đêm.",
    1768: "Dinh dưỡng trong đất xuống thấp!",
    1769: "Chọn Hạt Giống",
    1770: "Sản Lượng Hiện Tại",
    1771: "Thu Hoạch Sớm",
    1772: "Đang Thu Hoạch",
    1773: "Dịch Vụ",
    1774: "Thức ăn dân dã",
    1775: "Thưởng Khách Viếng Thăm",
    1778: "Gửi Chú Chuột Cần Lao Của Ta,",
    1779: "Kính gửi những ai hữu trách,",
    1780: "Thuyền Trưởng Dread",
    1781: "Dưới Sự Trị Vì Ân Đức Của Đức Vua,\nThuyền Trưởng Tama\nBộ Cung Ứng Hoàng Gia\n",
    1782: "Một Cư Dân Thuộc Địa Bất Khuất",
    1783: "Không Khoan Nhượng Với Hải Tặc",
    1784: "Đã có báo cáo về việc hải tặc đòi tiền chuộc trong vùng biển của ngươi. Trong bất kỳ tình huống nào, ngươi tuyệt đối không được nhượng bộ hay có ý định nộp tiền tống tiền cho chúng.\n\nNếu thuộc địa của ngươi còn sống sót, hãy lập tức báo cáo lại các thủ đoạn tống tiền của lũ Hải Tặc.\n",
    1785: "Lời Thỉnh Cầu Khiêm Nhường",
    1786: "Chúng ta chỉ là những kẻ lênh đênh sông nước mộc mạc, sau khi giũ bỏ xiềng xích vương quyền thì nay đang lâm vào cảnh ngặt nghèo. Trước đây những lúc khốn khó, các thuộc địa Chuột khôn ngoan và hào phóng đều sẵn lòng dâng cho chúng ta mọi thứ họ có.\n\nCác ngươi nên noi gương họ, và hãy làm cho nhanh. Chẳng có thứ gì đáng ghê tởm và đáng bị tiêu diệt hơn một thuộc địa bủn xỉn.\n",
    1787: "Ruộng Trồng Bông Vải",
    1788: "Hạn hán ở các thuộc địa phương nam đã tàn phá sạch các vụ thu hoạch Bông Vải. Vương quốc đang cần thêm nguồn cung Bông Vải gấp. Một phần thưởng hậu hĩnh đã được phê duyệt cho bất kỳ thuộc địa nào hoàn thành chỉ tiêu được giao.\n\nHãy gieo trồng và thu hoạch 34 Bông Vải. Hạt giống bông đã được gửi kèm trong kiện hàng này.\n",
    1789: "Những Ngôi Nhà Đáng Để Sống",
    1790: "Xin Trưởng Làng, liệu chúng tôi có thể có chỗ ở tươm tất hơn không? Hòn đảo mới này ban đầu thật hào hứng, nhưng niềm vui ấy đã tan biến rồi. Mỗi sớm mai thức giấc, mùi ẩm mốc lại xộc thẳng vào mũi.\n\nNếu nơi ăn chốn ở không được cải thiện, hòn đảo này sẽ chẳng bao giờ trở thành một mái ấm thực sự.\n",
    1791: "Dự Trữ Cho Mùa Đông",
    1792: "Trưởng Làng có còn nhớ câu chuyện ngụ ngôn về con mèo lười biếng và đàn hải ly chăm chỉ không? Về việc con mèo lười phớt lờ lời khuyên của đàn hải ly và chẳng bao giờ thèm tích trữ lương thực cho mùa đông? Nó thích nằm ườn sưởi nắng hơn là cần mẫn chắt chiu dành dụm…\n\nMùa đông đang cận kề rồi. Chúng ta cần phải noi gương đàn hải ly chăm chỉ, mau chóng tích trữ kho lương thôi.\n",
    1793: "Lửa Trại Cho Mùa Đông",
    1794: "Chúng tôi đang phải dãi dầu nơi hoang vu này, gió thấu xương và lạnh buốt giá. Dù chỉ là vài Đống Lửa Trại đơn sơ cũng sẽ là cứu cánh to lớn.\n\nXin hãy nhóm 5 Đống Lửa Trại. Vài đống gần khu nhà ở, và 1 hoặc 2 đống cho những chú chuột thu gom xa xôi nhất. Lửa trại tỏa nhiều khói đen, nên tránh đặt ở đầu ngọn gió thổi vào hoa màu hoặc trong các góc khuất chật hẹp.",
    1795: "Trang Phục Mùa Đông",
    1796: "Bộ lông của chúng tôi không đủ để chống chọi lại những cơn gió đông cắt da cắt thịt. Những chiếc Áo Choàng sẽ giúp chúng tôi giữ hơi ấm từ Lửa Trại lâu hơn và làm chậm nguy cơ bị cóng lạnh.\n\nXin hãy trao đổi hoặc may đủ Áo Choàng cho ít nhất 13 cư dân chuột. Có thêm thì càng quý. Và xin đừng quên bố trí Lửa Trại ở những vị trí chiến lược.",
    1797: "Cơn Đói Cồn Cào",
    1798: "Tôi đói đến lả đi rồi… Cầu xin Trưởng Làng, tôi cần chút đồ ăn. Tôi không nghĩ mình có thể cầm cự được lâu hơn nữa đâu.",
    1799: "Giá Rét Băng Cực",
    1800: "Tuyết đã phủ trắng từ đỉnh núi tràn xuống. Giờ đây ngay cả bờ biển cũng nhuốm màu băng giá. Các thùng nước để ngoài trời đều đã đóng băng cứng đờ. Nghĩ đến cảnh sáng ra thấy một đồng loại chuột bị đông cứng trong tuyết thật kinh hoàng. Xin hãy dựng đủ nhà ở để không còn chú chuột nào phải chịu cảnh vô gia cư. Ngủ ngoài trời chưa bao giờ là an toàn, nhưng lúc này nó là một bản án tử hình.",
    1801: "Trang Trí Nâng Cao Tinh Thần",
    1802: "Dù thời buổi có gian nan, đó cũng chẳng phải lý do để chúng ta bỏ bê thị trấn của mình. Làm đẹp các nẻo đường và dựng tượng sẽ thắp sáng tinh thần của toàn thể bầy chuột. Ngay cả Phe Móng Vuốt cũng chẳng thể tước đoạt một thú vui tao nhã như thế của chúng ta.\n\nXin hãy trang trí ít nhất 8 đoạn lối đi. Chúng tôi thỉnh cầu điều này đâu có quá đáng, phải không Trưởng Làng?",
    1803: "Cần Tình Nguyện Viên Đóng Thuế Bổ Sung",
    1804: "Đức Vua vĩ đại của chúng ta nhân từ mở rộng bổng lộc cho hàng Bá Tước, mở ra cơ hội quý báu để các Thuộc Địa Chuột bày tỏ lòng tri ân sâu sắc với Hoàng Gia. Một lễ hội quyên góp bù đắp thiếu hụt tình nguyện đặc biệt đã được ban bố. Mỗi thuộc địa đều được tự do tình nguyện cống nạp thêm một khoản thuế cho Vương Triều.\n\nThuộc địa của ngươi đã được chỉ định mức đóng góp tình nguyện là 877 vàng, phải thanh toán trong chuyến tàu thuế kế tiếp. Hãy nộp cho sòng phẳng và đúng hạn.",
    1805: "Phát Triển Dân Số Cho Tương Lai Lớn Hơn",
    1806: "Thuộc địa của ngươi bị phát hiện là quy mô quá nhỏ bé. Các khoản thuế thu được chưa tương xứng với tốc độ tăng trưởng kỳ vọng của một hòn đảo trù phú mà ngươi được tin tưởng giao phó.\n\nHãy đạt quy mô dân số 84 Cư Dân Chuột để xóa bỏ vết nhơ này trên sổ sách hoàng gia. Lưu ý: để được tính vào sổ bộ, số chuột đó bắt buộc phải còn sống.",
    1807: "Mùa Xuân Là Mùa Gieo Hạt",
    1808: "Côn trùng đang cựa mình thức giấc sau đợt tan băng mùa xuân. Đây là cơ hội để chúng ta tối đa hóa sản lượng mùa màng năm nay. Đã đến lúc gieo hạt và mở rộng những cánh đồng. Cây trồng sẽ phát triển nhanh nhất dưới nắng ấm mùa hạ, vì thế những tháng mùa xuân này là lúc chúng ta cần cày xới đất và gieo mầm.",
    1809: "Kính Trọng Và Dựng Tượng",
    1810: "Loài Mèo chúng ta vốn là một giống loài khiêm nhường. Chúng ta hiếm khi đưa ra những đòi hỏi khiếm nhã vốn thuộc về quyền hạn của mình. Thế nhưng vương quốc nhận thấy có quá ít thuộc địa biết đền đáp sự khiêm nhường này bằng lòng tôn kính đúng mực.\n\nThuộc địa của ngươi đã bị điểm tên trong danh sách ấy. Đây là lời cảnh cáo cuối cùng: Hãy tạc 8 Tượng Mèo Móng Vuốt xứng tầm với ân đức mà chúng ta đã ban bố cho bầy chuột các ngươi.",
    1811: "Sống Sót Qua Mùa Đông",
    1812: "Mùa đông xưa nay vẫn là thử thách khắc nghiệt đối với một số thuộc địa chuột. Nếu thuộc địa nào chủ quan không chuẩn bị trước, giá lạnh và sự đình đốn của mùa màng sẽ đẩy họ vào bước đường cùng quẫn. Đáng buồn thay, những lời cầu cứu của họ gửi đến bộ nha của chúng ta thường quá muộn để nhận được hồi âm chính thức.\n\nBởi vậy, hãy xem đây là thông tri báo trước: các ngươi phải sống sót qua mùa đông bằng mọi giá. Sẽ không có thuyền cứu hộ nào đâu. Chẳng có lựa chọn nào khác ngoài việc tự lực cánh sinh. Đừng làm uổng phí thuộc địa này.",
    1813: "Lối Đi Tăng Năng Suất",
    1814: "Dù là vác hàng hóa nặng hay rảo bước đi làm, chú chuột nào cũng trân quý một con đường phong quang. Một lối đi lát đá phẳng phiu, chẳng còn gì tuyệt hơn thế. Tôi rất thích cảm giác khi vừa cất bước đi đâu đó, và bùm – như thể có ai đó biết trước lối rẽ của tôi, một con đường hoàn hảo đã mở sẵn ngay trước mắt.\n\nChúng ta nên lát thêm nhiều con đường đẹp đẽ như thế.",
    1815: "Băng Tải Cơ Khí",
    1816: "Cảm giác như mỗi ngày trôi qua, đống hàng hóa này lại càng nặng thêm. Mới hôm qua thôi, tôi suýt còng cả lưng khi phải gồng gánh mấy tảng đá. Chúng ta có thể lắp vài Dây Băng Tải để giảm bớt gánh nặng được không?\n\nBăng tải giúp chuyển hàng mà không tốn lấy một giọt mồ hôi. Chúng ta chỉ việc thả hàng vào Phễu Nạp rồi đứng nhìn nó tự chạy. Băng tải sẽ chở hàng đi tít tắp, còn chúng ta có thể thảnh thơi quay lại làm việc của mình.",
    1817: "Những Chú Chuột Cần Việc Làm",
    1818: "Hồ sơ của chúng ta cho thấy ngươi đã tiếp nhận số lượng chuột thợ nhiều hơn số công việc tạo ra giá trị của thuộc địa.\n\nHãy nhớ rằng: nhàn cư vi bất thiện, chuột rảnh rỗi ắt sinh nông nổi nguy hiểm. Hãy giảm lượng chuột thất nghiệp xuống mức có thể quản lý được.",
    1819: "Xưởng Đóng Tàu",
    1820: "Hãy chuẩn bị tinh thần. Tin tức mà ta được ủy quyền thông báo cho ngươi là một minh chứng vĩ đại cho lòng đại lượng của Đức Vua. Hãy biết ơn. Hãy trân quý. Và hãy ghi nhớ ngày này vào lịch sử thuộc địa của ngươi.\n\nĐức Vua đã ban ân huệ cấp cho thuộc địa của ngươi bản vẽ thiết kế Xưởng Đóng Tàu. Đây là công nghệ được các kỹ sư Mèo Móng Vuốt mài giũa qua nhiều thế kỷ. Các xưởng đóng tàu hoàng gia của chúng ta đủ sức chế tác những Chiến Hạm Hạng Nhất lướt sóng uy phong và dẹp tan hải tặc nơi biển dữ.\n\nXưởng Đóng Tàu của thuộc địa ngươi dĩ nhiên không thể bì được với những xưởng đóng tàu hoàng gia tráng lệ, nhưng chúng hoàn toàn đủ sức đóng những chiếc thuyền đánh cá để nâng cao hơn nữa khả năng cống hiến cho Vương Triều.",
    1821: "Đội Tàu Đánh Cá",
    1822: "Đã đến lúc thuộc địa của ngươi phải đền đáp lòng nhân từ của Đức Vua. Hãy tận dụng xưởng đóng tàu mới đó để gây dựng một đội thuyền đánh cá tương xứng. Ít nhất 1 Thuyền Đánh Cá Một Buồm là đạt yêu cầu.\n\nTrong bất kỳ trường hợp nào, ngươi tuyệt đối không được tơ tưởng đến việc lạm dụng những con thuyền này để liên lạc với các thuộc địa khác. Mọi hành vi buôn lậu giữa các thuộc địa sẽ bị trừng phạt bằng một trăm phát đại bác bắn chìm tàu.",
    1823: "Tìm Thuộc Địa Khác",
    1824: "Bấy lâu nay chúng ta đã phải oằn mình chịu sự áp bức của Phe Móng Vuốt! Giờ đây thời cơ đã đến! Với những con tàu tự đóng, chúng ta có thể dong buồm tìm kiếm và bắt liên lạc với các thuộc địa anh em khác – hoặc thậm chí là các quốc gia lân bang!",
    1825: "Kiếm Vàng Nhờ Buôn Bán",
    1826: "Nếu chúng ta có thể bán sản phẩm công nghiệp để đổi lấy vàng thỏi, chúng ta sẽ trút bớt được gánh nặng cống nộp thuế khóa. Các đảo khác sẽ rất sẵn lòng đổi tài nguyên thô của họ lấy hàng hóa tinh chế của chúng ta. Lũ Mèo gọi đó là buôn lậu – như thể chúng ta nợ chúng từng giọt mồ hôi nước mắt của mình vậy!\n\nHãy thiết lập một tuyến giao thương và gom vàng để nộp thuế, để chúng ta có thể giữ lại nhiều sản vật hơn cho chính bản thân mình.",
    1827: "Tối Hậu Thư Khẩn Cấp Của Hải Tặc",
    1828: "Do sự cố ngoài ý muốn, một viên đại bác lạc đã bắn gãy cột buồm chiến hạm của chúng ta.\n\nVì thiệt hại này do sự cẩu thả từ đám chủ nhân Mèo Móng Vuốt của các ngươi gây ra, chúng ta buộc phải tìm đến các ngươi đòi bồi thường. Hãy giao nộp cho chúng ta đủ số Ván Gỗ để tu sửa chiến thuyền. Các ngươi có 3 ngày, nếu không sẽ không trách được chuyện chúng ta nã pháo san phẳng thuộc địa.",
    1832: "Không có nghiên cứu nào đang tiến hành",
    1839: "Không khả dụng trong bản chơi thử",
    1845: "Bạn có chắc chắn muốn tuyên chiến với Phe Móng Vuốt không?",
    1846: "Tuyên Chiến",
    1847: "Yêu Cầu Nguồn Nước Mặt",
    1848: "Yêu Cầu Lối Ra Đại Dương Cho Tàu Thuyền",
    1849: "Hủy Thu Hoạch Sớm",
    1854: "Thiếu Điều Kiện Tiên Quyết",
    1860: "Chỉ định tàu vào Bến Tàu Thợ",
    1861: "Bến Tàu Thợ đóng vai trò là căn cứ hoạt động cho từng con tàu",
    1870: "Mùa đông đã gõ cửa",
    1871: "Mùa đông băng giá khắc nghiệt khiến việc di chuyển đường biển trở nên vô cùng hiểm trở. Do đó, Đức Vua sẽ đình chỉ hầu hết các chuyến viếng thăm thuộc địa.\n\nChúng ta tin tưởng rằng các ngươi đã tích trữ đầy đủ nhu yếu phẩm và sẽ gặp lại các ngươi trong tình trạng bình an khi mùa xuân tới.",
    1872: "Tinh Thần Sa Sút",
    1873: "Những suy nghĩ tiêu cực vẫn còn dai dẳng",
    1874: "Vật Trang Trí Đã Dựng",
    1875: "Lối Đi Trang Trí Đã Lát",
    1876: "Tổng dự trữ lương thực",
    1877: "đã tích trữ",
    1878: "Chuột vô gia cư",
    1879: "Chuột thất nghiệp",
    1880: "Chuột đang đói",
    1881: "Đêm Sống Sót",
    1882: "Lợi Nhuận Buôn Lậu",
    1883: "Đảo Đã Khám Phá",
    1884: "Thanh toán toàn bộ nợ thuế",
    1885: "Nếu Từ Chối Nhiệm Vụ",
    1888: "Chúng ta đã ghi nhận sự thiếu hụt trong khoản thuế cống nạp tình nguyện được yêu cầu. Có lẽ chúng ta nên dành sự nâng đỡ của mình cho những thuộc địa biết điều hơn.",
    1889: "Khoản đóng góp thuế tình nguyện của ngươi đã được ghi nhận vào công trạng.",
    1890: "Khoản Quyên Thuế Tự Nguyện",
    1895: "Kẻ Trung Quân Bất Mãn",
    1896: "Kẻ sùng bái vương quyền bị điều đi làm việc công nghiệp sẽ không đóng góp gì cho mục tiêu của Phe Móng Vuốt",
    1918: "Vải Vóc Cũ",
    1935: "Kho sức chứa trung bình",
    1936: "Kho sức chứa rất nhỏ",
    1937: "Kho sức chứa cực nhỏ",
    1958: "Rất tiếc, đây là nhánh Thử Nghiệm (Beta Branch) không chính xác.\n\nXin vui lòng kiểm tra email để lấy mật khẩu của nhánh Beta chuẩn xác.\n\nBản cài đặt sẽ tự động thoát.\n\nCảm ơn bạn đã quan tâm đến trò chơi của chúng tôi :)",
    1959: "Sai Nhánh Thử Nghiệm",
    1960: "Đã nắm vững",
    1961: "Đã Chọn",
    1963: "Thức Ăn",
    1964: "Đồ Uống",
    1965: "Thức Ăn Nấu Chín",
    1966: "Ẩm Thực Thượng Hạng",
    1967: "Chi Tiết Tối Thiểu",
    1968: "Vận Chuyển Hàng Hóa",
    1977: "Vận Tải Bằng Xe Kéo",
    1980: "Nhấp để chọn.",
    1983: "Chào mừng bạn đến với Bản Chơi Thử Whiskerwood!\n\nWhiskerwood là dự án tâm huyết của chúng tôi, và chúng tôi vô cùng hào hứng mang đến cho bạn cái nhìn sớm về những chương đầu của trò chơi trước ngày phát hành chính thức vào cuối năm nay!\n\nBản demo sẽ cho phép bạn chơi thỏa thích bao lâu tùy ý, thiết lập các chuỗi sản xuất cốt lõi để giữ cho bầy chuột luôn ấm no hạnh phúc, và gom đủ sản vật nộp các khoản thuế ngày một gia tăng do lũ mèo bóc lột áp đặt. Liệu bạn có thể chèo lái thuộc địa của mình trụ vững được bao nhiêu ngày?\n\nKhi trò chơi chính thức ra mắt vào cuối năm nay, bạn sẽ được trải nghiệm nhiều chuỗi sản xuất, nhiệm vụ và thử thách phong phú hơn rất nhiều, bao gồm:\n109 công trình độc đáo có thể xây dựng\nCây công nghệ với hơn 50 nhánh nghiên cứu\nHơn 70 loại hàng hóa để khai thác, canh tác hoặc gia công chế tạo\nĐóng tàu phục vụ thám hiểm biển sâu, giao thương và chiến đấu\nCác bản đồ rộng lớn gấp 9 lần quy mô trong bản demo này\n\nNếu bạn có bất kỳ phản hồi hoặc đề xuất nào, xin vui lòng chia sẻ để chúng tôi hoàn thiện Whiskerwood tốt nhất có thể khi chính thức ra mắt!\n\nCảm ơn bạn đã trải nghiệm trò chơi của chúng tôi : )\n\nDaniel,\nLập trình viên",
    1984: "Hiện đang được nghiên cứu.",
    1985: "Cảm ơn bạn đã đồng hành cùng chúng tôi! Do trò chơi đang trong giai đoạn Bản Xem Trước (Game Preview), một số tính năng nền tảng có thể chưa hoạt động trơn tru, và bạn có thể bắt gặp một vài lỗi kỹ thuật cũng như tình trạng văng game. Trong suốt thời gian Preview, chúng tôi sẽ liên tục bổ sung nội dung mới, khắc phục sự cố, cân bằng lối chơi và hoàn thiện game dựa trên mọi báo cáo lỗi và góp ý quý báu từ cộng đồng. Xin vui lòng liên hệ với chúng tôi qua máy chủ Discord. Chân thành cảm ơn sự ủng hộ của bạn!",
    1986: "Hàm lượng dinh dưỡng trong đất canh tác. Sẽ hồi phục từ từ khi cạn kiệt. Có thể bổ sung và tăng tốc độ hồi phục bằng phân bón, đồng thời giúp nâng cao giới hạn phục hồi tối đa.",
    1987: "Đá lẫn trong tầng đất mặt. Chuột nông dân có thể dọn sạch chúng từ từ.",
    1988: "Dọn Đá Lẫn Trong Đất",
    1993: "Di chuyển nhanh hơn trên ruộng đồng",
    1996: "Chấp Nhận Tất Cả",
    1997: "Từ Chối Tất Cả",
    1998: "Thuế Đầu Chuột Tăng Thêm",
    1999: "Chi Phí Tăng Thêm Mỗi Cư Dân Chuột Được Nhận",
    2005: "Công trình nằm dưới lòng đất.",
    2017: "Kỳ Vọng Đời Sống",
    2018: "Cư Dân Khai Hoang Tân Thế Giới",
    2019: "Tiến Bộ Khoa Học Công Nghệ",
    2034: "Đánh dấu khu vực cần đắp nền bằng đá.",
    2035: "Chuột thợ san lấp sẽ đổ đá xuống độ cao được đánh dấu thấp nhất.",
    2062: "Một con tàu vừa cập bến ngỏ ý giao thương bí mật",
    2079: "Hy vọng dâng cao sau khi hoàn thành và toàn bộ cư dân chuột sẽ kỳ vọng mức sống tốt hơn.",
    2082: "Chất Lượng Tắm Giặt",
    2083: "Chất Lượng Ăn Uống",
    2084: "Chất Lượng Trang Phục",
    2085: "Chất Lượng Thức Ăn",
    2118: "Phí Tổ Chức Điều Phối",
    2120: "Chuột Thợ",
    2127: "Tay buôn lậu đề nghị mua hàng hóa bằng Vàng Thỏi",
    2128: "Mặt hàng xuất khẩu và giao thương giá trị cao",
    2129: "Chưa xếp hàng lên thuyền",
    2136: "Được Truyền Cảm Hứng",
    2137: "Bị lôi cuốn bởi những lời đồn thổi về nền độc lập tự chủ ngày một lớn mạnh",
    2138: "Đá Dằn Tàu",
    2139: "Đang Thu Hoạch Sớm",
    2141: "Không có chú chuột nào sở hữu kỹ năng yêu cầu",
    2153: "Gia Hạn Tự Động Làm Thêm Giờ",
    2154: "Bật để tự động gia hạn Làm Thêm Giờ khi hết hiệu lực, miễn là bạn còn đủ điểm Lòng Dân.",
    2158: "Cuộn Độ Cao",
    2160: "Sau khi xây dựng xong:",
    2163: "Không cho phép loại tài nguyên nào",
    2164: "Mức Ưu Tiên Mảnh Ruộng",
    2165: "Chỉ định những mảnh ruộng mà chuột nông dân của nông trại này sẽ ưu tiên chăm sóc.",
    2166: "Chỉ Chăm Sóc Khu Ưu Tiên"
}

def apply_phase6b():
    with open('translations/06_Quests_Events_Story.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    applied_count = 0
    missing_ids = []

    # Process items in range [335, 671)
    for idx in range(335, 671):
        item = data[idx]
        item_id = item['id']
        if item_id in PHASE6B_TRANSLATIONS:
            item['target_vi'] = PHASE6B_TRANSLATIONS[item_id]
            applied_count += 1
        else:
            missing_ids.append((idx, item_id, item['key']))

    with open('translations/06_Quests_Events_Story.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Applied translation to {applied_count} / {671 - 335} items in Phase 6B!")
    if missing_ids:
        print(f"Missing translations for {len(missing_ids)} items: {missing_ids[:5]}...")
    else:
        print("All 336 Phase 6B items translated 100%!")

if __name__ == '__main__':
    apply_phase6b()
