import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(PROJECT_ROOT, "translations", "02_Buildings_Logistics.json")

# Dictionary of high-quality translations for all 409 items in Phase 2
T = {
  # 1. Paths & Stairs
  "building.stonepath": "Đường Lát Đá",
  "building.stairs": "Cầu Thang Dài",
  "building.ladder": "Thang Dốc",
  "building.slide": "Máng Trượt Chuột",
  "building.conveyor": "Băng Chuyền Chở Chuột",
  "building.logisticshud": "Trạm Vận Tải Hàng",
  "building.woodcutter": "Trại Đốn Gỗ",
  "building.stonecutter": "Trại Khai Thác Đá",
  "building.gatheringcamp": "Chòi Hái Lượm",
  "building.fishingdock": "Bến Đánh Cá",
  "building.fishery": "Nhà Hun Khói",
  "building.lumbermill": "Xưởng Xẻ Gỗ",
  "building.granary": "Kho Thóc",
  "building.brickmaker": "Xưởng Đẽo Đá",
  "building.repair": "Trạm Bảo Dưỡng",
  "building.stewbrewery": "Bếp Nấu Súp",
  "building.finekitchen": "Bếp Thượng Hạng",
  "building.charcoalfurnace": "Lò Than Củi",
  "building.lab": "Phòng Kỹ Nghệ",
  "building.townhall": "Tòa Thị Chính",
  "building.factiondock": "Bến Cảng Chính",
  "building.eatery": "Quán Ăn Nhỏ",
  "building.smallwell": "Giếng Nước Nhỏ",
  "building.trashcollection": "Điểm Thu Gom Rác",
  "building.restroom": "Nhà Vệ Sinh",
  "building.flowerbed": "Bồn Hoa Dại",
  "building.bonfire": "Đống Lửa Sưởi",
  "building.statue": "Tượng Đài Móng Vuốt",
  "building.bonsai": "Cây Cảnh Bonsai",
  "building.smallplanter": "Chậu Cây Nhỏ",
  "building.woodbench": "Ghế Gỗ Dài",
  "building.signpost": "Bảng Thông Cáo Làng",
  "building.windmill": "Cối Xay Gió",
  "building.raincatcher": "Giàn Hứng Hơi Ẩm",
  "building.warehouse": "Kho Tổng",
  "building.smallwarehouse": "Kho Nhỏ",
  "building.sensortower": "Tháp Cảm Biến",
  "building.battery": "Bình Ắc Quy",
  "building.farm": "Nông Trại",

  # Belts (Aim Components)
  "aim.flat": "Băng Tải Phẳng",
  "aim.lift": "Băng Tải Leo Tầng",
  "aim.slide": "Máng Trượt Xuống Tầng",
  "aim.flat.desc": "Băng chuyền lăn đưa tài nguyên từ Phễu Nạp đến các điểm tiếp nhận.",
  "aim.lift.desc": "Đưa tài nguyên trên băng tải lên tầng vách đá cao hơn.",
  "aim.slide.desc": "Cho tài nguyên trượt dốc xuống tầng thấp hơn.",
  "aim.inbox": "Phễu Nạp Hàng",
  "aim.outbox": "Hộc Đón Hàng Băng Tải",
  "aim.inbox.desc": "Điểm tập kết thả hàng để cấp tài nguyên vào băng chuyền.\n\nCó thể cấu hình loại hàng cho phép.\n\nCác nhà xưởng có thể chọn điểm này để trả hàng ra.",
  "aim.outbox.desc": "Hộc hứng giữ tạm các món hàng chuyển tới để thợ bốc vác thủ công sau. Sức chứa có hạn.",

  # Extraction, Heating, Utilities
  "building.miningcamp": "Khu Khai Thác Mỏ",
  "building.heater": "Lò Sưởi Đá",
  "building.chimes": "Chuông Gió",
  "building.oresmelter": "Lò Nấu Quặng",
  "building.toolmaker": "Xưởng Rèn Đồng",
  "building.waterpump": "Máy Bơm Nước",
  "building.mousewheel": "Bánh Xe Guồng Chuột",
  "building.elevatorshaft": "Trục Thang Máy",
  "building.elevatorentrance": "Cửa Vào Thang Máy",
  "building.logabode": "Nhà Gỗ Đơn",
  "building.wheat": "Lúa Mì",
  "building.cheatheater": "Lò Sưởi Debug",
  "building.pipe": "Đường Ống Nước",
  "building.steampipe": "Đường Ống Hơi Nước",
  "building.coalProcessor": "Tháp Sàng Khoáng Sản",
  "building.teahouse": "Quán Trà",
  "building.firetender": "Trại Chăm Lửa",
  "building.bathhouse": "Nhà Tắm Hơi",
  "building.waterfountain": "Trụ Nước Uống",
  "building.logisticshub": "Trung Tâm Hậu Cần",
  "building.smallgranary": "Kho Thóc Nhỏ",
  "building.stonewall": "Tường Đá",
  "building.steamboiler": "Nồi Hơi Nước",
  "building.radiator": "Bộ Tản Nhiệt Hơi Nước",
  "building.researcharchive": "Kho Lưu Trữ Nghiên Cứu",
  "building.watertower": "Bồn Chứa Nước",

  # Houses
  "building.tinyhouse1": "Nhà Ván Gỗ Đơn",
  "building.tinyhouse2": "Nhà Đá Đơn",
  "building.tinyhouse3": "Nhà Sang Trọng Đơn",
  "building.smallhouse1": "Nhà Ván Gỗ Đôi",
  "building.smallhouse2": "Nhà Đá Đôi",
  "building.smallhouse3": "Nhà Sang Trọng Đôi",
  "building.rowhouse1": "Dãy Nhà Ván Gỗ",
  "building.rowhouse2": "Dãy Nhà Đá",
  "building.rowhouse3": "Dãy Nhà Sang Trọng",
  "building.steamtank": "Bồn Chứa Hơi Nước",
  "building.furnituremaker": "Xưởng Mộc",
  "building.supplier": "Tiệm Cung Ứng Hàng Xa Xỉ",
  "building.triage": "Trạm Sơ Cứu",
  "building.farmplot": "Thửa Ruộng",
  "building.ladderTurn": "Khúc Quanh Thang Dốc",
  "building.smallshipyard": "Xưởng Đóng Tàu Nhỏ",
  "building.bakery": "Lò Bánh Mì",
  "building.tailor": "Tiệm May Mặc",
  "building.office": "Văn Phòng Hành Chính",
  "building.weaver": "Xưởng Dệt Vải",
  "building.steamvalve": "Van Hơi Nước",
  "building.steamengine": "Động Cơ Hơi Nước",
  "building.miningladder": "Thang Mỏ Chuyên Dụng",
  "building.waterstatue": "Đài Phun Nước Trang Trí",
  "building.stonestairs": "Cầu Thang Đá",

  # Descriptions
  "building.stairs.desc": "Cầu thang gỗ chất lượng tốt. Đi lại nhanh và thoải mái hơn thang dốc.",
  "building.stonestairs.desc": "Cầu thang đá kiên cố vững chãi.",
  "building.fastfloor.desc": "Lối đi bằng phẳng lát từ đá phiến đẽo gọt.",
  "building.conveyor.desc": "Băng chuyền cơ khí đưa bà con chuột di chuyển nhanh chóng về một hướng.",
  "building.slide.desc": "Đường trượt dốc giúp các chú chuột trượt xuống cực nhanh.\n\nNối liền nhiều đoạn trượt sẽ giữ được đà di chuyển.",
  "building.shortstairs.desc": "Cầu thang hẹp, hơi chênh vênh nhưng đỡ tốn diện tích.",
  "building.shortstairs_turnLeft.desc": "Cầu thang xoắn ốc nhỏ hẹp rẽ về bên trái.",
  "building.shortstairs_turnRight.desc": "Cầu thang xoắn ốc nhỏ hẹp rẽ về bên phải.",
  "building.elevatorEntrance.desc": "Khoang thang máy có bệ đón khách ra vào.",
  "building.elevatorShaft.desc": "Khoang trục thang máy chỉ chạy qua, không có bệ đón.",
  "building.bridge_medium.desc": "Nối liền hai mỏm vách đá vững chắc mà không cần cột chống.",
  "building.lumbermill.desc": "Xẻ gỗ cây thành những tấm ván gỗ bóng bẩy.",
  "building.brickmaker.desc": "Đẽo gọt đá tảng thô thành vật liệu xây dựng đa dụng.",
  "building.weaver.desc": "Dệt sợi lanh thành áo choàng hoặc xe sợi mịn thành vải vóc.",
  "building.fishery.desc": "Nướng và hun khói cá tươi để bảo quản dùng được lâu.",
  "building.stewery.desc": "Nấu súp và các món hầm ấm bụng cho cả làng.",
  "building.finekitchen.desc": "Nấu nướng các bữa ăn thịnh soạn bằng gia vị quý hiếm.",
  "building.bakery.desc": "Nướng bánh mì thơm ngon và các loại bánh ngọt.",
  "building.charcoalFurnace.desc": "Đốt gỗ khúc thành than củi sưởi ấm.",
  "building.coalProcessor.desc": "Sàng lọc quặng phi kim thành các loại vật liệu tinh chế.",
  "building.oresmelter.desc": "Luyện các loại quặng kim loại có điểm nóng chảy thấp thành thỏi đúc.",
  "building.toolmaker.desc": "Chế tạo công cụ và vật phẩm hữu ích từ đồng đỏ và đồng điếu.",
  "building.tailor.desc": "May áo choàng giữ ấm và các sản phẩm dệt may cao cấp.",
  "building.furnitureMaker.desc": "Đẽo gọt bàn ghế, công cụ và vật dụng gia đình bằng gỗ.",
  "building.researchbuilding.desc": "Nghiên cứu tạo ra điểm tri thức để mở khóa công nghệ mới cho nhà chuột.",
  "building.archive.desc": "Mở rộng sức chứa điểm tri thức khoa học.",
  "building.park.desc": "Khu công viên thảm cỏ xanh mướt cho bà con đi dạo mát.",
  "building.flowerbed.desc": "Thảm hoa dại nhỏ điểm tô sắc màu.",
  "building.smallstatue.desc": "Tượng đài thị uy đầy đe dọa của Phe Móng Vuốt.",
  "building.smallplanter.desc": "Bồn hoa dại bằng gỗ mộc mạc.",
  "building.woodenbench.desc": "Nơi lý tưởng để các chú chuột dừng chân ngơi nghỉ.",
  "building.signpost.desc": "Bảng thông cáo để truyền tin và ghi chép việc làng.",
  "building.stonewall.desc": "Tường đá kiên cố dùng để quây khuôn viên hoặc làm bệ đỡ.",
  "building.stonegate.desc": "Cổng vòm đá cho chuột đi qua lại.",
  "building.chimes.desc": "Biến làn gió biển thành những nốt nhạc du dương.",
  "building.waterstatue.desc": "Đài phun nước ấn tượng. Cần được cấp nước để hoạt động.",
  "building.mousewheel.desc": "Phát điện bằng những giọt mồ hôi chuột chạy guồng.",
  "building.pipe.liquid.desc": "Đường ống dẫn nước sạch.",
  "building.waterpump.desc": "Hút nước biển hoặc nước ngọt từ bờ lên đảo.",
  "building.watertower.desc": "Chứa được lượng nước dự trữ khổng lồ.",
  "building.pipe.steam.desc": "Đường ống dẫn hơi nước nhiệt độ cao.",
  "building.steamvalve.desc": "Van khóa hơi nước. Tự động đóng nếu áp suất ngõ vào thấp hơn ngưỡng cài đặt.",
  "building.steamboiler.desc": "Đun sôi nước thành hơi nước áp suất cao.",
  "building.steamtank.desc": "Bồn chứa được lượng hơi nước rất lớn.",
  "building.radiator.desc": "Sưởi ấm khu vực xung quanh bằng hơi nước dẫn qua đường ống.",
  "building.steamengine.desc": "Tăng tốc độ làm việc hoặc sản lượng cho các nhà xưởng liền kề nhờ năng lượng hơi nước.",
  "building.infiniteFluidSource.desc": "Cung cấp nước và hơi nước vô tận (Debug).",
  "building.infiniteFluidSink.desc": "Hút cạn nước và hơi nước vô tận (Debug).",
  "building.infiniteResourceSource.desc": "Cung cấp tài nguyên vô hạn (Debug).",
  "building.infiniteResourceSink.desc": "Tiêu hủy tài nguyên vô hạn (Debug).",
  "building.woodcutter.desc": "Chặt hạ cây cối trong khu vực lân cận.",
  "building.gatherer.desc": "Thu lượm rau củ, quả dại quanh vùng.",
  "building.fishingdock.desc": "Câu cá vùng nước nông ven bờ đảo.",
  "building.miningcamp.desc": "Đào bới các khối đất đá được đánh dấu khai khoáng.\n\nDùng Công Cụ Khai Mỏ để khoanh vùng đào.",
  "building.farm.desc": "Trồng trọt và gặt hái nông sản trong tầm của nông trại.\n\nDùng Công Cụ Trồng Trọt để quy hoạch luống đất.",
  "building.homeland_factiondock.desc": "Bến cảng lớn nơi các đoàn tàu từ Mẫu quốc có thể cập bến.",
  "building.tradedock.desc": "Mở rộng giao thương với mạng lưới thương thuyền biển khơi.",
  "building.townhall.desc": "Trung tâm hành chính mộc mạc của làng chuột. Cho phép ban hành các chính sách cơ bản.",
  "building.civicoffice.desc": "Văn phòng mở rộng để xử lý lượng giấy tờ ngày càng nhiều.\n\nCho thêm +1 ô Chính Sách.",
  "building.firetender.desc": "Dự trữ than củi và chuyên chở đi tiếp tế cho các lò sưởi và nồi hơi quanh vùng.",
  "building.bonfire.desc": "Đống lửa sưởi ấm đơn giản, tầm ảnh hưởng hẹp và tốn ít củi đốt.",
  "building.heater.desc": "Lò sưởi bằng đá lớn, sưởi ấm diện rộng với hiệu suất nhiên liệu cao hơn.",
  "building.infiniteHeater.desc": "Nguồn nhiệt vĩnh cửu (Debug).",
  "building.supplier.desc": "Thu gom hàng hóa xa xỉ và mang phân phát đến tận nhà cho các gia đình chuột.",
  "building.waterfountain_piped.desc": "Cấp nước uống mát lành cho thợ thuyền mệt mỏi.\n\nCần kết nối với đường ống nước.",
  "building.triagebeds.desc": "Bà con chuột ốm đau hoặc bị thương sẽ tĩnh dưỡng hồi phục tại đây.",
  "building.teahouse.desc": "Nơi thưởng thức trà ngon sau một ngày dài làm lụng.\n\nCần một chú chuột pha chế túc trực phục vụ.",
  "building.bathhouse.desc": "Bồn tắm nước nóng giúp thư giãn sảng khoái vào buổi tối.",
  "building.vending.desc": "Nơi ấm cúng để ăn uống chuyện trò vào buổi tối.\n\nCần một chú chuột chuẩn bị đồ ăn thức uống ban ngày.",
  "building.loghouse.desc": "Túp lều gỗ đơn sơ cho một chú chuột trú ngụ qua mùa mưa rét.",
  "building.tinyhouse1.desc": "Nhà ván gỗ nhỏ vừa vặn cho một chú chuột.",
  "building.house1.desc": "Nhà ván gỗ khang trang dành cho hai chú chuột.",
  "building.rowhouse1.desc": "Dãy nhà ván gỗ liền kề dành cho hai chú chuột.",
  "building.tinyhouse2.desc": "Nhà đá nhỏ kiên cố cho một chú chuột.",
  "building.house2.desc": "Nhà đá khang trang ấm áp dành cho hai chú chuột.",
  "building.rowhouse2.desc": "Dãy nhà đá liền kề vững chãi cho hai chú chuột.",
  "building.tinyhouse3.desc": "Nhà nhỏ sang trọng đầy đủ tiện nghi cho một chú chuột.",
  "building.house3.desc": "Nhà đôi sang trọng dành cho hai chú chuột.",
  "building.rowhouse3.desc": "Dãy nhà sang trọng bề thế cho hai chú chuột.",
  "building.smallwarehouse.desc": "Kho chứa hàng cỡ nhỏ.\n\nCó thể phân công thợ đẩy xe kéo hàng từ các kho khác về đây.",
  "building.warehouse.desc": "Kho tổng quy mô lớn chứa được mọi loại hàng hóa.\n\nTài nguyên lưu trữ tại đây có thể đem giao thương hoặc xuất khẩu nộp cống nạp.",
  "building.chimneySegment.desc": "Hút khói ô nhiễm từ dưới chân và xả ra ở đỉnh ống khói trên cao.",

  # Advanced Industry & Ships
  "building.oilpress": "Máy Ép Dầu",
  "building.shipyard": "Xưởng Đóng Tàu",
  "building.mill": "Cối Xay Bột",
  "building.mill.desc": "Cối đá chạy bằng sức gió để xay lúa mì thành bột mịn.",
  "building.decorativetree": "Cây Cảnh Trang Trí",
  "building.decorativetree.desc": "Cây bóng mát trổ hoa rực rỡ.",
  "building.fancyEatery": "Đại Sảnh Tiệc",
  "building.fancyEatery.desc": "Phòng ăn sang trọng dành cho những chú chuột giàu có bậc nhất làng.",
  "building.jumppad": "Bệ Phóng Chuột",
  "building.jumppad.desc": "Thiết bị dùng hơi nước đẩy các chú chuột vọt lên các tầng vách đá cao.",
  "building.watervalve": "Van Nước",
  "building.watervalve.desc": "Van khóa nước tự động. Đóng lại nếu áp suất ngõ vào thấp hơn mức quy định.",
  "building.rail": "Đoạn Đường Ray",
  "building.rail.desc": "Tuyến đường sắt tốc độ cao chuyên chở cư dân chuột.",
  "building.rail_station": "Sân Ga Tàu Hỏa",
  "building.rail_station.desc": "Nơi các chú chuột lên hoặc xuống mạng lưới tàu hỏa.",
  "building.rail_steambooster": "Trạm Tăng Tốc Hơi Nước",
  "building.rail_steambooster.desc": "Phun hơi nước áp suất cao giúp toa tàu phóng nhanh hơn.",

  # Logistics Links
  "logistics.neareststockpile": "Kho Gần Nhất",
  "logistics.multipleSources": "Nhiều Nguồn Cấp",
  "logistics.multipleDestinations": "Nhiều Nơi Nhận",
  "logistics.sourcingFrom": "Lấy hàng từ",
  "logistics.deliveringTo": "Giao hàng đến",
  "building.blastfurnace": "Lò Cao Luyện Kim",
  "building.blacksmith": "Lò Rèn Sắt Thép",
  "building.netter": "Xưởng Đan Lưới",
  "building.sailmanufactory": "Xưởng May Buồm",
  "building.cannonfoundry": "Xưởng Đúc Đại Bác",
  "building.laboratory": "Phòng Hóa Phẩm",
  "building.apothecary": "Tiệm Thuốc Nấm",
  "building.cannery": "Xưởng Đóng Hộp",
  "building.teaprocessor": "Xưởng Sao Trà",
  "building.machinist": "Xưởng Cơ Khí Chế Tạo",

  "building.blastfurnace.desc": "Luyện các loại quặng kim loại có điểm nóng chảy cao thành thỏi đúc.",
  "building.blacksmith.desc": "Chế tạo công cụ và vũ khí từ sắt và thép.",
  "building.netter.desc": "Đan bện dây thừng thành lưới đánh cá trên biển.",
  "building.sailmanufactory.desc": "May những cánh buồm lớn phục vụ đóng tàu vượt biển.",
  "building.cannonfoundry.desc": "Đúc nòng đại bác và lắp ráp pháo phòng thủ bờ biển.",
  "building.laboratory.desc": "Sản xuất xà phòng, dược phẩm và đồ dùng vệ sinh sức khỏe.",
  "building.apothecary.desc": "Chiết xuất dược liệu quý từ các loại nấm rừng.",
  "building.cannery.desc": "Đóng hộp thực phẩm để bảo quản cho những chuyến hải trình dài ngày.",
  "building.teaprocessor.desc": "Ủ và sao lá trà tươi thành trà khô hảo hạng.",
  "building.machinist.desc": "Sản xuất máy móc phụ tùng hướng tới tự chủ công nghiệp.",
  "building.campfire": "Đống Lửa Trại",
  "building.campfire.desc": "Đống lửa sưởi khẩn cấp lúc giá rét.\n\nTự tàn lụi sau khi cháy hết củi.",
  "building.smallworkdock": "Bến Tàu Thợ",
  "building.smallworkdock.desc": "Bến cảng nhỏ để chỉ định tàu và thủy thủ ra khơi làm việc trên biển.",
  "building.plankpath": "Đường Ván Gỗ",
  "building.logpath": "Đường Gỗ Tạm",
  "building.plankpath.desc": "Đường đi lát ván gỗ êm chân, đi lại nhanh hơn.",
  "building.logpath.desc": "Đường mòn gồ ghề ghép tạm bợ bằng thân gỗ thô.",
  "building.mediumWarehouse": "Kho Vừa",
  "building.mediumwarehouse.desc": "Kho chứa hàng cỡ trung bình.\n\nCó thể cắt cử thợ đi xe kéo gom hàng từ các kho khác về.",
  "building.spicegrinder": "Cối Nghiền Gia Vị",
  "building.spicegrinder.desc": "Xay ớt tiêu thành gia vị thơm lừng.",
  "building.tinywarehouse": "Chòi Chứa Hàng",
  "building.smallbrickhouse": "Nhà Gạch Nhỏ",
  "building.smallbrickhouse.desc": "Ngôi nhà gạch ấm cúng dành cho một chú chuột.",
  "building.tinywarehouse.desc": "Chòi nhỏ để cất giữ một lượng nhỏ tài nguyên tiện tay.\n\nCó thể phân công thợ gom đồ từ các kho khác về.",
  "building.stoneshelter": "Chòi Trú Bằng Đá",
  "building.stoneshelter.desc": "Căn chòi đá dựng tạm bợ, chỉ vừa đủ chui ra chui vào.",

  # Logistics Whitelist & Rules
  "logistics.assignedDropoffonly": "Chỉ nhận nơi đã chỉ định",
  "logistics.assignedDropoffOnly.detail": "Chỉ tiếp nhận hàng từ các nhà xưởng đã cài đặt điểm trả hàng về đây.",
  "logistics.whitelist": "Danh Sách Hàng Cho Phép",
  "logistics.inboxHint": "Tài nguyên giao đến đây sẽ được thả thẳng lên băng chuyền kết nối",
  "building.stonedec_wall": "Tường Đá Trang Trí",
  "building.stonedec_pillar_short": "Cột Đá Thấp",
  "building.stonedec_pillar_tall": "Cột Đá Cao",
  "building.stonedec_pedestal": "Bệ Đá Đặt Tượng",
  "building.stonedec_gate": "Cổng Đá",
  "building.stonedec_arch": "Cổng Vòm Đá",
  "building.stonedec_platform": "Bệ Đỡ Bằng Đá",
  "building.stonedec.desc": "Công trình kiến trúc bằng đá.",
  "building.oilpress.desc": "Dùng máy ép hơi nước để chiết xuất dầu mỡ thực vật.",
  "building.shipyard.desc": "Ụ đóng tàu lớn trên cạn để đóng những chiến thuyền vượt biển bề thế.\n\nTàu đóng xong phải gán vào Bến Tàu Thợ để tuyển thủy thủ.",
  "logistics.filterhint.whitelist": "Chọn tài nguyên hoặc nhóm hàng cho phép nhận",
  "logistics.filterhint.all": "Tiếp nhận mọi loại tài nguyên",
  "logistics.keepEmpty": "Luôn cố gắng dọn rỗng",
  "logistics.keepEmpty.desc": "Thợ kho sẽ ưu tiên chuyển mọi món hàng trong kho này sang các kho nhận hàng khác.",
  "logistics.constructionAccess": "Cho Phép Lấy Hàng Xây Dựng",
  "logistics.constructionAccess.desc": "Cho phép thợ xây rút tài nguyên trong kho này để thi công công trình.",
  "logistics.desired": "Mức Yêu Cầu",

  # Colony Problems
  "problem.housingShortage": "Thiếu Nhà Ở!",
  "problem.housingShortage.desc": "Số lượng chuột đông hơn chỗ ngủ hiện có.\n\nHãy dựng thêm nhà cho bà con chuột có chỗ ngả lưng!",
  "problem.longpaths": "Quãng Đường Đi Bộ Quá Xa!",
  "problem.longpaths.desc": "Vài chú chuột đang phải đi bộ quá xa! Tuyến đường có bị đứt gãy chỗ nào không?",
  "problem.nobuilders": "Hết Thợ Xây!",
  "problem.nobuilders.desc": "Cần những chú chuột rảnh rỗi để thi công công trình.\n\nHiện toàn bộ dân chuột đều đã bận việc.",
  "problem.pathIssues": "Đường Đi Bị Gián Đoạn",
  "problem.pathIssues.desc": "Một hoặc nhiều chú chuột không thể tìm thấy đường đến nơi cần đến.",
  "problem.lowfood": "Sắp Cạn Lương Thực!",
  "problem.lowfood.desc": "Lượng thức ăn dự trữ trong kho đang cạn dần ở mức báo động.",
  "problem.buildingDestroyed": "Công Trình Bị Sập Đổ!",
  "problem.buildingDestroyed.desc": "Công trình bị hỏng cần được đánh dấu để thợ sửa chữa lại.",

  # Logistics Hub Hints
  "logistics.hint1": "Thợ hậu cần vận chuyển tài nguyên giữa các kho theo lượng hàng yêu cầu",
  "logistics.hint2": "Hãy xây thêm ít nhất một kho nữa để mở khóa bảng điều khiển Hậu Cần",
  "logistics.addSourceWarehouse": "Thêm Kho Cấp Hàng",
  "logistics.addSourceWarehouse.desc": "Chọn những kho mà công trình này được phép đến lấy hàng.\n\nNếu để trống, thợ sẽ tự đến kho gần nhất có hàng.",
  "logistics.addDestinationWarehosue": "Thêm Kho Nhận Hàng",
  "logistics.addDestinationWarehouse.desc": "Chọn kho hoặc xưởng mà công trình này được phép giao hàng đến.\n\nNếu để trống, thợ sẽ tự đem đến kho gần nhất.",
  "logistics.clearAllLinks": "Xóa Mọi Liên Kết",
  "logistics.clearAllLinks.desc": "Gỡ bỏ tất cả tuyến kết nối đã chỉ định.",
  "building.oceanvoid": "Ống Xả Nước Ra Biển",
  "building.oceanvoid.desc": "Xả nước thừa từ hệ thống ngược trở lại biển.",
  "building.terraformCamp": "Bãi Đổ Đá Lấn Đất",
  "building.terraformCamp.desc": "Đổ đá hộc xuống dưới để bồi đắp địa hình thành cột đất vững chắc.",
  "problem.unburiedWhiskers": "Cư Dân Chưa Được An Táng!",
  "problem.unburiedWhiskers.desc": "Bà con chuột cần một phần mộ tươm tất để yên nghỉ.",
  "building.grave": "Phần Mộ",
  "building.grave.desc": "Nơi an nghỉ ngàn thu cho các chú chuột đã qua đời.",
  "building.hangingGarden": "Vườn Treo",
  "building.hangingGarden.desc": "Vườn cây sum suê với những nhành thường xuân rủ bóng xuống tầng dưới.",
  "building.flaxspinner": "Xưởng Kéo Sợi Lanh",
  "building.flaxspinner.desc": "Se sợi lanh thành dây thừng chắc nịch hoặc sợi mịn dệt vải.",
  "building.cottongin": "Máy Tách Hạt Bông",
  "building.cottongin.desc": "Tách hạt khỏi xơ bông để chuẩn bị kéo thành sợi.",
  "building.largewarehouse": "Kho Lớn",
  "building.largewarehouse.desc": "Kho chứa hàng quy mô lớn.\n\nCó thể phân công thợ đẩy xe kéo chuyển hàng từ kho khác về.",
  "building.showers": "Nhà Tắm Vòi Sen",
  "building.showers.desc": "Hệ thống vòi tắm nước ấm dẫn qua đường ống cho chuột tắm gội sạch sẽ.",
  "building.bathingdock": "Cầu Tắm Biển",
  "building.bathingdock.desc": "Bến gỗ ven biển cho chuột nhảy xuống tắm mát xua tan mệt mỏi.",
  "building.house4.desc": "Nhà đôi xa hoa tráng lệ dành cho hai chú chuột.",
  "building.rowhouse4": "Dãy Nhà Xa Hoa",
  "building.rowhouse4.desc": "Dãy nhà liền kề tráng lệ cho hai chú chuột.",
  "building.smallhouse4": "Nhà Xa Hoa Đôi",
  "building.tinyhouse4": "Nhà Xa Hoa Đơn",
  "building.tinyhouse4.desc": "Nhà nhỏ xa hoa lộng lẫy dành cho một chú chuột.",

  # Logistics Stats & Indicators
  "logistics.totalLogisticsWorkers": "Tổng Thợ Hậu Cần",
  "logistics.totalWarehouses": "Tổng Số Kho Hàng",
  "logistics.totalDeficits": "Danh sách hàng đang thiếu cần chở đến:",
  "logistics.noDeficits": "Không có yêu cầu nào",
  "logistics.warehouseHint": "Trung Tâm Hậu Cần lân cận sẽ điều phối xe chuyển hàng theo yêu cầu giữa các kho",
  "logistics.workerHint": "Thợ hậu cần vận chuyển hàng hóa giữa các kho dựa trên danh sách yêu cầu",
  "logistics.nologisticsHubs": "Chưa xây Trung Tâm Hậu Cần nào!",
  "building.logisticshub.desc": "Giúp việc vận chuyển hàng hóa giữa các kho bằng xe kéo đạt hiệu suất cao.",
  "logistics.requested": "Đã Yêu Cầu",
  "logistics.inbound": "Đang Chuyển Đến",
  "problem.noresourcesInRange": "Trại Đang Nhàn Rỗi!",
  "problem.noresourcesInRange.desc": "Trại không tìm thấy việc gì trong phạm vi hoạt động.",
  "logistics.totalcapacity": "Tổng Sức Chứa",
  "building.labNew": "Phòng Nghiên Cứu Kỹ Nghệ",
  "building.laboratoryNew": "Xưởng Hóa Chất",
  "building.earthworks": "Trạm Đắp Đất",
  "building.earthworks.desc": "Bồi đắp đất đá vào các khu vực được đánh dấu.",
  "logistics.disableAcceptingDeliveries": "Từ chối mọi chuyến giao hàng",
  "logistics.requestsDisabled": "Đã Khóa Yêu Cầu",
  "logistics.enableAll": "Cho Phép Tất Cả",
  "logistics.disableAll": "Từ Chối Tất Cả",
  "logistics.keepWarehouseEmpty": "Rút sạch đồ trong kho",
  "logistics.resourceWhitelistHint": "Có thể tích chọn loại hàng cho phép trong bảng.",
  "building.school": "Trường Học",
  "building.school.desc": "Nơi các chú chuột thông thái truyền dạy kỹ năng nghề nghiệp cho thế hệ sau.",
  "building.bridge_medium": "Cầu Mái Che",
  "building.coordinationOffice": "Văn Phòng Điều Phối",
  "building.coordinationOffice.desc": "Đội ngũ nhân sự chuyên trách giúp thợ thuyền phối hợp làm việc nhịp nhàng hơn.",
  "building.giantwarehouse": "Kho Khổng Lồ",
  "building.giantwarehouse.desc": "Kho hàng sâu hun hút với sức chứa tài nguyên gần như vô tận.",
  "problem.campstoragefull": "Kho Xưởng Đã Đầy!",
  "problem.campstoragefull.desc": "Xưởng không tìm thấy kho nào còn chỗ để trả thành phẩm.",
  "building.windsock": "Cột Báo Gió",
  "building.windsock.desc": "Túi vải đón gió giúp nhận biết hướng gió và sức gió ngoài biển.",
  "building.anchoredplatform": "Bệ Đỡ Neo Vách Đá",
  "building.anchoredplatform.desc": "Giàn khung dầm gỗ chìa ra làm nền móng để xây cất công trình phía trên.",
  "building.stonedec_arch.desc": "Cổng vòm đá bề thế làm nền móng vững chắc cho công trình bên trên.",
  "problem.freezingTriage": "Trạm Sơ Cứu Bị Lạnh Cóng!",
  "problem.feezingTriage.desc": "Trạm sơ cứu quá lạnh buốt, bệnh nhân không thể hồi phục!",

  # Belts & Splitters
  "aim.splitter": "Bộ Chia Băng Tải",
  "aim.splitter.desc": "Tách luồng hàng hóa rẽ sang hai nhánh băng chuyền.",
  "aim.sorter": "Bộ Lọc Hàng",
  "aim.sorter.desc": "Chỉ thả đúng loại hàng được cài đặt xuống dưới. Dùng để tách riêng từng món hàng ra khỏi băng tải chung.",
  "aim.clift": "Thang Nâng Đảo Chiều",
  "aim.clift.desc": "Dùng bánh răng nâng hàng lên theo phương thẳng đứng kết hợp đảo chiều chuyển động.",
  "logistics.splitterFilter": "Chọn tài nguyên tách xuống băng chuyền dưới",
  "aim.smallStorage": "Hộc Đón Hàng",
  "aim.smallStorage.desc": "Hộc chứa hàng siêu nhỏ chuyên đón đồ rơi từ băng chuyền.\n\nChỉ tiếp nhận hàng chuyển từ băng chuyền.",
  "logistics.conveyorDropoffOnly": "Kho này chỉ tiếp nhận tài nguyên rơi từ băng chuyền",
  "aim.extractor": "Bộ Rút Hàng Kho",
  "aim.extractor.desc": "Rút thẳng tài nguyên từ kho liền kề đặt lên băng chuyền.",
  "logistics.logisticsCanTake": "Cung cấp cho hậu cần",
  "logistics.logisticsCanTake.hint": "Cho phép thợ hậu cần rút tài nguyên dư thừa từ kho này mang đi nơi khác",
  "aim.oceandump": "Cửa Xả Hàng Xuống Biển",
  "aim.oceandump.desc": "Xả thẳng bất kỳ món hàng nào trên băng chuyền xuống lòng biển.\n\nXả hàng ra biển có thể gây ô nhiễm và hủy hoại hệ sinh thái biển!",
  "building.raftDock": "Bến Bè Mảng",
  "building.raftDock.desc": "Bè gỗ thô sơ dùng để đi lại giữa các đảo lân cận.\n\nCần tối thiểu hai bến bè mới hoạt động được.",
  "building.bush": "Bụi Cây Nhỏ",
  "building.bush.desc": "Bụi cây và dương xỉ dại.",
  "logistics.allowOverflow": "Cho Phép Tràn Băng",
  "building.smallshipyard.desc": "Ụ đóng tàu nhỏ trên cạn để đóng các loại tàu thuyền vượt biển.\n\nTàu đóng xong phải gán vào Bến Tàu Thợ để tuyển thủy thủ.",
  "building.constructionyard": "Công Trường Xây Dựng",
  "building.constructionyard.desc": "Đội trưởng công trình điều phối xe kéo và dụng cụ để thi công nhanh các công trình lân cận.",
  "problem.idleyard": "Công Trường Đang Nhàn Rỗi",
  "problem.idleyard.desc": "Công trường không có dự án xây dựng nào trong phạm vi hoạt động.",
  "logistics.allowOverflow.desc": "Nếu băng tải dưới bị tắc nghẽn, cho phép hàng hóa tràn tiếp sang băng chuyền trên.",
  "problem.noMineCart": "Không Có Xe Trên Đường Ray",

  # Maritime Docks & War
  "building.navalFishingDock": "Bến Tàu Đánh Cá Xa Bờ",
  "building.navalFishingDock.desc": "Chỉ định tàu và thủy thủ đoàn thực hiện các chuyến hải trình đánh bắt cá ngoài biển sâu.",
  "building.navaltradedock": "Bến Thương Thuyền Ngầm",
  "building.navaltradedock.desc": "Tổ chức tàu buôn lậu lén lút xuất khẩu hàng hóa cho các đối tác sẵn lòng mua.",
  "building.navalwardock": "Bến Chiến Hạm Hải Quân",
  "building.navalwardock.desc": "Trang bị đại bác và tuyển mộ thủy thủ cho chiến hạm để hải chiến và oanh tạc đảo đối phương.",
  "building.navalhuntingdock": "Bến Tàu Săn Thủy Quái",
  "building.navalhuntingdock.desc": "Trang bị cho tàu ra khơi săn Leviathan – chuyến đi đầy nguy hiểm nhưng chiến lợi phẩm cực kỳ giá trị.",
  "building.navalguanodock": "Bến Thu Gom Phân Chim Biển",
  "building.navalguanodock.desc": "Trang bị cho tàu đến các hải đảo xa xôi thu gom phân chim biển giàu dinh dưỡng làm phân bón.",
  "building.largeshipyard": "Xưởng Đóng Tàu Lớn",
  "building.largeshipyard.desc": "Xưởng đóng tàu quy mô lớn có thể đóng các loại chiến hạm vượt biển hạng nặng.",
  "building.giantshipyard": "Xưởng Đóng Tàu Hoàng Gia",
  "building.giantshipyard.desc": "Ụ tàu khổng lồ chuyên đóng các kỳ hạm đại dương hùng vĩ.\n\nTàu đóng xong phải gán vào Bến Tàu Thợ để điều động thủy thủ.",
  "problem.noPathToSea": "Bến Cảng Không Thông Ra Biển Lớn",
  "building.defensivetower": "Tháp Pháo Phòng Thủ",
  "building.defensivetower.desc": "Tháp canh kiên cố có thể nã đạn đại bác vào tàu địch dám mon men lại gần.",
  "problem.colonyInCombat": "Đại Bác Vang Rền Gần Làng Ta!",
  "problem.colonyInCombat.desc": "Bà con chuột được phân công phòng thủ sẽ túc trực chiến đấu cho đến khi dứt tiếng súng.",
  "building.brickdec_wall": "Tường Gạch Đỏ",
  "building.brickdec_wall.desc": "Tường gạch dày dặn viền đá trắng phía trên.",
  "building.brickdecor": "Bồn Cây Bằng Gạch",
  "building.brickDecordesc": "Các loại bồn hoa xây bằng gạch với thiết kế giật cấp nhiều tầng.",
  "building.nauticalRaftDock": "Bến Phà Đảo",
  "building.nauticalRaftDock.desc": "Chỉ định tàu chở bà con chuột qua lại nhanh chóng giữa các bến cảng trên đảo.",
  "building.questRepairDock": "Bến Sửa Chữa Dã Chiến",
  "building.questRepairDock.desc": "Bến cảng dã chiến nơi các chú chuột sửa chữa con tàu bị mắc kẹt.",
  "logistics.dropoffLogisticsHint": "Xe kéo hậu cần sẽ tránh các điểm xả hàng trừ khi được cài đặt dọn rỗng",
  "building.storageDock": "Bến Neo Đậu Dự Bị",
  "building.desc.storageDock": "Bến neo đậu đơn giản để bảo quản tàu thuyền khi chưa dùng đến.",
  "building.scoutDock": "Bến Tàu Thám Hiểm",
  "building.scoutDock.desc": "Trang bị tàu và thủy thủ đoàn để giong buồm khám phá hải đồ và các vùng biển bí ẩn.\n\nCác bến cảng khác có thể trang bị tàu cho những nhiệm vụ đặc thù hơn."
}

def apply():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        entries = json.load(f)

    applied = 0
    missing = []

    for entry in entries:
        key = entry["key"]
        if key in T:
            entry["target_vi"] = T[key]
            applied += 1
        else:
            missing.append((key, entry["source_en"]))

    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(entries, f, ensure_ascii=False, indent=2)

    print(f"Applied translation to {applied} / {len(entries)} items in Phase 2!")
    if missing:
        print(f"Missing {len(missing)} keys:")
        for k, s in missing[:10]:
            print(f"  - {k}: {s}")
    else:
        print("All 409 Phase 2 items translated 100%!")

if __name__ == "__main__":
    apply()
