import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(PROJECT_ROOT, "translations", "04_Mice_Traits_Thoughts.json")

T = {
  # 1. Guilds (Bang Hội Nhà Chuột)
  "guild.miners": "Hội Thợ Mỏ",
  "guild.engineers": "Hội Thợ Máy",
  "guild.farmers": "Hội Nông Dân",
  "guild.explorers": "Hội Thám Hiểm",
  "guild.miners.desc": "Những chú chuột đồng vạm vỡ lành nghề đào mỏ & luyện kim.",
  "guild.engineers.desc": "Những thợ cơ khí và nghệ nhân năng suất vượt trội.",
  "guild.farmers.desc": "Những chuyên gia trồng trọt và nghệ thuật ẩm thực.",
  "guild.explorers.desc": "Những chú chuột rừng tò mò, say mê khám phá hoang dã.",
  "guild.favoritefood": "Món Khoái Khẩu",

  # 2. Thoughts (Tâm trạng & Suy nghĩ của bầy chuột)
  "thought.food_somevariety": "Bữa Ăn Đổi Vị",
  "thought.desc.food_somevariety": "Hôm nay được ăn 2 món khác nhau",
  "thought.food_highvariety": "Bữa Ăn Phong Phú",
  "thought.desc.food_highvariety": "Hôm nay được ăn 3 món khác nhau",
  "thought.rawFoodComplaint": "Phải Ăn Đồ Sống",
  "thought.desc.rawFoodComplaint": "Phải gặm đồ sống đúng là nỗi sỉ nhục đối với Hội Nông Dân!",
  "thought.hunger": "Bụng Đói Cồn Cào",
  "thought.desc.hunger": "Hôm nay chẳng kiếm được miếng ăn nào vào bụng!",
  "thought.cold": "Chân Lạnh Buốt",
  "thought.desc.cold": "Phải chịu đựng cái rét buốt giá",
  "thought.freezing": "Tê Cóng Cắt Da",
  "thought.desc.freezing": "Chịu đựng cái rét thấu xương đe dọa tính mạng",
  "thought.newArrival": "Chuột Mới Đến",
  "thought.desc.newArrival": "Bé chuột mới chân ướt chân ráo tới thuộc địa, lòng đầy niềm lạc quan phơi phới",
  "thought.sleep_tier0": "Chỗ Ngủ Tồi Tàn",
  "thought.desc.sleep_tier0": "Phải ngủ trong một nơi khó mà gọi là một mái nhà",
  "thought.sleep_tier1": "Nhà Ở Tạm Ổn",
  "thought.desc.sleep_tier1": "Một giấc ngủ ngon khép lại ngày dài",
  "thought.sleep_tier2": "Nhà Ở Ấm Cúng",
  "thought.desc.sleep_tier2": "Một giấc ngủ ngon khép lại ngày dài",
  "thought.sleep_tier3": "Nhà Ở Xa Hoa",
  "thought.desc.sleep_tier3": "Một giấc ngủ ngon khép lại ngày dài",
  "thought.luxury.furniture": "Nhà Đủ Bàn Ghế",
  "thought.desc.luxury.furniture": "Tổ ấm được trang bị bàn ghế tươm tất",
  "thought.luxury.bedding": "Chăn Ấm Đệm Êm",
  "thought.desc.luxury.bedding": "Tổ ấm có sẵn chăn ấm đệm êm",
  "thought.missedBedtime": "Ngủ Ngoài Trời",
  "thought.desc.missedBedtime": "Không về kịp nhà trước giờ ngủ — hoặc chẳng có nhà để về",
  "thought.sleepwithsnorer": "Ngủ Không Ngon Giấc",
  "thought.desc.sleepwithsnorer": "Mất ngủ vì chung phòng với chú chuột ngáy như sấm",
  "thought.eatExperience_ateAtWarehouse": "Ăn Vội Trong Kho",
  "thought.desc.eatExperience_ateAtWarehouse": "Ăn uống chẳng chút tươm tất — đến cái ghế ngồi cũng không có!",
  "thought.eatExperience_drankAtWarehouse": "Uống Trà Trong Kho",
  "thought.desc.eatExperience_drankAtWarehouse": "Thưởng trà là phải ở quán xá đàng hoàng mới đúng điệu",
  "thought.eatExperience_ateAtEatery": "Ghé Quán Ăn",
  "thought.desc.eatExperience_ateAtEatery": "Chỗ ngồi dễ chịu để nghỉ ngơi, ăn lót dạ hay nhâm nhi tách trà",
  "thought.eatExperience_ateAtHall": "Dự Tiệc Đại Sảnh",
  "thought.desc.eatExperience_ateAtHall": "Nơi xa hoa xứng tầm với một chú chuột thành đạt",
  "thought.grieving": "Đau Buồn",
  "thought.desc.grieving": "Một người bạn vừa mới qua đời",
  "thought.bathed": "Tắm Nước Nóng",
  "thought.desc.bathed": "Tận hưởng những phút giây thư thái tại nhà tắm hơi",
  "thought.aesthetic.beauty.tier1": "Khung Cảnh Dễ Chịu",
  "thought.desc.aesthetic.beauty.tier1": "Đi ngang qua vài luống hoa và góc trang trí nhỏ",
  "thought.aesthetic.beauty.tier2": "Khung Cảnh Tươi Đẹp",
  "thought.desc.aesthetic.beauty.tier2": "Đi ngang qua nhiều bồn hoa và cảnh quan rực rỡ",
  "thought.aesthetic.beauty.tier3": "Khung Cảnh Đẹp Say Lòng",
  "thought.desc.aesthetic.beauty.tier3": "Đi ngang qua vườn hoa và cảnh quan bạt ngàn đẹp như mơ",
  "thought.statueintimidation": "Uy Áp Tượng Đá",
  "thought.desc.statueintimidation": "Cảm thấy khiếp vía trước tượng đá Quý Tộc Mèo gần đó",
  "thought.hardlabor": "Lao Động Nặng Nhọc",
  "thought.desc.hardlabor": "Bị giao việc nặng nhọc vắt kiệt sức lực",
  "thought.lightpollution": "Khói Bụi Mờ Mịt",
  "thought.desc.lightpollution": "Đi qua khu vực nồng nặc khói bụi khó chịu",
  "thought.heavypollution": "Khói Bụi Ngạt Thở",
  "thought.desc.heavypollution": "Khó thở vì khói bụi ô nhiễm quá nặng nề",
  "thought.rudeWhisker": "Va Chạm Khó Chịu",
  "thought.desc.rudeWhisker": "Một chú chuột đi ngang càu nhàu mấy câu cực kỳ thô lỗ!",
  "thought.overtime": "Làm Thêm Giờ",
  "thought.desc.overtime": "Rõ ràng bảo làm đúng giờ hành chính mà...",
  "thought.freshclothes": "Quần Áo Sạch Sẽ",
  "thought.desc.freshclothes": "Hôm nay được diện một bộ đồ mới tinh tươm",
  "thought.unburiedFriend": "Bạn Bè Chưa An Táng",
  "thought.desc.unburiedFriend": "Thi thể người bạn nằm đó chưa được chôn cất thật xót xa...",
  "thought.discontentMonarchist": "Chuột Bảo Hoàng Bất Mãn",
  "thought.desc.discontentMonarchist": "Tín đồ trung thành của Hoàng Gia cực kỳ ghét phải làm việc công nghiệp lam lũ",
  "thought.favFood": "Món Khoái Khẩu",
  "thought.desc.favFood": "Chú chuột được ăn món khoái khẩu theo khẩu vị bang hội của mình",
  "thought.showered": "Tắm Nước Lạnh",
  "thought.desc.showered": "Tắm một gáo nước lạnh buốt cho sạch bụi đất",
  "thought.dirty": "Bộ Lông Lấm Lem",
  "thought.desc.dirty": "Cần được tắm rửa cho sạch sẽ",
  "thought.bathedOcean": "Tắm Biển",
  "thought.desc.bathedOcean": "Người thoang thoảng mùi rong biển",
  "thought.nodecor": "Cảnh Sắc Ảm Đạm",
  "thought.desc.nodecor": "Lâu lắm rồi chẳng thấy chút cảnh sắc tươi đẹp nào",
  "thought.noclothing": "Quần Áo Rách Rưới",
  "thought.desc.noclothing": "Chẳng tìm đâu ra một bộ đồ lành lặn để thay",
  "thought.earlysleep": "Đi Ngủ Sớm",
  "thought.desc.earlysleep": "Về được đến nhà trước khi đêm tàn",
  "thought.homeless": "Không Mái Nhà Che Thân",
  "thought.personalSpace": "Mất Không Gian Riêng",
  "thought.desc.personalSpace": "Chú chuột thích một mình phải ở chung nhà với kẻ khác",
  "thought.housing.disappointed": "Ngột Ngạt Chật Chội",
  "thought.housing.disappointed.desc": "Thất vọng vì chất lượng nhà ở quá tồi tàn",
  "thought.housing.elated": "Mái Ấm Như Ý",
  "thought.housing.elated.desc": "Phấn khởi vì nhà ở tiện nghi vượt ngoài mong đợi",
  "thought.food.disappointed": "Đồ Ăn Nhạt Nhẽo",
  "thought.food.disappointed.desc": "Cứ ngỡ sẽ được thưởng thức món ăn cầu kỳ hơn",
  "thought.food.elated": "Món Ngon Tuyệt Hảo",
  "thought.food.elated.desc": "Hân hoan vì món ăn ngon vượt ngoài mong đợi",
  "thought.clothing.disappointed": "Quần Áo Tồi Tàn",
  "thought.clothing.disappointed.desc": "Bất mãn vì chất lượng quần áo quá tệ",
  "thought.clothing.elated": "Áo Quần Bảnh Bao",
  "thought.clothing.elated.desc": "Phấn khích vì trang phục đẹp đẽ ngoài mong đợi",
  "thought.bathing.disappointed": "Tắm Rửa Chẳng Ra Sao",
  "thought.bathing.disappointed.desc": "Ước gì được tắm gội thoải mái hơn một chút",
  "thought.bathing.elated": "Sạch Sẽ Sảng Khoái",
  "thought.bathing.elated.desc": "Không ngờ khu tắm gội lại tiện nghi đến thế",
  "thought.dining.disappointed": "Bữa Ăn Gò Bó",
  "thought.dining.disappointed.desc": "Chỗ ăn uống không đáp ứng được mong đợi",
  "thought.dining.elated": "Thưởng Bữa Sang Trọng",
  "thought.dining.elated.desc": "Cảm thấy vô cùng hài lòng về trải nghiệm dùng bữa",
  "thought.supplies.disappointed": "Thiếu Hụt Đồ Dùng",
  "thought.supplies.disappointed.desc": "Thất vọng vì hàng xa xỉ nhận được chẳng thấm tháp vào đâu",
  "thought.supplies.elated": "Cuộc Sống Sung Túc",
  "thought.supplies.elated.desc": "Hưởng thụ hàng xa xỉ dồi dào đầy sung sướng",
  "thought.compassionateGrieving": "Tang Tóc Đau Thương",
  "thought.desc.compassionateGrieving": "Đau xót khôn nguôi trước sự ra đi gần đây của người bạn",
  "thought.rebellious": "Xúc Phạm Đức Vua",
  "thought.rebellious.desc": "Nổi trận lôi đình vì những lời lẽ bất trung phỉ báng hoàng triều",

  # 3. Traits (Đặc điểm tính cách của từng chú chuột)
  "trait.snorer": "Ngáy To",
  "trait.snorer.desc": "Làm phiền các chú chuột khác ngủ chung nhà.",
  "trait.lightEater": "Ăn Ít",
  "trait.lightEater.desc": "Mỗi bữa ăn ít hơn 1 phần thức ăn.",
  "trait.loner": "Thích Đơn Độc",
  "trait.loner.desc": "Buồn bã nếu phải làm việc hoặc ngủ chung với chuột khác.",
  "trait.loner.desc.alt": "Khó chịu khi phải chia sẻ chỗ ngủ với chuột khác",
  "trait.strongShoulders": "Đôi Vai Vạm Vỡ",
  "trait.strongShoulders.desc": "+2 sức khuân vác.",
  "trait.heavyEater": "Ăn Khỏe",
  "trait.heavyEater.desc": "Mỗi bữa ăn thêm 1 phần thức ăn.",
  "trait.swift": "Thoăn Thoắt",
  "trait.swift.desc": "+15 tốc độ di chuyển.",
  "trait.optimist": "Lạc Quan",
  "trait.optimist.desc": "Có cơ hội nhân đôi hiệu ứng của các suy nghĩ tích cực.",
  "trait.pessimist": "Bi Quan",
  "trait.pessimist.desc": "Có cơ hội nhân đôi hiệu ứng của các suy nghĩ tiêu cực.",
  "trait.sickly": "Ốm Yếu",
  "trait.sickly.desc": "Kém chống chịu trước giá rét và bệnh tật.",
  "trait.scientist": "Say Mê Nghiên Cứu",
  "trait.scientist.desc": "Tăng mạnh tốc độ làm việc khi nghiên cứu công nghệ.",
  "trait.mascochist": "Thích Khổ Hạnh",
  "trait.mascochist.desc": "Vui vẻ khi phải lao động nặng nhọc.",
  "trait.healthy": "Khỏe Khoắn",
  "trait.healthy.desc": "Chống chịu rất tốt trước bệnh tật hoặc chấn thương.",
  "trait.warmCore": "Thân Nhiệt Cao",
  "trait.warmCore.desc": "Chống chịu giá rét tốt hơn bình thường.",
  "trait.unsafe": "Thợ Bất Cẩn",
  "trait.unsafe.desc": "Làm máy móc công nghiệp hao mòn nhanh hơn.",
  "trait.rude": "Cộc Cằn",
  "trait.rude.desc": "Có cơ hội khiến những chú chuột đi ngang qua mất vui.",
  "trait.monarchist": "Bảo Hoàng",
  "trait.monarchist.desc": "Bản tính trung thành tuyệt đối với Phe Móng Vuốt.",
  "trait.nosmell": "Mũi Điếc",
  "trait.nosmell.desc": "Không bị ảnh hưởng tiêu cực bởi ô nhiễm khói bụi.",
  "trait.rebellious": "Nổi Loạn",
  "trait.rebellious.desc": "Dễ buông lời chống đối hoặc lan truyền tin đồn phản nghịch",
  "trait.diligent": "Cần Mẫn",
  "trait.diligent.desc": "Chú chuột này làm việc vô cùng chăm chỉ",
  "trait.perfectionist": "Cầu Toàn",
  "trait.perfectionist.desc": "Chú chuột này đặc biệt chú trọng sự chuẩn xác tuyệt đối",
  "trait.weak": "Yếu Ớt",
  "trait.weak.desc": "Chú chuột này không khuân vác được nhiều",
  "trait.slow": "Chậm Chạp",
  "trait.slow.desc": "Chú chuột này bước đi không được nhanh nhẹn",
  "trait.teacher": "Có Khiếu Sư Phạm",
  "trait.teacher.desc": "Chú chuột này có thể kèm cặp người khác nhanh hơn",
  "trait.mypace": "Ung Dung",
  "trait.mypace.desc": "Chú chuột này cứ túc tắc làm theo nhịp độ riêng",
  "trait.compassionate": "Giàu Tình Cảm",
  "trait.compassionate.desc": "Không đòi hỏi nhiều cho bản thân, nhưng vô cùng xót xa khi có ai qua đời",
  "trait.thoughtful": "Hay Trăn Trở",
  "trait.thoughtful.desc": "Đầu óc luôn suy nghĩ không ngừng. Dễ nảy sinh cả cảm xúc tích cực lẫn tiêu cực",
  "trait.considerate": "Bao Dung",
  "trait.considerate.desc": "Không để bụng những lời lẽ cộc cằn thô lỗ",
  "trait.inquisitive": "Ham Học Hỏi",
  "trait.inquisitive.desc": "Luôn tò mò đặt câu hỏi. Tiếp thu bài học nhanh hơn khi đến trường",
  "trait.weakknees": "Chân Yếu Tay Mềm",
  "trait.weakknees.desc": "Rất sợ lao động nặng và dễ bị chấn thương",
  "trait.nosey": "Tọc Mạch",
  "trait.nosey.desc": "Quan tâm người khác nhưng thỉnh thoảng buột miệng hỏi những câu kém duyên",
  "trait.greedy": "Đòi Hỏi Cao",
  "trait.greedy.desc": "Luôn mong đợi nhiều hơn từ cuộc sống",
  "trait.patient": "Điềm Đạm",
  "trait.patient.desc": "Chẳng hiểu sao mọi người cứ phải vội, thích thong dong ngắm hoa và tận hưởng cuộc sống",
  "trait.content": "Biết Đủ",
  "trait.content.desc": "Biết hài lòng với hoàn cảnh sống hiện tại",

  # 4. Activities (Hành vi & Trạng thái hoạt động của bầy chuột)
  "whiskerActivity.idle": "Rảnh rỗi",
  "whiskerActivity.seekFood": "Đang tìm đồ ăn",
  "whiskerActivity.seekService": "Đang tìm dịch vụ",
  "whiskerActivity.seekEquipment": "Đang lấy dụng cụ",
  "whiskerActivity.seekResource": "Đang lấy tài nguyên",
  "whiskerActivity.deliverOutput": "Đang giao sản phẩm",
  "whiskerActivity.extract": "Đang khai thác tài nguyên",
  "whiskerActivity.goWork": "Đang đi làm",
  "whiskerActivity.deliverLuxuries": "Đang phân phát hàng xa xỉ",
  "whiskerActivity.farmHarvest": "Đang thu hoạch mùa màng",
  "whiskerActivity.farmTill": "Đang xới đất đồng ruộng",
  "whiskerActivity.farmSow": "Đang gieo hạt",
  "whiskerActivity.farmFertilize": "Đang bón phân ruộng",
  "whiskerActivity.farmTillRocks": "Đang cày xới đất sỏi",
  "whiskerActivity.farm.idle": "Nghỉ tay ở nông trại",
  "whiskerActivity.constructionSupply": "Đang chuyển vật liệu thi công",
  "whiskerActivity.constructingBuilding": "Đang thi công",
  "whiskerActivity.seekHeat": "Đang tìm chỗ sưởi ấm",
  "whiskerActivity.eating": "Đang dùng bữa",
  "whiskerActivity.work.idle": "Chưa có việc gì làm",
  "whiskerActivity.home": "Đang ngủ ở nhà",
  "whiskerActivity.jobticket.nojobs": "Rảnh rỗi - Không có yêu cầu",
  "whiskerActivity.jobticket.fulfilling": "Đang đáp ứng yêu cầu",
  "whiskerActivity.service.bathing": "Đang tắm gội",
  "whiskerActivity.service.healing": "Đang điều trị y tế",
  "whiskerActivity.service.drinking": "Đang uống nước",
  "whiskerActivity.logistics.idle": "Không có hàng để chở",
  "whiskerActivity.genericWork": "Đang làm việc",
  "whiskerActivity.genericRelaxing": "Đang nghỉ ngơi",
  "whiskerActivity.workplace.idle": "Rảnh tay tại xưởng",
  "whiskerActivity.replacingMachinery": "Đang thay thế máy móc",
  "whiskerActivity.replacingCatalyst": "Đang thu gom chất xúc tác",
  "whiskerActivity.doctor.patients": "Đang chăm sóc bệnh nhân",
  "whiskerActivity.seekClothing": "Đang tìm quần áo",
  "whiskerActivity.terraforming": "Đang san lấp mặt bằng",
  "whiskerActivity.adminwork": "Đang xử lý việc hành chính",
  "whiskerActivity.work.standingguard": "Đang đứng gác",

  # 5. Education & Training (Giáo dục, Đào tạo thợ & Hàng hải)
  "education.required": "Yêu Cầu Bắt Buộc",
  "education.schooled": "Đã Qua Trường Lớp",
  "education.schooled.desc": "Đã được học hành bài bản tại thuộc địa",
  "education.target": "Mục Tiêu Đào Tạo",
  "education.skilled": "Thợ Học Việc",
  "education.skilled.desc": "Thợ đã được đào tạo cơ bản, nắm vững kỹ thuật nhập môn",
  "education.educated": "Có Học Thức",
  "education.educated.desc": "Thông thạo chữ nghĩa và tính toán sổ sách",
  "education.craftsmaster": "Bậc Thầy Thủ Công",
  "education.craftsmaster.desc": "Được đào tạo toàn diện và là chuyên gia lành nghề",
  "education.craftsman": "Nghề Thủ Công",
  "education.scholar": "Ngành Học Thuật",
  "education.teaching": "Đang Giảng Dạy",
  "education.learning": "Đang Học Tập",
  "education.noteacher": "Chưa Có Giáo Viên",
  "education.assignteacher": "Phân Công Giáo Viên",
  "education.reassignteacher": "Đổi Giáo Viên",
  "education.nostudent": "Chưa Có Học Viên",
  "education.assignstudent": "Chỉ Định Học Viên",
  "education.reassignstudent": "Đổi Học Viên",
  "education.insufficient": "Chưa đạt kỹ năng yêu cầu",
  "education.sailor": "Thủy Thủ",
  "education.sailor.desc": "Được huấn luyện các nhiệm vụ cơ bản trên tàu",
  "education.officer": "Sĩ Quan Hàng Hải",
  "education.officer.desc": "Tinh thông hàng hải và kỹ nghệ định vị nâng cao",
  "education.seafaring": "Nghề Hàng Hải"
}

def apply_translation():
    with open(JSON_PATH, 'r', encoding='utf-8') as f:
        data = json.load(f)

    applied_count = 0
    missing = []
    for item in data:
        key = item.get('key')
        if key in T:
            item['target_vi'] = T[key]
            applied_count += 1
        else:
            missing.append((item['id'], key, item.get('source_en')))

    with open(JSON_PATH, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Applied translation to {applied_count} / {len(data)} items in Phase 4!")
    if missing:
        print(f"Missing {len(missing)} items:")
        for m in missing[:20]:
            print(" ", m)
    else:
        print("All 250 Phase 4 items translated 100%!")

if __name__ == "__main__":
    apply_translation()
