import json

# Phase 6C Translations: 341 items (Indices 671 to 1011, IDs 2167 to 2748)
PHASE6C_TRANSLATIONS = {
    2167: "Bật/tắt để chuột nông dân chỉ chăm sóc các mảnh ruộng ưu tiên. Khi bật, nông dân sẽ nghỉ ngơi nếu không có việc cần làm ở ruộng ưu tiên và sẽ không làm việc trên các mảnh ruộng khác.",
    2168: "Hạn Mức Sản Xuất",
    2169: "Tạm dừng sản xuất nếu lượng dự trữ trong kho vượt quá hạn mức thiết lập",
    2170: "Hạn mức sản xuất",
    2173: "Quản Lý Được Bổ Nhiệm",
    2174: "Xây dựng Văn Phòng Quản Lý để điều phối các hạn mức sản xuất",
    2177: "Mở Khóa Hạn Mức Sản Xuất",
    2178: "Mở Khóa Chính Sách",
    2183: "Kho sức chứa khổng lồ",
    2186: "Hàng Rào Cọc Gỗ",
    2187: "Hàng Rào Sắt",
    2188: "Giàn Hoa Leo",
    2189: "Bụi Cây Cảnh",
    2190: "Nến Thắp Sáng",
    2191: "Lòng Tin Của Phe Móng Vuốt",
    2192: "Mất toàn bộ lòng tin có nguy cơ dẫn tới sự trả đũa quân sự",
    2193: "Thưởng Thế Giới",
    2194: "Hiệu Lực Kéo Dài",
    2200: "Cửa Hầm Mỏ",
    2213: "Bán Kính Làm Việc",
    2214: "Chuột thợ sẽ chỉ tìm kiếm công việc trong phạm vi này.\n\nKhông áp dụng cho việc thu gom hoặc lưu trữ tài nguyên.",
    2215: "Băng Giá! Quá trình chữa trị tạm đình chỉ.",
    2216: "Quá lạnh để vận hành!",
    2217: "Sẽ cho chuột bệnh xuất viện",
    2237: "Không có kho chứa liền kề",
    2240: "Tỷ Lệ Đánh Bắt Trước Giờ",
    2241: "Vùng Đón Cá",
    2242: "Trữ Lượng Cá",
    2246: "Góc Nhìn Luồng Cá",
    2249: "Trữ Lượng Cá Thấp",
    2250: "Chưa thiết lập tuyến bè!",
    2251: "Thiết lập một tuyến đường nối tới bến khác",
    2252: "Tuyến Bè Bị Chặn!",
    2253: "Tổng số bè",
    2254: "Đang hoạt động",
    2255: "Chuột đang trên biển",
    2256: "Chuột đang đợi bè",
    2257: "Thiết Lập Tuyến",
    2258: "Hủy Tuyến",
    2259: "Đóng Bè Mới",
    2260: "Tu Sửa Tuyến",
    2261: "Kho Bè",
    2262: "Tăng số lượng bè sẵn có cho tuyến này",
    2267: "Tạo Tuyến Đường",
    2268: "Kết nối với một bến thứ hai để tạo tuyến đi lại",
    2269: "Tuyến đường bị chặn",
    2270: "Khu vực cập bến bị nghẽn",
    2280: "Tường Đá",
    2284: "Đã sao chép thiết lập",
    2285: "Đã dán thiết lập",
    2286: "Không có gì để dán",
    2287: "Thiết lập dán không tương thích",
    2289: "Sao Chép Thiết Lập",
    2290: "Lưu thiết lập của công trình này vào bộ nhớ tạm",
    2292: "Dán Thiết Lập",
    2293: "Áp dụng thiết lập đã lưu vào công trình này",
    2294: "Bật khi nhiệt độ:",
    2295: "Mưa Ướt Sũng",
    2296: "Bị chậm lại do mưa như trút nước mà không có mái che",
    2301: "Chuột thợ chở vật tư và thi công các công trình trong phạm vi một cách hiệu quả",
    2302: "Chuột Thợ Xưởng Xây Dựng",
    2303: "Tốc độ xây dựng cải thiện nhờ có cai thầu điều phối",
    2308: "Bồi Hoàn Phí Đạn Pháo",
    2309: "Độ Bền Vật Liệu",
    2310: "Cấp độ sức công phá có thể chống chịu",
    2311: "Sức Công Phá",
    2312: "Mệnh Lệnh",
    2327: "Bậc Nghiên Cứu Cơ Bản",
    2345: "Thủy Thủ Đoàn Hiện Diện",
    2346: "Lòng Dũng Cảm",
    2350: "Lênh Đênh Trên Biển",
    2351: "Nghỉ Ngơi Tại Bến",
    2384: "Danh Mục Kiểm Tra Xuất Bến",
    2385: "Chưa Phân Công Tàu",
    2386: "Đóng tàu tại Xưởng Đóng Tàu và phân công về đây",
    2390: "Đang Chờ Tiếp Tế",
    2391: "Cần Sửa Chữa",
    2392: "Tàu Đang Rời Bến",
    2393: "Tàu Bị Đánh Chìm!",
    2394: "Thuyền cứu sinh đang chở những chú chuột sống sót quay về",
    2400: "Thủy Thủ",
    2401: "Sĩ Quan",
    2402: "Tàu WSS Ngày Tươi Sáng",
    2403: "Tàu WSS Đồng Lòng",
    2404: "Tàu WSS Trợ Thủ Biển Khơi",
    2405: "Tàu WSS Hy Vọng Đại Dương",
    2406: "Tàu WSS Cánh Đồng Xanh",
    2407: "Tàu WSS Mùa Gặt",
    2408: "Tàu WSS Thời Cơ Thuận Lợi",
    2409: "Tàu WSS Hoàn Hảo",
    2410: "Tàu WSS Lễ Hội",
    2411: "Tàu WSS Trời Quang",
    2412: "Tàu WSS Gió Lộng",
    2413: "Tàu WSS Nắng Ấm",
    2414: "Tàu WSS Hoan Ca",
    2415: "Tàu WSS Niềm Vui",
    2416: "Tàu WSS Nồng Ấm",
    2417: "Tàu WSS Chim Di Trú",
    2418: "Tàu WSS Khúc Họa Mi",
    2419: "Tàu WSS Rạng Rỡ",
    2420: "Tàu WSS May Mắn",
    2421: "Tàu WSS Vui Vẻ",
    2422: "Tàu WSS Hân Hoan",
    2423: "Tàu Kinh Hoàng",
    2424: "Tàu Hắc Ám",
    2425: "Tàu Cánh Buồm Đen",
    2426: "Tàu Trảm Vương",
    2427: "Tàu Cướp Đoạt",
    2428: "Tàu Bất Công",
    2429: "Tàu Vô Tội",
    2430: "Tàu Trơ Trẽn",
    2431: "Tàu Tự Do",
    2432: "Tàu Phá Xiềng Xích",
    2433: "Tàu Robin Hood",
    2434: "Tàu Đáng Sợ",
    2435: "Tàu Khiếp Đảm",
    2436: "Tàu Ác Mộng",
    2437: "Tàu Phán Quyết",
    2438: "Tàu Cơ Cực",
    2439: "Tàu Trơ Tráo",
    2440: "Tàu Háu Đói",
    2441: "Tàu Đoạt Mệnh",
    2442: "Tàu Tham Lam",
    2443: "Tàu Tàn Khốc",
    2444: "Tàu RN Thiện Xạ",
    2445: "Tàu RN Trung Kiên",
    2446: "Tàu RN Quý Tộc",
    2447: "Tàu RN Khải Hoàn",
    2448: "Tàu RN Hiên Ngang",
    2449: "Tàu RN Trung Thành",
    2450: "Tàu RN Vinh Quang",
    2451: "Tàu RN Quả Cảm",
    2452: "Tàu RN Lộng Lẫy",
    2453: "Tàu RN Thượng Lưu",
    2454: "Tàu RN Dũng Cảm",
    2455: "Tàu RN Dự Bị",
    2456: "Tàu RN Trụ Cột",
    2457: "Tàu RN Uy Quyền",
    2458: "Tàu RN Hoàng Gia",
    2459: "Tàu RN Tận Trung",
    2460: "Tàu RN Bền Bỉ",
    2461: "Tàu RN Kiên Cường",
    2462: "Tàu RN Can Trường",
    2463: "Tàu RN Táo Bạo",
    2464: "Tàu RN Gan Dạ",
    2465: "Buôn Bán Tấp Nập",
    2466: "Lợi Nhuận Kếch Xù",
    2467: "Chuyến Hàng Đắt Khách",
    2468: "Tàu Phú Quý",
    2469: "Tàu Thương Nhân Số 2",
    2470: "Hái Ra Tiền",
    2471: "Công Ty Đầy Vàng",
    2472: "Ngài Lắm Của",
    2473: "Chữ Tín Đáng Giá",
    2474: "Công Ty Thương Tín",
    2475: "Chồn & Bạn Hữu",
    2476: "Công Ty Thương Mại 77",
    2477: "Công Ty Acme",
    2478: "Thương Mại Acme",
    2479: "Công Ty Mậu Dịch Acme",
    2480: "Cồn Rượu Acme",
    2481: "Acme Đệ Nhất",
    2482: "Acme & Bạn Hữu",
    2483: "Gia Tộc Chồn",
    2484: "Kẻ Định Giá",
    2485: "Ngài Lươn Lẹo",
    2486: "Thuyền Cứu Sinh",
    2487: "Yêu Cầu Tàu Đi Biển",
    2488: "Chống Đạn Đại Bác",
    2489: "Thuyền đánh cá nhỏ",
    2490: "Tàu đánh cá hạng trung",
    2491: "Tàu đánh cá cỡ lớn",
    2492: "Tàu trinh sát nhỏ",
    2493: "Tàu chiến hạng trung",
    2494: "Đại chiến hạm",
    2495: "Tàu buôn lậu nhỏ",
    2496: "Tàu buôn hạng trung",
    2497: "Xà lan buôn cỡ lớn",
    2498: "Thuyền cứu sinh",
    2501: "Đánh Bắt Cá",
    2502: "Săn Thủy Quái",
    2503: "Giao Thương",
    2504: "Thám Hiểm",
    2505: "Hải Chiến",
    2506: "Trục Vớt Cứu Hộ",
    2507: "Khai Thác Phân Chim",
    2529: "Sự Cố Khẩn Cấp!",
    2530: "Các tàu ghé thăm không thể tiếp cận bến cảng của bạn!",
    2531: "Không có luồng lạch nào thông suốt giữa bến cảng và biển khơi. Hãy cân nhắc di dời bến cảng hoặc phá dỡ các công trình chắn lối đi.",
    2532: "Phe Móng Vuốt sẽ không nương tay nếu tàu thuyền của họ bị cản trở!",
    2533: "Không có lối ra biển!",
    2534: "Sẵn sàng khởi hành!",
    2543: "Hàng Hải",
    2544: "Sát Thương",
    2545: "Độ Bền Công Trình",
    2546: "Mức sát thương công trình này có thể gánh chịu trước khi bị phá hủy",
    2547: "Hết Đạn Đại Bác",
    2548: "Chuột thợ sẽ nạp loại đạn đại bác tốt nhất hiện có",
    2549: "Sẵn Sàng Khai Hỏa",
    2550: "Đang Nạp Đạn",
    2553: "Tấn Công Hải Tặc",
    2554: "Mọi công trình phòng thủ sẽ tự động nã pháo vào tàu hải tặc. Hải tặc rất có thể sẽ leo thang xung đột!",
    2562: "Bản Vẽ Thiết Kế Chưa Rõ",
    2563: "Công nghệ được Phe Móng Vuốt canh giữ cẩn mật",
    2564: "Thuyền Đánh Cá Nhỏ",
    2565: "Tàu đi biển cỡ nhỏ có khả năng vươn ra đại dương",
    2566: "Chiến Thuyền Của Stormie",
    2567: "Tàu đi biển cỡ nhỏ có khả năng vươn ra đại dương",
    2568: "Thuyền Buồm Trinh Sát Nhỏ",
    2569: "Thuyền Buồm Tác Chiến Nhỏ",
    2570: "Tàu Đa Dụng Hạng Trung",
    2571: "Tàu Chở Hàng Hạng Trung",
    2572: "Tàu Chiến Hạng Trung",
    2573: "Đại Tàu Đa Năng",
    2574: "Đại Tàu Vận Tải",
    2575: "Đại Chiến Hạm Bọc Thép",
    2576: "Tàu Đang Bị Tấn Công!",
    2577: "Một con tàu đang bị nã pháo tấn công!",
    2578: "Sẵn Sàng Giao Thương",
    2579: "Một con tàu đã cập bến đích và đang chờ trao đổi hàng hóa",
    2580: "Thủy Thủ Đói Lả!",
    2581: "Một con tàu đã cạn sạch lương thực, thủy thủ đoàn đang chết đói!",
    2582: "Chuẩn Bị",
    2589: "Thông Báo Hạm Đội",
    2590: "Bãi Đá Phân Chim",
    2591: "Ngư Trường",
    2592: "Ổ Thủy Quái",
    2593: "Xác Tàu Đắm",
    2597: "Có tiếng đại bác gần thuộc địa!",
    2600: "Báo Động Đỏ",
    2601: "Mất tích ngoài biển khơi",
    2602: "Chuột tử nạn chờ an táng",
    2603: "Dự trữ lương thực",
    2604: "Đạn dược",
    2607: "Tường Gạch Trang Trí",
    2610: "Kéo Để Xây",
    2611: "Tàu Phân Công",
    2614: "Tàu đang chắn cửa xuất hàng",
    2618: "Hối lộ Hải Tặc để lấy bản vẽ",
    2620: "Sửa chữa <0>",
    2621: "Thoát bản đồ hải quân",
    2622: "Bản đồ hải quân",
    2627: "Cứu Hộ Sửa Thuyền",
    2628: "Con tàu của tôi đã hư hại vượt quá khả năng sửa chữa rồi!\n\nKhông có ai cứu giúp, tôi thật chẳng dám tưởng tượng chuyện gì sẽ xảy ra giữa đại dương bao la này.\n\nTrưởng Làng là một bậc nghĩa hiệp, phải không? Xin hãy cứu giúp một đồng loại chuột hoạn nạn! Tôi khẩn cầu bằng tấm lòng hảo tâm của Trưởng Làng!\n\nNếu Trưởng Làng cứu tôi thoát khỏi cảnh ngặt nghèo này, tôi xin lấy danh dự thề rằng một ngày nào đó sẽ đền đáp ân tình! Rồi Trưởng Làng sẽ thấy!",
    2629: "Tàu Bè, Thêm Nhiều Tàu Bè Nữa!",
    2630: "Xin thứ lỗi cho tôi.\nTôi biết mình không có phận sự lên tiếng, nhưng Trưởng Làng nhất định phải đóng thêm tàu bè!\n\n\nPhe Móng Vuốt nắm giữ một hạm đội khổng lồ, và nếu chúng ta muốn thoát khỏi móng vuốt nhơ bẩn của chúng, chúng ta phải lớn mạnh ngang tầm!\n\n\nCàng nhiều tàu bè đồng nghĩa với càng nhiều tự do. Chẳng phải điều đó quá tuyệt vời sao?\n\n\nDĩ nhiên, một thủy thủ hèn mọn như tôi đâu dám chỉ tay năm ngón bảo một thủ lĩnh vĩ đại như Trưởng Làng phải xây dựng thứ gì. Tôi tin chắc Trưởng Làng sẽ tự đưa ra quyết định đúng đắn nhất.",
    2631: "Kìa Xưởng Đóng Tàu!",
    2632: "Tôi có tin này cho Trưởng Làng, nhưng có thể Trưởng Làng sẽ không thích nghe đâu.\n\nKhi ngẫm nghĩ về tình cảnh của chúng ta, tôi nhận ra chúng ta cần một chút \"đòn bẩy\" trong kỹ nghệ đóng tàu.\n\nVà tôi tự nhủ, \"ai thạo sóng gió biển khơi hơn lũ hải tặc chứ\"?\n\nThế là tôi đã mạo hiểm ra khơi, kể cho đám hải tặc nghe về hòn đảo của chúng ta, và dàn xếp được một thỏa thuận với chúng!\n\nTôi biết hầu hết bầy chuột chẳng bao giờ thèm đàm phán với những kẻ \"thủy thủ mang tiếng xấu\" như thế, nhưng xin Trưởng Làng đừng nổi giận! Hãy nghe tôi giãi bày. Rốt cuộc thì tất cả cũng vì tương lai thuộc địa thôi mà.\n\nĐám hải tặc đã đồng ý chia sẻ cho chúng ta bí quyết xây dựng Xưởng Đóng Tàu! Và tất cả những gì chúng đòi hỏi chỉ là năm thỏi vàng còm cõi!\n\nDĩ nhiên, tôi đâu muốn Trưởng Làng nghĩ tôi là loại chuột cơ hội không biết chia sẻ gánh nặng! Khi nào Trưởng Làng gom đủ vàng trả cho hải tặc, tôi sẽ tự trích một thỏi vàng từ hòm giấu của riêng mình để góp cùng.",
    2633: "Dưới Ách Kìm Kẹp Của Hải Tặc",
    2634: "Đa tạ lòng tốt đã đáp ứng yêu sách của chúng ta. Sự hào phóng của các ngươi sẽ cho phép chúng ta bành trướng sang các hòn đảo mới. Những “Đảo Hải Tặc” mới. Nghe oai phong đấy chứ!\n\nCác ngươi đã biết điều như vậy, chúng ta cũng muốn đáp lễ! Nếu các ngươi tìm thấy một thuộc địa Chuột khác và thề sẽ báo tin cho chúng ta, ta sẽ bảo đảm các băng hải tặc khác không quấy rầy hòn đảo của các ngươi trong một thời gian. Lời của ta đáng giá ngàn vàng!\n\nVà biết đâu đấy? Có khi các ngươi còn tìm thấy vài hòn đảo hoang để chúng ta biến thành nhiều Đảo Hải Tặc hơn nữa! Chia sẻ cùng nhau thấy vui phết, đúng không nào?",
    2635: "Báo Ân Bằng Phản Bội",
    2636: "Gửi lời cảm ơn chân thành của tôi đến toàn thể thuộc địa vì đã đóng xong con tàu tuyệt mỹ này. Con thuyền cũ rách ngày trước mà Trưởng Làng vớt tôi lên sẽ chẳng bao giờ làm nên đại sự! Tôi xin phép lấy con tàu này. Cứ coi như đây là khoản đóng góp đầu tiên của Trưởng Làng cho đại nghĩa tự do!\n\nQuá lâu rồi, giống loài chuột chúng ta phải oằn mình làm nô lệ dưới sự áp bức của Phe Móng Vuốt! Mòn mỏi chờ đợi ngày này, khi một chú chuột đủ quả cảm để phất cờ khởi nghĩa dám đưa ra lựa chọn mà những kẻ hèn nhát lẩn tránh. Như đã hứa khi chúng ta tương ngộ, giờ tôi đã giữ trọn lời thề và đền đáp ân tình của Trưởng Làng.\n\nHãy ghi nhớ ngày này! Hãy kể lại cho đàn con cháu của bà con. Kể cho chúng nghe bà con đã có mặt ở đây khi Stormie rời cảng và châm ngòi cho Cuộc Khởi Nghĩa Của Loài Chuột!",
    2637: "Nhiệm Vụ Hải Tặc",
    2638: "Chúng ta đang tìm cách mở rộng mạng lưới quyên góp. Nếu ngươi biết bất kỳ thuộc địa Chuột nào muốn ủng hộ đại sự của chúng ta, đó sẽ là sự trợ giúp tuyệt vời.",
    2639: "Nếu ngươi hợp tác, chúng ta hứa sẽ bảo vệ thuộc địa của ngươi khỏi các băng hải tặc khác trong 8 ngày.",
    2640: "Chúng ta luôn săn lùng các tài liệu mật. Đây là một mẩu giấy da. Nếu ngươi chia sẻ một bản vẽ thiết kế cho chúng ta, chúng ta sẽ đội ơn vô cùng!",
    2641: "Dĩ nhiên chúng ta rất trân trọng lòng hào phóng ấy. Đổi lại, đích thân ta sẽ bảo lãnh cho thuộc địa của ngươi trước các băng hải tặc khác. Ngươi sẽ được an toàn trong 13 ngày.",
    2642: "Sau những chiến tích lẫy lừng trước Phe Móng Vuốt và nhờ sự hào phóng của các thuộc địa Chuột như các ngươi, chúng ta đang cần một hòn đảo để mở rộng căn cứ hoạt động. Ngươi có biết hòn đảo hoang nào không?",
    2643: "Nếu ngươi làm tròn phần việc của mình, chúng ta sẽ coi đó là một ân huệ và bảo hộ thuộc địa của ngươi trong 8 ngày.",
    2644: "Một cuộc chạm trán ác liệt với lũ Mèo bướng bỉnh đã đẩy chúng ta vào thế kẹt. Liệu chúng ta có thể xin ít vật tư sửa tàu để bù đắp cho những thiệt hại do đám chủ nhân Mèo của ngươi gây ra không?",
    2645: "Bằng lòng hảo tâm của mình, ta sẽ ban cho ngươi sự bảo hộ trong 5 ngày. Tức là không có chuyến ghé thăm nào từ chúng ta hay đồng bọn.",
    2646: "Chúng ta đang chiêu mộ thuyền viên! Miễn là ngươi không phải là một con Mèo Móng Vuốt, luôn có chỗ cho ngươi trong thủy thủ đoàn của chúng ta. Mọi chú chuột lành nghề, khỏe mạnh và quen sóng nước đều được chào đón gia nhập. Đổi lại, ngươi sẽ nhận được phần chia chiến lợi phẩm cùng chỗ ăn ở chu đáo!",
    2647: "Những gì chúng ta trao cho ngươi là 21 ngày bảo hộ. Lấy danh dự thề, không tên hải tặc nào dám bén mảng quấy rầy ngươi khi ngươi đang dưới sự che chở của chúng ta.",
    2648: "Chỉ Dụ Hoàng Gia Trưng Cầu Tiếp Viện",
    2649: "Những tin đồn thất thiệt về hành vi bạo loạn của một con chuột lầm đường lạc lối cần phải bị phớt lờ bằng mọi giá. Những lời xầm xì sai sự thật ấy có nguy cơ làm giảm năng suất của những chú chuột thợ chân chính và thổi bùng ngọn lửa phản nghịch.\n\nNhững lời đồn đại này đầy rẫy sự dối trá về việc tàu bè bị đánh chìm và các hòm thuế bị cướp phá. Ngươi cần biết rằng chưa từng có tàu tiếp tế nào bị đắm và chẳng có đồng thuế nào bị cướp cả. Hoạt động hải tặc đã bị tiêu diệt gần hết, và hạm đội của chúng đã nằm dưới đáy biển sâu.\n\nĐể duy trì hòa bình và trấn an toàn thể loài chuột về sự an toàn của những cống vật mà các ngươi đã nộp, các tàu chiến tuần tra bổ sung đã được triển khai. Nhằm giữ vững tiến độ tu bổ hạm đội, chúng ta cho phép nộp Đinh Sắt, Đồ Hộp và Vải Buồm thay cho thuế cống nạp. Để bù đắp cho sự nhân từ này, mức thuế tính trên mỗi đầu chuột sẽ được tăng lên.",
    2650: "Tin Tức Về Stormie",
    2651: "Tin vui gửi tới tất cả những ai tận trung với Đức Vua! Tên phản loạn ngu xuẩn Stormie đã bị đền tội. Trò hề tà ác của hắn đã chấm dứt cùng với sinh mạng của hắn.\n\nGiờ đây khi thuộc địa của ngươi đã thoát khỏi bóng ma bạo ngược của Stormie, chúng ta yêu cầu các ngươi quyên góp để ban thưởng cho các chiến binh Mèo Móng Vuốt dũng cảm đã bắt sống hắn. Một vài Thỏi Vàng là mức cống nộp thỏa đáng.\n\nTái bút: Để ăn mừng chiến công, bộ nha quyết định ban tặng bản vẽ Đại Bác cho thuộc địa của ngươi. Hãy sẵn sàng cho những yêu cầu viện trợ tiếp theo khi chúng ta đưa Cuộc Chiến Hải Tặc này đến hồi kết nhanh chóng với tổn thất sinh mạng tối thiểu cho loài Mèo.",
    2652: "Nhiệm Vụ Của Đức Vua",
    2653: "Sau khi hoàn thành chỉ dụ này, thuộc địa của ngươi sẽ được ban tặng 1 Thư Tiến Cử Hoàng Gia.",
    2654: "Tốt hơn hết thuộc địa của ngươi nên dùng những khẩu đại bác đó cho đúng việc. Hãy tìm và bắn chìm cho chúng ta một chiến thuyền Hải Tặc.",
    2655: "Lũ Hải Tặc đang lẩn trốn trên một hòn đảo chưa có trên hải đồ. Đây là mệnh lệnh chính thức yêu cầu ngươi thám hiểm đại dương và xác định sào huyệt của chúng.",
    2656: "Nhiều báo cáo chỉ ra rằng lũ buôn lậu đang lộng hành và phá hoại chính sách giao thương của chúng ta. Hãy giáng một đòn vào túi tiền của chúng và bắn chìm một tàu buôn lậu cho chúng ta.",
    2657: "Quý Tộc Móng Vuốt chúng ta không thể một mình gánh chịu toàn bộ gánh nặng của Cuộc Chiến Hải Tặc này. Hãy xem đây là lời triệu tập ngươi đứng lên tiêu diệt 1 Đảo Hải Tặc. Quét sạch toàn bộ hệ thống phòng thủ và nã pháo san phẳng mọi bến tàu của chúng thành bình địa. Không có bến tàu, lũ Hải Tặc sẽ không thể đóng lại chiến thuyền.",
    2658: "Thuộc địa của ngươi xem chừng khá cần mẫn làm ăn. Đã đến lúc các ngươi phải đóng góp phần nghĩa vụ sòng phẳng của mình.",
    2659: "Lời Hứa Về Tự Do",
    2660: "Chỉ còn lại một Đảo Hải Tặc gai góc duy nhất. Nhưng hãy cẩn trọng. Lũ hải tặc này đã cùng đường và tăng cường gấp đôi lực lượng phòng thủ.\n\nNếu ngươi giao chiến với chúng trong một trận chiến kéo dài, ta e rằng tổn thất của các ngươi sẽ rất nặng nề. Rất may, chúng ta không phải không có giải pháp.\n\nĐể hỗ trợ cho trận đánh của ngươi, ta đã phê chuẩn việc chuyển giao Bản Vẽ Đạn Pháo Sắt. Loại đạn pháo sắt này sở hữu sức xuyên phá vượt trội trước các tháp phòng thủ nhưng quy trình chế tạo phức tạp hơn nhiều.\n\nMột khi ngươi dọn sạch hòn đảo cuối cùng này và chấm dứt vĩnh viễn Cuộc Chiến Hải Tặc, ta đã được ủy quyền đề cử thuộc địa của ngươi nhận Phần Thưởng Của Đức Vua.\n\nThông thường một phần thưởng như thế sẽ phong tước vị quý tộc, nhưng đối với loài Chuột các ngươi, các ngươi sẽ nhận được nền Độc Lập Tự Chủ.\n\nGiờ đây, ngươi phải kiên nhẫn. Nếu được ban thưởng, các ngươi sẽ là những cư dân Chuột đầu tiên trong lịch sử nhận được vinh dự to lớn dường ấy. Nhưng điều đó hoàn toàn xứng đáng. Các thủy thủ của ngươi đã chiến đấu ngoan cường và thuộc địa của ngươi đã trả giá bằng máu và mạng sống. Ta lấy làm vinh hạnh được kề vai sát cánh chiến đấu cùng ngươi.",
    2661: "KẾT THÚC HỒI II",
    2662: "Tin tức về chiến thắng vang dội của ngươi đã truyền đến tai ta! Thật là một kỳ tích huy hoàng!\n\nTa sẽ đệ trình thư tiến cử của ngươi lên triều đình ngay lập tức! Xin hãy kiên nhẫn chờ đợi vì toàn bộ quy trình thẩm định của hoàng gia có thể mất vài năm trời.",
    2663: "Gửi Bầy Chuột Đồng Bào,",
    2664: "Stormie\nThủy Thủ Biển Khơi",
    2665: "Kính Gửi Trưởng Làng,",
    2666: "Gửi Chú Chuột Cần Lao Của Ta,",
    2667: "Stormie\nKẻ Nổi Dậy",
    2668: "Dưới Sự Trị Vì Ân Đức Của Đức Vua,\nĐô Đốc Birman\nQuân Đoàn Tiễu Trừ Hải Tặc",
    2669: "Stormie",
    2670: "Đô Đốc Birman",
    2671: "Thư Tiến Cử Hoàng Gia",
    2672: "Một bức thư tiến cử chính thức của hoàng gia",
    2673: "Hết Hạn Sau",
    2674: "Thu thập bản vẽ thiết kế <0>",
    2675: "Công Trình Nhiệm Vụ",
    2678: "Đảo Hải Tặc Đã Tiêu Diệt",
    2679: "<0> Tàu Đã Bị Bắn Chìm",
    2680: "Khám Phá <0> Đảo",
    2681: "Hải Tặc",
    2682: "Bầy Chuột",
    2683: "Phe Móng Vuốt",
    2684: "Phe Chồn",
    2685: "Buôn Lậu",
    2686: "Bị Bỏ Hoang",
    2687: "Cảm ơn vì con tàu nhé!",
    2690: "Các loại tài nguyên mới được chấp nhận để nộp thuế",
    2691: "Xác nhận thỏa thuận đã cập nhật",
    2692: "Cần Đối Tác Giao Thương",
    2693: "Chọn một đối tác giao thương để bắt đầu bốc xếp hàng hóa trao đổi lên tàu",
    2694: "Nhu Cầu Mua",
    2695: "Mặt Hàng Bán",
    2696: "Bốc xếp hàng hóa lên tàu",
    2697: "Chưa khám phá đối tác giao thương nào!",
    2698: "Hãy thám hiểm đại dương để tìm kiếm những thương nhân sẵn lòng giao dịch",
    2699: "Hải Trình",
    2700: "Dân Số",
    2701: "Hải Tặc yêu cầu một chú chuột tình nguyện",
    2702: "Chú chuột này sẽ rời khỏi thuộc địa của bạn vĩnh viễn",
    2703: "Chưa chọn chú chuột nào",
    2704: "Cử Chuột Đi",
    2705: "Từ Chối Yêu Sách",
    2706: "Nhiệm Vụ Của Đức Vua",
    2707: "Chia Sẻ Bản Vẽ Thiết Kế",
    2709: "Hải tặc khiêm nhường yêu cầu các nhà nghiên cứu của bạn chia sẻ thành quả khoa học. Tri thức sinh ra là để tự do, phải không nào?",
    2710: "Hải Tặc Đòi Bản Vẽ Thiết Kế",
    2711: "Các Điểm Đến Hợp Lệ",
    2716: "Tàu Trinh Sát Caravel",
    2717: "Một con tàu nhanh nhẹn nhưng mỏng manh với khoang hàng hạn chế",
    2718: "Tàu Galleon Đa Năng",
    2719: "Một con tàu toàn diện với không gian rộng rãi chứa vật tư",
    2720: "Tàu Buồm Schooner Chở Hàng",
    2721: "Khoang chứa hàng rộng rãi, rất thích hợp cho giao thương buôn bán",
    2722: "Chiến Hạm Barque Vũ Trang",
    2723: "Thuyền buồm kiên cố trang bị đại bác đủ sức tham gia hải chiến",
    2724: "Xà Lan Thương Mại",
    2725: "Một con tàu chậm chạp với khoang hàng khổng lồ, rất thích hợp cho giao thương đường dài",
    2726: "Trống",
    2739: "Mỗi thủy thủ tiêu thụ 1 lương thực mỗi đêm",
    2740: "Tàu sẽ quay đầu khi lượng thức ăn giảm còn một nửa",
    2741: "Lệnh Khi Rời Cảng:",
    2742: "Đánh bắt tại Ngư Trường gần nhất còn cá",
    2743: "Thu gom tại Bãi Đá Phân Chim gần nhất còn tài nguyên",
    2744: "Giao thương với <0>",
    2745: "Rời cảng và chờ chỉ thị",
    2748: "Mua bản vẽ thiết kế <0> từ Hải Tặc ghé thăm"
}

def apply_phase6c():
    with open('translations/06_Quests_Events_Story.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    applied_count = 0
    missing_ids = []

    # Process items in range [671, len(data))
    for idx in range(671, len(data)):
        item = data[idx]
        item_id = item['id']
        if item_id in PHASE6C_TRANSLATIONS:
            item['target_vi'] = PHASE6C_TRANSLATIONS[item_id]
            applied_count += 1
        else:
            missing_ids.append((idx, item_id, item['key']))

    with open('translations/06_Quests_Events_Story.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Applied translation to {applied_count} / {len(data) - 671} items in Phase 6C!")
    if missing_ids:
        print(f"Missing translations for {len(missing_ids)} items: {missing_ids[:5]}...")
    else:
        print("All 341 Phase 6C items translated 100%!")

if __name__ == '__main__':
    apply_phase6c()
