import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(PROJECT_ROOT, "translations", "05_Nautical_Exploration_World.json")

T = {
  # 1. Embark & World Parameters (35 items)
  "embark.scenariosTitle": "Kịch Bản",
  "embark.scenario": "Kịch Bản",
  "embark.presetTitle": "Mức Độ Khó",
  "embark.preset1": "Thư Thái",
  "embark.preset2": "Tiêu Chuẩn",
  "embark.preset3": "Thử Thách",
  "embark.preset4": "Khốc Liệt",

  "embark.scenario1": "Tín Đồ Bảo Hoàng",
  "embark.scenario1.desc": "Phe Móng Vuốt sẽ cử chủ yếu là những chú chuột trung thành với Hoàng Gia. Chuột bảo hoàng đòi hỏi ít Lòng Dân hơn để chấp thuận và vui vẻ hơn trước điều kiện khắc nghiệt, nhưng từ chối buôn lậu hoặc chiến đấu. Chúng tin rằng công xưởng là một sự xúc phạm đối với ân sủng của Đức Vua.",
  "embark.scenario1.descV2": "Phe Móng Vuốt sẽ cử chủ yếu là những chú chuột trung thành với Hoàng Gia. Chuột bảo hoàng đòi hỏi ít Lòng Dân hơn để chấp thuận và vui vẻ hơn trước điều kiện khắc nghiệt, nhưng rất dễ nổi giận trước những lời lẽ phản nghịch. Chúng tin rằng công xưởng là một sự xúc phạm đối với ân sủng của Đức Vua.",

  "embark.scenario2": "Vùng Biển Hải Tặc",
  "embark.scenario2.desc": "Vùng biển này lúc nhúc hải tặc. Chúng đòi tiền chuộc tham lam hơn nhưng hàng buôn lậu lại bán được giá cao hơn nhiều. Tàu thu thuế xuất hiện ít thường xuyên hơn.",

  "embark.scenario3": "Biên Viễn Xa Xôi",
  "embark.scenario3.desc": "Rất ít chuột bảo hoàng bị lưu đày tới vùng biên viễn xa xôi này. Tàu thu thuế cập bến theo chu kỳ bình thường, nhưng có ít hải đảo hứng thú với hàng hóa buôn lậu hơn.",
  "embark.scenario3.descV2": "Rất ít chuột bảo hoàng bị lưu đày tới vùng biên viễn xa xôi này. Tàu thu thuế cập bến theo chu kỳ bình thường, nhưng khoảng cách xa xôi khiến giới buôn lậu đòi giá cao hơn cho mỗi thỏi vàng.",

  "embark.param.title": "Thiết Lập Bản Đồ",
  "embark.param.mapSize": "Kích Thước Bản Đồ",
  "embark.param.mainIslandSize": "Kích Thước Đảo Chính",
  "embark.param.extraIslands": "Số Đảo Phụ",
  "embark.param.barrenIslands": "Đảo Cằn Cỗi",
  "embark.param.winters": "Mùa Đông",
  "embark.param.newArrivals": "Chuột Tới Định Cư",
  "embark.param.clawGreed": "Lòng Tham Loài Mèo",
  "embark.param.piratePopulation": "Mật Độ Hải Tặc",
  "embark.param.pirateRaids": "Tần Suất Đột Kích",
  "embark.param.cropfertility": "Độ Phì Nhiêu Đất Trồng",
  "embark.param.pollutionpenalties": "Hình Phạt Ô Nhiễm",
  "embark.param.whiskerFickleness": "Tính Khí Thất Thường",
  "embark.param.researchCost": "Chi Phí Nghiên Cứu",
  "embark.param.resources": "Khoáng Sản & Độ Màu Mỡ",
  "embark.param.colonyName": "Tên Thuộc Địa",

  "embark.action.title": "Khởi Hành Ra Khơi",
  "embark.state.title": "Thuộc Địa",
  "embark.state.resources": "Tài Nguyên Ban Đầu",
  "embark.state.crew": "Thủy Thủ Đoàn",

  # Embark Choices
  "embark.choice.tiny": "Tí Hon",
  "embark.choice.small": "Nhỏ",
  "embark.choice.normal": "Bình Thường",
  "embark.choice.large": "Lớn",
  "embark.choice.giant": "Khổng Lồ",
  "embark.choice.oversize": "Siêu Lớn",
  "embark.choice.rare": "Hiếm",
  "embark.choice.common": "Phổ Biến",
  "embark.choice.lots": "Nhiều",
  "embark.choice.none": "Không Có",
  "embark.choice.few": "Ít",
  "embark.choice.occasional": "Thỉnh Thoảng",
  "embark.choice.often": "Thường Xuyên",
  "embark.choice.kind": "Nhân Từ",
  "embark.choice.fair": "Công Bằng",
  "embark.choice.survivable": "Chống Chọi Được",
  "embark.choice.oppressive": "Bóc Lột Khắc Nghiệt",
  "embark.choice.many": "Rất Nhiều",
  "embark.choice.highseas": "Chỉ Biển Sâu",
  "embark.choice.boosted": "Dồi Dào",
  "embark.choice.natural": "Tự Nhiên",
  "embark.choice.reduced": "Hạn Chế",
  "embark.choice.dangerous": "Nguy Cấp",
  "embark.choice.mild": "Ôn Hòa",
  "embark.choice.low": "Thấp",
  "embark.choice.high": "Cao",
  "embark.choice.veryhigh": "Rất Cao",
  "embark.choice.poor": "Nghèo Nàn",

  # 2. Colony Names (60 items)
  "colonyname.0": "Xứ Chuột Rodentia",
  "colonyname.1": "Làng Whiskerville",
  "colonyname.2": "Trấn Gnawington",
  "colonyname.3": "Hang Trú Burrowville",
  "colonyname.4": "Trấn Squeakton",
  "colonyname.5": "Trấn Skitterton",
  "colonyname.6": "Thị Trấn Fuzzborough",
  "colonyname.7": "Cảng Gió Airhaven",
  "colonyname.8": "Trấn Clawston",
  "colonyname.9": "Ấp Sniffwick",
  "colonyname.10": "Thôn Earham",
  "colonyname.11": "Bến Nước Scurryford",
  "colonyname.12": "Trấn Ogdenville",
  "colonyname.13": "Vùng North Haverbrook",
  "colonyname.14": "Trấn Brockway",
  "colonyname.15": "Đảo Nút Bần Newcork",
  "colonyname.16": "Đồng Rộng Overfield",
  "colonyname.17": "Cánh Đồng Mới",
  "colonyname.18": "Thửa Ruộng Paddyfield",
  "colonyname.19": "Bụi Thưa Sparsebrush",
  "colonyname.20": "Bụi Vàng Tanbrush",
  "colonyname.21": "Đảo Xanh Lushisle",
  "colonyname.22": "Đồng Lúa Vàng Tangrain",
  "colonyname.23": "Cánh Đồng Ngũ Cốc",
  "colonyname.24": "Rặng Liễu Lúa Mì",
  "colonyname.25": "Cảng Gỗ Woodport",
  "colonyname.26": "Bờ Đá Nhọn",
  "colonyname.27": "Hang Đất Vàng",
  "colonyname.28": "Hang Chuột Sâu",
  "colonyname.29": "Hang Chuột Ấm",
  "colonyname.30": "Kho Hang Chuột",
  "colonyname.31": "Đồi Hang Chuột",
  "colonyname.32": "Đồi Ngũ Cốc",
  "colonyname.33": "Đảo Ngũ Cốc",
  "colonyname.34": "Đảo Lúa Mì",
  "colonyname.35": "Đảo Cây Lanh",
  "colonyname.36": "Pháo Lũy Bastion",
  "colonyname.37": "Pháo Đài Mới",
  "colonyname.38": "Trấn Lũy Đá",
  "colonyname.39": "Thành Gạch Brickfort",
  "colonyname.40": "Thành Gạch Đỏ",
  "colonyname.41": "Vựa Thóc Cangrain",
  "colonyname.42": "Thị Trấn Tự Do",
  "colonyname.43": "Thị Trấn Nắng Ấm",
  "colonyname.44": "Trấn Vách Đá",
  "colonyname.45": "Thị Trấn Ven Biển",
  "colonyname.46": "Bờ Biển Muối Mỏ",
  "colonyname.47": "Khởi Đầu Mới",
  "colonyname.48": "Hang Vách Đá",
  "colonyname.49": "Mỏm Đá Dốc",
  "colonyname.50": "Vách Đá Xám",
  "colonyname.51": "Mái Ấm Mới",
  "colonyname.52": "Bến Lời Hứa",
  "colonyname.53": "Thành Trì Kiên Định",
  "colonyname.54": "Vòng Đá Stonewrap",
  "colonyname.55": "Mũi Đá Stonepoint",
  "colonyname.56": "Mỏm Đá Tận Cùng",
  "colonyname.57": "Đồi Niềm Tin",
  "colonyname.58": "Mũi Đất Vọng Ước",
  "colonyname.59": "Nông Trang Ven Biển",

  # 3. Seasons & Weather / World Effects (56 items)
  "season.Spring": "Mùa Xuân",
  "season.Summer": "Mùa Hạ",
  "season.Fall": "Mùa Thu",
  "season.Winter": "Mùa Đông",
  "season.Next": "Mùa Tiếp Theo",

  "worldeffect.pleasantWeather": "Khí Trời Dễ Chịu",
  "worldeffect.foulbreeze": "Gió Biển Tanh Nồng",
  "worldeffect.moltingtrees": "Mùa Cây Thay Vỏ",
  "worldeffect.weather_clear": "Trời Quang Mây Tạnh",
  "worldeffect.weather_lightrain": "Mưa Rào Nhẹ",
  "worldeffect.weather_heavyrain": "Mưa Tầm Tã",
  "worldeffect.weather_fog": "Sương Mù Nhẹ",
  "worldeffect.weather_lightsnow": "Tuyết Rơi Lất Phất",
  "worldeffect.weather_heavysnow": "Bão Tuyết",
  "worldeffect.warmSeasonEffect": "Mùa Ấm Áp",
  "worldeffect.coldSeasonEffect": "Mùa Băng Giá",
  "worldeffect.unsafeWaters": "Vùng Biển Mất An Ninh",
  "worldeffect.badfoodproduction": "Đại Dịch Sâu Bọ",
  "worldeffect.easymining": "Bí Quyết Đào Mỏ",
  "worldeffect.goodwill": "Thiện Chí",
  "worldeffect.intimidated": "Thị Uy Nghiêm Ngặt",
  "worldeffect.lowSpirits": "Tinh Thần Sa Sút",
  "worldeffect.qualityMachinery": "Dầu Bôi Trơn Cơ Khí",
  "worldeffect.richFuel": "Phụ Gia Nhiên Liệu",
  "worldeffect.quest.granarymice": "Sâu Mọt Kho Lương",
  "worldeffect.quest.taxIncrease": "Tăng Thuế Tự Nguyện",
  "worldeffect.pirateProtection": "Bảo Hộ Khỏi Hải Tặc",

  # World effect descriptions
  "worldeffect.desc.pleasantWeather": "Bà con chuột thỉnh thoảng nảy sinh cảm xúc tích cực khi ở dưới ánh nắng",
  "worldeffect.desc.foulbreeze": "Tỉ lệ nhỏ mắc bệnh khi ở gần bờ biển",
  "worldeffect.desc.moltingtrees": "Tốc độ đốn hạ cây tăng gấp đôi",
  "worldeffect.desc.weather_clear": "Tăng tốc độ phát triển của cây trồng",
  "worldeffect.desc.weather_lightrain": "Bể chứa nước lộ thiên tự tích thêm nước",
  "worldeffect.desc.weather_heavyrain": "• Giảm tốc độ di chuyển nếu bị ướt sũng\n• Bể chứa nước lộ thiên tự tích thêm nước",
  "worldeffect.desc.weather_fog": "Màn sương êm đềm bao phủ hòn đảo. Không có tác động gì",
  "worldeffect.desc.weather_lightsnow": "Khiến tâm trạng bà con hơi chùng xuống một chút",
  "worldeffect.desc.weather_heavysnow": "Giảm mạnh tốc độ di chuyển trên mặt đất không có sưởi ấm",
  "worldeffect.desc.warmSeasonEffect": "• Cây trồng phát triển bình thường\n• Nhiệt độ an toàn\n• Biển êm đềm, thuận lợi ra khơi",
  "worldeffect.desc.coldSeasonEffect": "• Cây trồng bắt đầu thối rữa\n• Giá rét nguy hiểm tới tính mạng\n• Vùng biển dữ dội, nguy hiểm khi ra khơi",
  "worldeffect.desc.badfoodproduction": "20% nguy cơ các xưởng chế biến thực phẩm không tạo ra sản lượng",
  "worldeffect.desc.easymining": "Tốc độ khai thác mỏ nhanh hơn 30%",
  "worldeffect.desc.goodwill": "Các chính sách có 30% tỉ lệ không tiêu tốn Lòng Dân khi kích hoạt",
  "worldeffect.desc.intimidated": "Tượng Quý Tộc Mèo nhân đôi hiệu ứng lên các chú chuột đi ngang qua",
  "worldeffect.desc.lowSpirits": "Cảm xúc tích cực có 20% nguy cơ không tạo ra Lòng Dân",
  "worldeffect.desc.qualityMachinery": "Máy móc công nghiệp hao mòn chậm hơn 50%",
  "worldeffect.desc.richFuel": "Các xưởng sản xuất nhiên liệu có 20% cơ hội nhân đôi sản lượng",
  "worldeffect.desc.quest.granarymice": "Đang thất thoát 2 phần thức ăn mỗi phút từ kho trữ",
  "worldeffect.desc.quest.taxIncrease": "Tăng số lượng thuế cống nạp phải nộp trong chuyến tàu thu thuế tiếp theo",
  "worldeffect.desc.pirateProtection": "Hải tặc sẽ không phái thuyền đột kích chừng nào bạn còn được bảo hộ",

  # World effect flavor texts
  "worldeffect.flavortext.pleasantWeather": "Vài ngày nắng đẹp giúp tinh thần bà con phấn chấn hẳn lên",
  "worldeffect.flavortext.foulbreeze": "Luồng gió tanh tưởi bốc lên từ đại dương",
  "worldeffect.flavortext.moltingtrees": "Cây cối mềm lớp vỏ ngoài",
  "worldeffect.flavortext.weather_clear": "Ánh mặt trời ấm áp chiếu rọi muôn nơi",
  "worldeffect.flavortext.weather_lightrain": "Cơn mưa phùn êm ả ru lòng người",
  "worldeffect.flavortext.weather_heavyrain": "Trận mưa rào như trút nước mịt mù",
  "worldeffect.flavortext.weather_fog": "Màn sương mù dày đặc",
  "worldeffect.flavortext.weather_lightsnow": "Những bông tuyết rơi lất phất lặng lẽ",
  "worldeffect.flavortext.weather_heavysnow": "Tuyết đóng dày ngập ngụa khắp lối đi",
  "worldeffect.flavortext.warmSeasonEffect": "Mùa của sinh sôi nảy nở, giao thương tấp nập và khí trời ấm áp",
  "worldeffect.flavortext.coldSeasonEffect": "Mùa sinh tồn khốc liệt",
  "worldeffect.flavortext.badfoodproduction": "Sâu bọ tràn vào quấy phá các gian bếp!",
  "worldeffect.flavortext.easymining": "Đất đá trở nên mềm và dễ đục đẽo hơn",
  "worldeffect.flavortext.goodwill": "Bà con chuột đang trong tâm trạng vô cùng phấn chấn",
  "worldeffect.flavortext.intimidated": "Cảm giác như luôn có đôi mắt sắc lạnh dõi theo sau gáy",
  "worldeffect.flavortext.lowSpirits": "Bầu không khí ảm đạm bao trùm toàn thể làng chuột",
  "worldeffect.flavortext.qualityMachinery": "Một ví dụ kiểu mẫu về kỹ nghệ cơ khí chính xác",
  "worldeffect.flavortext.richFuel": "Than đá và gỗ cháy rực rỡ sáng bừng",
  "worldeffect.flavortext.quest.granarymice": "Này, cái đó là của tôi mà!",

  # 4. Docked Ships (25 items)
  "dockedship.whiskers.shipname": "Tàu Chở Dân Chuột",
  "dockedship.whiskers.flavor": "Bà con nhà chuột đang háo hức muốn đặt chân lên đảo.",
  "dockedship.whiskers.flavorquote": "Cầu mong nơi này sẽ tốt đẹp hơn...",
  "dockedship.pirates.shipname": "Tàu Hải Tặc Phong Tỏa",
  "dockedship.pirates.header": "Hải Tặc Đòi Tiếp Tế!",
  "dockedship.pirates.hint": "Chất tài nguyên lên tàu để xoa dịu lũ hải tặc.",
  "dockedship.pirates.retaliationwarning": "Hải tặc sẽ trả đũa khốc liệt!",
  "dockedship.pirates.satisfied": "Hải tặc đã thỏa mãn.",
  "dockedship.pirates.threat": "Đe dọa nã <0> quả đạn pháo",
  "dockedship.pirates.flavorquote": "Thật đáng tiếc nếu đôi bên không tìm được tiếng nói chung...",
  "dockedship.startingSupplies.header": "Hàng tiếp tế ban đầu đã cập bến.",
  "dockedship.supplier.shipname": "Tàu Tiếp Tế",
  "dockedship.supplier.header": "Chọn một kiện hàng tiếp tế",
  "dockedship.supplier.flavorquote": "Quý Tộc Móng Vuốt rộng lượng ban phát cho ngươi hàng tiếp tế.",
  "dockedship.supplier.debtwarning": "Nợ mới phát sinh",
  "dockedship.supplier.debtwarning.tooltip": "Bạn sẽ nợ thêm chừng này thuế trong đợt thu thuế tiếp theo.",
  "dockedship.supplier.winterfee": "Phụ phí mùa đông tăng cao!",
  "dockedship.action.unloadShipment": "Dỡ Hàng Xuống Bến",
  "dockedship.action.rejectShipment": "Từ Chối Kiện Hàng",
  "dockedship.tax.shipname": "Tàu Thu Thuế Cống Nạp",
  "dockedship.tax.flavorquote": "Để xem hôm nay các ngươi chuẩn bị được những gì cho chúng ta...",
  "dockedship.smugglertrader.shipname": "Thuyền Buôn Lậu",
  "dockedship.smugglertrader.flavorquote": "Có lẽ chúng ta có thể giúp đỡ lẫn nhau đấy...",
  "dockedship.departingTimer": "Rời bến sau:",
  "dockedship.none": "Hiện không có tàu nào cập bến.",

  # 5. Nautical Encounters, Diplomacy & War (80 items)
  "nautical.decision.inspect.title": "Cho Quan Kiểm Tra Lên Tàu?",
  "nautical.decision.inspect.desc": "Chiếu theo lệnh của Đức Vua, các ngươi phải cho phép chúng ta khám tàu. Đang có tin báo về hoạt động buôn lậu ở vùng biển này.",
  "nautical.decision.extortion.title": "Nộp Tiền Chuộc?",
  "nautical.decision.extortion.desc": "Tiền hay mạng? Lấy cái nào bọn ta cũng thích, nhưng tốt hơn là ngươi nên chọn nộp tiền.",
  "nautical.decision.war.title": "Tuyên Chiến?",
  "nautical.decision.war.desc": "Tấn công tàu của chúng sẽ châm ngòi cho một cuộc chiến toàn diện.",
  "nautical.decision.wait.title": "Đang Chờ Mệnh Lệnh",
  "nautical.decision.wait.desc": "Chúng tôi cần lệnh mới! Điểm đến tiếp theo ở đâu?",
  "nautical.decision.allow": "Cho Khám Tàu",
  "nautical.decision.pay": "Nộp Tiền Chuộc",
  "nautical.decision.declarewar": "Cứ Tấn Công",
  "nautical.decision.refuse": "Từ Chối",
  "nautical.cancel": "Hủy Lệnh",
  "nautical.auto": "TỰ ĐỘNG",
  "nautical.manual": "THỦ CÔNG",

  # Island discoveries
  "nautical.foundisland.action": "Đã Rõ",
  "nautical.decision.found.title": "Phát Hiện Đảo Mới!",
  "nautical.decision.found.whisker": "Chúng ta đã phát hiện một hòn đảo mới có bà con chuột sinh sống! Họ sẵn sàng mua bán hàng hóa với mức giá rất phải chăng.",
  "nautical.decision.found.pirate": "Một hòn đảo của lũ hải tặc. Hãy tránh xa kẻo tàu thuyền của chúng ta bị tấn công. Chừng nào chưa đúc đủ đại bác và đóng thêm tàu chiến, tốt nhất nên né hòn đảo này.",
  "nautical.decision.found.claw": "Phe Móng Vuốt kiểm soát hòn đảo này.",
  "nautical.decision.found.empty": "Đáng tiếc là không có ai sống trên hòn đảo này. Nhưng ít ra ở đây cũng chẳng có bóng dáng tên hải tặc nào.",
  "nautical.found.title.whisker": "Phát Hiện Thuộc Địa Chuột!",
  "nautical.found.title.claw": "Phát Hiện Đảo Phe Móng Vuốt!",
  "nautical.found.title.pirate": "Phát Hiện Đảo Hải Tặc!",
  "nautical.found.title.empty": "Phát Hiện Đảo Hoang!",

  # Flags
  "nautical.flag.discovery": "KHÁM PHÁ",
  "nautical.flag.danger": "NGUY HIỂM",
  "nautical.flag.question": "NGHI VẤN",
  "nautical.flag.request": "YÊU CẦU",

  # Diplomacy
  "nautical.diplo.title": "NGOẠI GIAO",
  "nautical.diplo.starttrade": "Đề Xuất Giao Thương",
  "nautical.diplo.requestrepair": "Yêu Cầu Sửa Tàu",
  "nautical.diplo.declarewar": "Tuyên Chiến",
  "nautical.diplo.demandransom": "Đòi Tiền Chuộc",
  "nautical.diplo.sellschematics": "Bán Bản Vẽ Kỹ Thuật",
  "nautical.status": "Tình Trạng",
  "nautical.relationship": "Mối Quan Hệ",
  "nautical.rel.hostile": "Thù Địch",
  "nautical.rel.despised": "Khinh Miệt",
  "nautical.rel.troubled": "Căng Thẳng",
  "nautical.rel.cordial": "Hòa Hoãn",
  "nautical.rel.friendly": "Thân Thiện",
  "nautical.rel.beloved": "Yêu Quý",
  "nautical.rel.allied": "Đồng Minh",

  # Trade
  "nautical.trade.title": "GIAO THƯƠNG",
  "nautical.trade.all": "Tất Cả",
  "nautical.trade.buy": "Mua",
  "nautical.trade.sell": "Bán",
  "nautical.trade.shipLacksGold": "Tàu không có Vàng Thỏi để trao đổi",
  "nautical.trade.shipFull": "Khoang tàu đã đầy",
  "nautical.trade.delaytrade": "Tạm Hoãn Giao Thương",
  "nautical.trade.finalize": "Hoàn Tất & Về Cảng Nhà",
  "nautical.cargo": "Hàng Hóa",
  "nautical.highseas": "Biển Khơi",

  # Naval War
  "nautical.enemy.claws": "Phe Móng Vuốt",
  "nautical.enemy.pirates": "Hải Tặc",
  "nautical.war.revolution": "Khởi Nghĩa Chống Phe Móng Vuốt",
  "nautical.war.piratewave": "Xung Đột Với Hải Tặc",
  "nautical.war.wave": "Đợt Tấn Công",
  "nautical.war.noshipsseen": "Chưa Thấy Tàu Địch",
  "nautical.war.shipsingle": "Tàu",
  "nautical.war.shipplural": "Tàu",
  "nautical.war.incoming": "Đang Tiếp Cận",

  # 6. Ship Tasks & Actions (45 items)
  # Tasks (Trạng thái hiển thị trên tàu)
  "nautical.task.fishing": "Đang đánh bắt cá",
  "nautical.task.smuggling": "Đang buôn lậu",
  "nautical.task.repairing": "Đang sửa chữa",
  "nautical.task.returning": "Đang quay về bến",
  "nautical.task.scouting": "Đang giương buồm",
  "nautical.task.mailing": "Đang chuyển thư",
  "nautical.task.attacking": "Đang cơ động tác chiến",
  "nautical.task.countering": "Đang phản công",
  "nautical.task.fleeing": "Đang đói lả!",
  "nautical.task.salvaging": "Đang trục vớt",
  "nautical.task.trade": "Đang giao thương",
  "nautical.task.repair": "Đang sửa chữa",
  "nautical.task.gonefishing": "Đang ra ngư trường",
  "nautical.task.idling": "Đang dừng tàu",
  "nautical.task.docked": "Đã cập bến",
  "nautical.task.docking": "Đang cập bến",
  "nautical.task.trading": "Đang giao thương",
  "nautical.task.harvestguano": "Đang gom phân chim",
  "nautical.task.escortship": "Đang hộ tống",
  "nautical.task.bombardtower": "Đang pháo kích",
  "nautical.task.Ferry": "Đang đưa đón dân chuột",
  "nautical.task.taxcollection": "Đang thu thuế",
  "nautical.task.supplyrun": "Đang tiếp tế",
  "nautical.task.smuggle": "Đang buôn lậu",
  "nautical.task.labortransport": "Đang chở nhân lực",
  "nautical.task.extortion": "Đang tống tiền",
  "nautical.task.salvage": "Đang trục vớt",

  # Actions (Nút lệnh điều khiển tàu)
  "nautical.action.attack": "Tấn Công Hải Tặc",
  "nautical.action.fish": "Đánh Bắt Cá",
  "nautical.action.flee": "Ép Cập Bến",
  "nautical.action.mail": "Chuyển Thư Từ",
  "nautical.action.repair": "Sửa Chữa Hư Hại",
  "nautical.action.return": "Quay Về Cảng Nhà",
  "nautical.action.salvage": "Trục Vớt",
  "nautical.action.scout": "Giương Buồm Tới Đây",
  "nautical.action.smuggle": "Buôn Lậu Hàng Hóa",
  "nautical.action.trade": "Giao Thương",
  "nautical.action.starttrade": "Xem Chào Hàng Giao Thương",
  "nautical.action.rescue": "Cứu Người Sống Sót",
  "nautical.action.hunting": "Săn Quái Thú Biển",
  "nautical.action.dock": "Cập Bến",
  "nautical.action.idle": "Dừng Lại & Chờ Lệnh",
  "nautical.action.harvestguano": "Thu Gom Phân Chim Biển",
  "nautical.action.escortship": "Hộ Tống Tàu",
  "nautical.action.bombardtower": "Pháo Kích Tháp Canh",
  "nautical.action.taxcollection": "Thu Thuế Cống Nạp",
  "nautical.action.supplyrun": "Chuyến Tiếp Tế",
  "nautical.action.labortransport": "Chở Nhân Lực Chuột",
  "nautical.action.extortion": "Tống Tiền",

  # Descriptions, hints, keyhints
  "nautical.flee.desc": "Thủy thủ đoàn đã tự quay mũi tàu về nhà vì nhu yếu phẩm không đủ cho chuyến hải trình tiếp theo. Họ sẽ không nghe theo bất kỳ mệnh lệnh nào nữa.",
  "nautical.docked.desc": "Tàu đang neo đậu tại bến và không thể nhận lệnh cho tới khi giương buồm ra khơi.",
  "nautical.localferry.desc": "Tàu được phân công chạy tuyến phà nội bộ và không thể điều khiển trực tiếp.",
  "ferrydock.hint": "Tàu được gán vào Bến Phà Đảo không thể điều khiển thủ công",
  "nautical.supportedTasks": "Các Hành Động Khả Dụng",
  "nautical.keyhint.selectShips": "Chọn Tàu",
  "nautical.keyhint.unselectShips": "Bỏ Chọn Tàu",
  "nautical.keyhint.issueOrder": "Ra Mệnh Lệnh",
  "ship.viewOnMap": "Xem trên bản đồ",
  "ship.assign": "Gán vào bến cảng",
  "ship.reassign": "Đổi sang bến cảng mới",
  "ship.stormie": "Tàu bị Stormie đánh cắp"
}

def apply_translation():
    with open(JSON_PATH, 'r', encoding='utf-8') as f:
        data = json.load(f)

    applied_count = 0
    missing = []
    for item in data:
        key = item.get('key')
        if key in T:
            item['target_vi'] = T[key]
            applied_count += 1
        else:
            missing.append((item['id'], key, item.get('source_en')))

    with open(JSON_PATH, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Applied translation to {applied_count} / {len(data)} items in Phase 5!")
    if missing:
        print(f"Missing {len(missing)} items:")
        for m in missing[:20]:
            print(" ", m)
    else:
        print("All 339 Phase 5 items translated 100%!")

if __name__ == "__main__":
    apply_translation()
